apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app: opsgenie-heartbeat
    release: prometheus-operator
  name: opsgenie-heartbeat
  namespace: monitoring
spec:
  endpoints:
  - port: metrics
    interval: 60s
    scrapeTimeout: 30s
  selector:
    matchLabels:
      app: opsgenie-heartbeat
