modules:
  http_2xx:
    prober: http
    http:
      preferred_ip_protocol: "ip4"
# Personal check in case of access via IP and ignore certificate check
# wget -O - 'http://blackbox-exporter:9115/probe?module=https_example_com&target=https://192.168.1.1'
# https_example_com:
#   prober: http
#   http:
#     preferred_ip_protocol: "ip4"
#     headers:
#       Host: "example.com"
#     tls_config:
#       insecure_skip_verify: true
#     valid_status_codes:
#       - 400
#     fail_if_header_not_matches:
#       - header: "content-type"
#         regexp: "application/json"
  tcp_connect:
    prober: tcp
    timeout: 5s

