groups:
  - name: "host down alerts - node_exporter"
    rules:
      - alert: "kubernetes node down P4-5"
        expr: up{job="node_exporter kubernetes",host_priority=~"P[4-5]|^$",instance=~".*:9100"} == 0
        for: 30m
        annotations:
          summary: "kubernetes node down"
          description: 'Connect to cluster: "{{ $labels.cluster_name }}" in env: "{{ $labels.server_env }}" and check if node: "{{ $labels.node_name }}" is running or pod: "{{ $labels.pod_name }}" is running on node'
          grafana: "https://grafana.monitoring-test.shalb.com/d/1xIGyoZZz/eks-metrics?orgId=1&var-server_env={{ $labels.server_env }}&var-node_name={{ $labels.node_name }}&var-namespace={{ $labels.namespace }}&var-pod_name={{ $labels.pod_name }}&var-service_name={{ $labels.service }}&panelId=146&fullscreen"
          access: "https://confluence.shalb.com/display/TEST/Access#Access-Grafana,Prometheus,Alertmanager"
          priority: "P2"

      - alert: "kubernetes node down P1-3"
        expr: up{job="node_exporter kubernetes",host_priority=~"P[1-3]",instance=~".*:9100"} == 0
        for: 20m
        annotations:
          summary: "kubernetes node down"
          description: 'Connect to cluster: "{{ $labels.cluster_name }}" in env: "{{ $labels.server_env }}" and check if node: "{{ $labels.node_name }}" is running or pod: "{{ $labels.pod_name }}" is running on node'
          grafana: "https://grafana.monitoring-test.shalb.com/d/1xIGyoZZz/eks-metrics?orgId=1&var-server_env={{ $labels.server_env }}&var-node_name={{ $labels.node_name }}&var-namespace={{ $labels.namespace }}&var-pod_name={{ $labels.pod_name }}&var-service_name={{ $labels.service }}&panelId=146&fullscreen"
          access: "https://confluence.shalb.com/display/TEST/Access#Access-Grafana,Prometheus,Alertmanager"
          priority: "P2"


  - name: "parse errors - node_exporter"
    rules:
      - alert: "node_exporter kubernetes has new errors P1-3"
        expr: node_scrape_collector_success{job="node_exporter kubernetes",host_priority=~"P[1-3]"} != 1
        for: 5m
        annotations:
          summary: "node_exporter kubernetes has new errors for some collectors"
          description: 'Connect to cluster: "{{ $labels.cluster_name }}" in env: "{{ $labels.server_env }}" and check logs for pod: "{{ $labels.pod_name }}"'
          grafana: "https://grafana.monitoring-test.shalb.com/d/1xIGyoZZz/eks-metrics?orgId=1&var-server_env={{ $labels.server_env }}&var-node_name={{ $labels.node_name }}&var-namespace={{ $labels.namespace }}&var-pod_name={{ $labels.pod_name }}&var-service_name={{ $labels.service }}&panelId=147&fullscreen"
          access: "https://confluence.shalb.com/display/TEST/Access#Access-Grafana,Prometheus,Alertmanager"
          priority: "P2"
        labels:
          team: monitoring

      - alert: "node_exporter kubernetes has new errors P4-5"
        expr: node_scrape_collector_success{job="node_exporter kubernetes",host_priority=~"P[4-5]"} != 1
        for: 15m
        annotations:
          summary: "node_exporter kubernetes has new errors for some collectors"
          description: 'Connect to cluster: "{{ $labels.cluster_name }}" in env: "{{ $labels.server_env }}" and check logs for pod: "{{ $labels.pod_name }}"'
          grafana: "https://grafana.monitoring-test.shalb.com/d/1xIGyoZZz/eks-metrics?orgId=1&var-server_env={{ $labels.server_env }}&var-node_name={{ $labels.node_name }}&var-namespace={{ $labels.namespace }}&var-pod_name={{ $labels.pod_name }}&var-service_name={{ $labels.service }}&panelId=147&fullscreen"
          access: "https://confluence.shalb.com/display/TEST/Access#Access-Grafana,Prometheus,Alertmanager"
          priority: "P3"
        labels:
          team: monitoring


  - name: "absent data - node_exporter"
    rules:
      - alert: "data absent for node_exporter P1-3"
        expr: ((up{instance=~".*:9100",job="node_exporter kubernetes",host_priority=~"P[1-3]"} + node_boot_time_seconds) or (up{instance=~".*:9100",job="node_exporter kubernetes",host_priority=~"P[1-3]"})) == 1
        for: 10m
        annotations:
          summary: "data absent for node_exporter"
          description: 'Go to host: "{{ $labels.hostname }}" and check log for node_exporter'
          grafana: "https://grafana.monitoring-test.shalb.com/d/FymDFbpZk/node-exporter?panelId=131&fullscreen&orgId=1&var-server_env={{ $labels.server_env }}&var-project={{ $labels.project }}&var-hostname={{ $labels.hostname }}"
          access: "https://confluence.shalb.com/display/TEST/Access#Access-Grafana,Prometheus,Alertmanager"
          priority: "P3"
        labels:
          team: monitoring

      - alert: "data absent for node_exporter P4-5"
        expr: ((up{instance=~".*:9100",job="node_exporter kubernetes",host_priority=~"P[4-5]|^$"} + node_boot_time_seconds) or (up{instance=~".*:9100",job="node_exporter kubernetes",host_priority=~"P[4-5]|^$"})) == 1
        for: 30m
        annotations:
          summary: "data absent for node_exporter"
          description: 'Go to host: "{{ $labels.hostname }}" and check log for node_exporter'
          grafana: "https://grafana.monitoring-test.shalb.com/d/FymDFbpZk/node-exporter?panelId=131&fullscreen&orgId=1&var-server_env={{ $labels.server_env }}&var-project={{ $labels.project }}&var-hostname={{ $labels.hostname }}"
          access: "https://confluence.shalb.com/display/TEST/Access#Access-Grafana,Prometheus,Alertmanager"
          priority: "P5"
        labels:
          team: monitoring

