groups:
  - name: "kubernetes_exporter down alerts"
    rules:
      - alert: "kubernetes_exporter down P5"
        expr: up{host_priority="P5",instance=~".*:9610"} == 0
        for: 10m
        annotations:
          summary: "kubernetes_exporter down"
          description: 'Connect to cluster: "{{ $labels.cluster_name }}" in env: "{{ $labels.server_env }}" and check if service: "kubernetes-exporter" is running'
          grafana: "https://grafana.monitoring-test.shalb.com/d/1xIGyoZZz/eks-metrics?orgId=1&var-server_env={{ $labels.server_env }}&panelId=83&fullscreen"
          access: "https://confluence.shalb.com/display/TEST/Access#Access-Grafana,Prometheus,Alertmanager"
          priority: "P3"

      - alert: "kubernetes_exporter down P4"
        expr: up{host_priority="P4",instance=~".*:9610"} == 0
        for: 5m
        annotations:
          summary: "kubernetes_exporter down"
          description: 'Connect to cluster: "{{ $labels.cluster_name }}" in env: "{{ $labels.server_env }}" and check if service: "kubernetes-exporter" is running'
          grafana: "https://grafana.monitoring-test.shalb.com/d/1xIGyoZZz/eks-metrics?orgId=1&var-server_env={{ $labels.server_env }}&panelId=83&fullscreen"
          access: "https://confluence.shalb.com/display/TEST/Access#Access-Grafana,Prometheus,Alertmanager"
          priority: "P3"

      - alert: "kubernetes_exporter down P3"
        expr: up{host_priority=~"P3|^$",instance=~".*:9610"} == 0
        for: 4m
        annotations:
          summary: "kubernetes_exporter down"
          description: 'Connect to cluster: "{{ $labels.cluster_name }}" in env: "{{ $labels.server_env }}" and check if service: "kubernetes-exporter" is running'
          grafana: "https://grafana.monitoring-test.shalb.com/d/1xIGyoZZz/eks-metrics?orgId=1&var-server_env={{ $labels.server_env }}&panelId=83&fullscreen"
          access: "https://confluence.shalb.com/display/TEST/Access#Access-Grafana,Prometheus,Alertmanager"
          priority: "P2"

      - alert: "kubernetes_exporter down P2"
        expr: up{host_priority="P2",instance=~".*:9610"} == 0
        for: 3m
        annotations:
          summary: "kubernetes_exporter down"
          description: 'Connect to cluster: "{{ $labels.cluster_name }}" in env: "{{ $labels.server_env }}" and check if service: "kubernetes-exporter" is running'
          grafana: "https://grafana.monitoring-test.shalb.com/d/1xIGyoZZz/eks-metrics?orgId=1&var-server_env={{ $labels.server_env }}&panelId=83&fullscreen"
          access: "https://confluence.shalb.com/display/TEST/Access#Access-Grafana,Prometheus,Alertmanager"
          priority: "P2"

      - alert: "kubernetes_exporter down P1"
        expr: up{host_priority="P1",instance=~".*:9610"} == 0
        for: 2m
        annotations:
          summary: "kubernetes_exporter down"
          description: 'Connect to cluster: "{{ $labels.cluster_name }}" in env: "{{ $labels.server_env }}" and check if service: "kubernetes-exporter" is running'
          grafana: "https://grafana.monitoring-test.shalb.com/d/1xIGyoZZz/eks-metrics?orgId=1&var-server_env={{ $labels.server_env }}&panelId=83&fullscreen"
          access: "https://confluence.shalb.com/display/TEST/Access#Access-Grafana,Prometheus,Alertmanager"
          priority: "P1"


  - name: "parse errors - kubernetes_exporter"
    rules:
      - alert: "kubernetes_exporter has new errors P1-3"
        expr: kubernetes_exporter_up{host_priority=~"P[1-3]"} != 1
        for: 5m
        annotations:
          summary: "kubernetes_exporter has new errors"
          description: 'Connect to cluster: "{{ $labels.cluster_name }}" in env: "{{ $labels.server_env }}" and check logs for service: "kubernetes-exporter"'
          grafana: "https://grafana.monitoring-test.shalb.com/d/1xIGyoZZz/eks-metrics?orgId=1&var-server_env={{ $labels.server_env }}&panelId=145&fullscreen"
          access: "https://confluence.shalb.com/display/TEST/Access#Access-Grafana,Prometheus,Alertmanager"
          priority: "P2"
        labels:
          team: monitoring

      - alert: "kubernetes_exporter has new errors P4-5"
        expr: kubernetes_exporter_up{host_priority=~"P[4-5]|^$"} != 1
        for: 15m
        annotations:
          summary: "kubernetes_exporter has new errors"
          description: 'Connect to cluster: "{{ $labels.cluster_name }}" in env: "{{ $labels.server_env }}" and check logs for service: "kubernetes-exporter"'
          grafana: "https://grafana.monitoring-test.shalb.com/d/1xIGyoZZz/eks-metrics?orgId=1&var-server_env={{ $labels.server_env }}&panelId=145&fullscreen"
          access: "https://confluence.shalb.com/display/TEST/Access#Access-Grafana,Prometheus,Alertmanager"
          priority: "P3"
        labels:
          team: monitoring


  - name: "nodes alerts - kubernetes_exporter"
    rules:
      - alert: "kubernetes_exporter - node is not ready P1-2"
        expr: kubernetes_node_condition{condition="Ready",host_priority=~"P[1-2]"} != 1
        for: 2m
        annotations:
          summary: "node is not ready"
          description: 'Connect to cluster: "{{ $labels.cluster_name }}" in env: "{{ $labels.server_env }}" and check why node: "{{ $labels.node_name }}" is not ready'
          grafana: "https://grafana.monitoring-test.shalb.com/d/1xIGyoZZz/eks-metrics?orgId=1&var-server_env={{ $labels.server_env }}&var-node_name={{ $labels.node_name }}&panelId=103&fullscreen"
          access: "https://confluence.shalb.com/display/TEST/Access#Access-Grafana,Prometheus,Alertmanager"
          priority: "P3"

      - alert: "kubernetes_exporter - node is not ready P4-5"
        expr: kubernetes_node_condition{condition="Ready",host_priority=~"P[4-5]|^$"} != 1
        for: 10m
        annotations:
          summary: "node is not ready"
          description: 'Connect to cluster: "{{ $labels.cluster_name }}" in env: "{{ $labels.server_env }}" and check why node: "{{ $labels.node_name }}" is not ready'
          grafana: "https://grafana.monitoring-test.shalb.com/d/1xIGyoZZz/eks-metrics?orgId=1&var-server_env={{ $labels.server_env }}&var-node_name={{ $labels.node_name }}&panelId=103&fullscreen"
          access: "https://confluence.shalb.com/display/TEST/Access#Access-Grafana,Prometheus,Alertmanager"
          priority: "P3"


  - name: "pod alerts - kubernetes_exporter"
    rules:
      - alert: "kubernetes_exporter - pod is not running P1-2"
        expr: kubernetes_pod_phase{host_priority=~"P[1-2]"} != 1
        for: 2m
        annotations:
          summary: "pod is not running"
          description: 'Connect to cluster: "{{ $labels.cluster_name }}" in env: "{{ $labels.server_env }}" and check why pod: "{{ $labels.pod_name }}" is not running'
          grafana: "https://grafana.monitoring-test.shalb.com/d/1xIGyoZZz/eks-metrics?orgId=1&var-server_env={{ $labels.server_env }}&var-node_name={{ $labels.node_name }}&var-namespace={{ $labels.namespace }}&var-pod_name={{ $labels.pod_name }}&var-service_name={{ $labels.service }}&panelId=109&fullscreen"
          access: "https://confluence.shalb.com/display/TEST/Access#Access-Grafana,Prometheus,Alertmanager"
          priority: "P3"

      - alert: "kubernetes_exporter - pod is not running P4-5"
        expr: kubernetes_pod_phase{host_priority=~"P[4-5]|^$"} != 1
        for: 10m
        annotations:
          summary: "pod is not running"
          description: 'Connect to cluster: "{{ $labels.cluster_name }}" in env: "{{ $labels.server_env }}" and check why pod: "{{ $labels.pod_name }}" is not running'
          grafana: "https://grafana.monitoring-test.shalb.com/d/1xIGyoZZz/eks-metrics?orgId=1&var-server_env={{ $labels.server_env }}&var-node_name={{ $labels.node_name }}&var-namespace={{ $labels.namespace }}&var-pod_name={{ $labels.pod_name }}&var-service_name={{ $labels.service }}&panelId=109&fullscreen"
          access: "https://confluence.shalb.com/display/TEST/Access#Access-Grafana,Prometheus,Alertmanager"
          priority: "P3"


  - name: "containers alerts - kubernetes_exporter"
    rules:
      - alert: "kubernetes_exporter - container restarts to often P1-2"
        expr: delta(kubernetes_container_restarts_total{host_priority=~"P[1-2]"}[1h]) > 10
        for: 2m
        annotations:
          summary: "container restarts to often"
          description: 'Connect to cluster: "{{ $labels.cluster_name }}" in env: "{{ $labels.server_env }}" and check why container: "{{ $labels.container_name }}" restarts to often'
          grafana: "https://grafana.monitoring-test.shalb.com/d/1xIGyoZZz/eks-metrics?orgId=1&var-server_env={{ $labels.server_env }}&var-node_name={{ $labels.node_name }}&var-namespace={{ $labels.namespace }}&var-pod_name={{ $labels.pod_name }}&var-service_name={{ $labels.service }}&var-container_name={{ $labels.container_name }}&panelId=102&fullscreen"
          access: "https://confluence.shalb.com/display/TEST/Access#Access-Grafana,Prometheus,Alertmanager"
          priority: "P3"

      - alert: "kubernetes_exporter - container restarts to often P4-5"
        expr: delta(kubernetes_container_restarts_total{host_priority=~"P[4-5]|^$"}[1h]) > 10
        for: 10m
        annotations:
          summary: "container restarts to often"
          description: 'Connect to cluster: "{{ $labels.cluster_name }}" in env: "{{ $labels.server_env }}" and check why container: "{{ $labels.container_name }}" restarts to often'
          grafana: "https://grafana.monitoring-test.shalb.com/d/1xIGyoZZz/eks-metrics?orgId=1&var-server_env={{ $labels.server_env }}&var-node_name={{ $labels.node_name }}&var-namespace={{ $labels.namespace }}&var-pod_name={{ $labels.pod_name }}&var-service_name={{ $labels.service }}&var-container_name={{ $labels.container_name }}&panelId=102&fullscreen"
          access: "https://confluence.shalb.com/display/TEST/Access#Access-Grafana,Prometheus,Alertmanager"
          priority: "P3"


      - alert: "kubernetes_exporter - container is not running P1-2"
        expr: kubernetes_container_ready{host_priority=~"P[1-2]"} != 1
        for: 2m
        annotations:
          summary: "container is not running"
          description: 'Connect to cluster: "{{ $labels.cluster_name }}" in env: "{{ $labels.server_env }}" and check why container: "{{ $labels.container_name }}" is not running'
          grafana: "https://grafana.monitoring-test.shalb.com/d/1xIGyoZZz/eks-metrics?orgId=1&var-server_env={{ $labels.server_env }}&var-node_name={{ $labels.node_name }}&var-namespace={{ $labels.namespace }}&var-pod_name={{ $labels.pod_name }}&var-service_name={{ $labels.service }}&var-container_name={{ $labels.container_name }}&panelId=122&fullscreen"
          access: "https://confluence.shalb.com/display/TEST/Access#Access-Grafana,Prometheus,Alertmanager"
          priority: "P3"

      - alert: "kubernetes_exporter - container is not running P4-5"
        expr: kubernetes_container_ready{host_priority=~"P[4-5]|^$"} != 1
        for: 10m
        annotations:
          summary: "container is not running"
          description: 'Connect to cluster: "{{ $labels.cluster_name }}" in env: "{{ $labels.server_env }}" and check why container: "{{ $labels.container_name }}" is not running'
          grafana: "https://grafana.monitoring-test.shalb.com/d/1xIGyoZZz/eks-metrics?orgId=1&var-server_env={{ $labels.server_env }}&var-node_name={{ $labels.node_name }}&var-namespace={{ $labels.namespace }}&var-pod_name={{ $labels.pod_name }}&var-service_name={{ $labels.service }}&var-container_name={{ $labels.container_name }}&panelId=122&fullscreen"
          access: "https://confluence.shalb.com/display/TEST/Access#Access-Grafana,Prometheus,Alertmanager"
          priority: "P3"

