groups:
  - name: "blackbox_exporter http checks host up"
    rules:
      - alert: "Http check fails P1"
        expr: probe_success{host_priority="P1",job!="blackbox-exporter kubernetes services"} != 1
        for: 1m
        annotations:
          summary: "Http check fails"
          description: 'Check host: "{{ $labels.instance }}" and find appropriate servers, which serving it to fix the problem.'
          grafana: "{{ GRAFANA_HTTP_STATUS_DASHBOARD }}"
          access: "{{ WIKI_MONITORING_ACCESS }}"
          priority: "P1"

      - alert: "Http check fails P2"
        expr: probe_success{host_priority="P2",job!="blackbox-exporter kubernetes services"} != 1
        for: 2m
        annotations:
          summary: "Http check fails"
          description: 'Check host: "{{ $labels.instance }}" and find appropriate servers, which serving it to fix the problem.'
          grafana: "{{ GRAFANA_HTTP_STATUS_DASHBOARD }}"
          access: "{{ WIKI_MONITORING_ACCESS }}"
          priority: "P2"

      - alert: "Http check fails P3"
        expr: probe_success{host_priority="P3",job!="blackbox-exporter kubernetes services"} != 1
        for: 5m
        annotations:
          summary: "Http check fails"
          description: 'Check host: "{{ $labels.instance }}" and find appropriate servers, which serving it to fix the problem.'
          grafana: "{{ GRAFANA_HTTP_STATUS_DASHBOARD }}"
          access: "{{ WIKI_MONITORING_ACCESS }}"
          priority: "P3"

      - alert: "Http check fails P4"
        expr: probe_success{host_priority="P4",job!="blackbox-exporter kubernetes services"} != 1
        for: 10m
        annotations:
          summary: "Http check fails"
          description: 'Check host: "{{ $labels.instance }}" and find appropriate servers, which serving it to fix the problem.'
          grafana: "{{ GRAFANA_HTTP_STATUS_DASHBOARD }}"
          access: "{{ WIKI_MONITORING_ACCESS }}"
          priority: "P4"

      - alert: "Http check fails P5"
        expr: probe_success{host_priority="P5",job!="blackbox-exporter kubernetes services"} != 1
        for: 20m
        annotations:
          summary: "Http check fails"
          description: 'Check host: "{{ $labels.instance }}" and find appropriate servers, which serving it to fix the problem.'
          grafana: "{{ GRAFANA_HTTP_STATUS_DASHBOARD }}"
          access: "{{ WIKI_MONITORING_ACCESS }}"
          priority: "P5"


  - name: blackbox_exporter http checks ssl exiration
    rules:
      - alert: "Ssl will be expired in next 10 days"
        expr: (probe_ssl_earliest_cert_expiry{job!="blackbox-exporter kubernetes services"} - time())  / (3600 * 24) < 10
        annotations:
          summary: "Ssl will be expired in next 10 days"
          description: 'Renew certificate for host: "{{ $labels.instance }}" if it managed by us or ask customer to get new one and install it'
          grafana: "{{ GRAFANA_HTTP_SSL_EXPIRATION_DASHBOARD }}"
          access: "{{ WIKI_MONITORING_ACCESS }}"
          priority: "P5"


      - alert: "Ssl will be expired in next 2 days"
        expr: (probe_ssl_earliest_cert_expiry{job!="blackbox-exporter kubernetes services"} - time())  / (3600 * 24) < 2
        annotations:
          summary: "Ssl will be expired in next 2 days"
          description: 'Renew certificate for host: "{{ $labels.instance }}" if it managed by us or ask customer to get new one and install it'
          grafana: "{{ GRAFANA_HTTP_SSL_EXPIRATION_DASHBOARD }}"
          access: "{{ WIKI_MONITORING_ACCESS }}"
          priority: "P3"

