groups:
  - name: "record rules blackbox-exporter kubernetes"
    rules:
    - record: service:http_status:minimal
      expr: min(probe_success) by (server_env)


  - name: "http service alerts - blackbox-exporter kubernetes"
    rules:
      - alert: "kubernetes_exporter - service http check fails P1-2"
        expr: probe_success{job="blackbox-exporter kubernetes services",host_priority=~"P[1-2]"} != 1
        for: 2m
        annotations:
          summary: "service http check fails"
          description: 'Connect to cluster: "{{ $labels.cluster_name }}" in env: "{{ $labels.server_env }}" and check why request to: "http://{{ $labels.instance }}{{ $labels.request }}" fails for service: "{{ $labels.service_name_http }}"'
          grafana: "{{ GRAFANA_KUBERNETES_EXPORTER_HTTP_CHECK_DASHBOARD }}"
          access: "{{ WIKI_MONITORING_ACCESS }}"
          priority: "P2"

      - alert: "kubernetes_exporter - service http check fails P3"
        expr: probe_success{job="blackbox-exporter kubernetes services",host_priority="P3"} != 1
        for: 5m
        annotations:
          summary: "service http check fails"
          description: 'Connect to cluster: "{{ $labels.cluster_name }}" in env: "{{ $labels.server_env }}" and check why request to: "http://{{ $labels.instance }}{{ $labels.request }}" fails for service: "{{ $labels.service_name_http }}"'
          grafana: "{{ GRAFANA_KUBERNETES_EXPORTER_HTTP_CHECK_DASHBOARD }}"
          access: "{{ WIKI_MONITORING_ACCESS }}"
          priority: "P3"

      - alert: "kubernetes_exporter - service http check fails P4-5"
        expr: probe_success{job="blackbox-exporter kubernetes services",host_priority=~"P[4-5]|^$"} != 1
        for: 10m
        annotations:
          summary: "service http check fails"
          description: 'Connect to cluster: "{{ $labels.cluster_name }}" in env: "{{ $labels.server_env }}" and check why request to: "http://{{ $labels.instance }}{{ $labels.request }}" fails for service: "{{ $labels.service_name_http }}"'
          grafana: "{{ GRAFANA_KUBERNETES_EXPORTER_HTTP_CHECK_DASHBOARD }}"
          access: "{{ WIKI_MONITORING_ACCESS }}"
          priority: "P5"

