groups:
 #- name: "get number of cores"
 #  rules:
 #  - record: instance:node_cpus:count
 #    expr: count(node_cpu_seconds_total{mode="idle"}) without (cpu,mode)


  - name: "load alerts kubernetes"
    rules:
      - alert: "LA > 110% P4"
        expr: node_load1{host_priority=~"P[1-3]",job="node_exporter kubernetes"} > (instance:node_cpus:count + 1)
        for: 30m
        annotations:
          summary: "LA > 110%: {{ $value }}"
          description: 'Check why LA is to high on node: "{{ $labels.node_name }}" in cluster: "{{ $labels.cluster_name }}"'
          grafana: "{{ GRAFANA_KUBERNETES_NODE_EXPORTER_LA_DASHBOARD }}"
          access: "{{ WIKI_MONITORING_ACCESS }}"
          priority: "P3"

      - alert: "LA > 110% P4-5"
        expr: node_load1{host_priority=~"P[4-5]|^$",job="node_exporter kubernetes"} > (instance:node_cpus:count + 1)
        for: 60m
        annotations:
          summary: "LA > 110%: {{ $value }}"
          description: 'Check why LA is to high on node: "{{ $labels.node_name }}" in cluster: "{{ $labels.cluster_name }}"'
          grafana: "{{ GRAFANA_KUBERNETES_NODE_EXPORTER_LA_DASHBOARD }}"
          access: "{{ WIKI_MONITORING_ACCESS }}"
          priority: "P5"

