groups:
  - name: "monit type=program alerts"
    rules:
      - alert: "custom check failed P4-5"
        expr: node_monit{host_priority=~"P[4-5]",type="program",key="status",name!~"check_monit_collector_exception"} > 0
        for: 15m
        annotations:
          summary: 'custom check: "{{ $labels.name }}" failed'
          description: 'Go to instance: "{{ $labels.instance }}"; find more info in monit config (grep -r {{ $labels.name }} /etc/monit.d/); monit log: /var/log/monit_collector.log'
          grafana: "{{ GRAFANA_ALL_ALERTS_DASHBOARD }}"
          access: "{{ WIKI_MONITORING_ACCESS }}"
          priority: "P3"

      - alert: "custom check failed P1-3"
        expr: node_monit{host_priority=~"P[1-3]",type="program",key="status",name!~"check_monit_collector_exception"} > 0
        for: 5m
        annotations:
          summary: 'custom check: "{{ $labels.name }}" failed'
          description: 'Go to instance: "{{ $labels.instance }}"; find more info in monit config (grep -r {{ $labels.name }} /etc/monit.d/); monit log: /var/log/monit_collector.log'
          grafana: "{{ GRAFANA_ALL_ALERTS_DASHBOARD }}"
          access: "{{ WIKI_MONITORING_ACCESS }}"
          priority: "P2"

