groups:
  - name: monit alerts
    rules:
      - alert: "monit not running P5"
        expr: node_number_of_monit_processes{host_priority="P5"} != 1
        for: 12m
        annotations:
          summary: "monit not running"
          description: 'Go to host: "{{ $labels.hostname }}" and check if service "monit" is running'
          grafana: "{{ GRAFANA_MONIT_RUNNING_DASHBOARD }}"
          access: "{{ WIKI_MONITORING_ACCESS }}"
          priority: "P3"

      - alert: "monit not running P4"
        expr: node_number_of_monit_processes{host_priority="P5"} != 1
        for: 7m
        annotations:
          summary: "monit not running"
          description: 'Go to host: "{{ $labels.hostname }}" and check if service "monit" is running'
          grafana: "{{ GRAFANA_MONIT_RUNNING_DASHBOARD }}"
          access: "{{ WIKI_MONITORING_ACCESS }}"
          priority: "P3"

      - alert: "monit not running P3"
        expr: node_number_of_monit_processes{host_priority="P5"} != 1
        for: 5m
        annotations:
          summary: "monit not running"
          description: 'Go to host: "{{ $labels.hostname }}" and check if service "monit" is running'
          grafana: "{{ GRAFANA_MONIT_RUNNING_DASHBOARD }}"
          access: "{{ WIKI_MONITORING_ACCESS }}"
          priority: "P2"

      - alert: "monit not running P2"
        expr: node_number_of_monit_processes{host_priority="P5"} != 1
        for: 3m
        annotations:
          summary: "monit not running"
          description: 'Go to host: "{{ $labels.hostname }}" and check if service "monit" is running'
          grafana: "{{ GRAFANA_MONIT_RUNNING_DASHBOARD }}"
          access: "{{ WIKI_MONITORING_ACCESS }}"
          priority: "P2"

      - alert: "monit not running P1"
        expr: node_number_of_monit_processes{host_priority="P5"} != 1
        for: 2m
        annotations:
          summary: "monit not running"
          description: 'Go to host: "{{ $labels.hostname }}" and check if service "monit" is running'
          grafana: "{{ GRAFANA_MONIT_RUNNING_DASHBOARD }}"
          access: "{{ WIKI_MONITORING_ACCESS }}"
          priority: "P1"

