groups:
  - name: mail
    rules:
      - alert: "mail queue > 100 P4-5" 
        expr: node_mail_queue{host_priority=~"P[4-5]",mail_list!="true"} > 100
        for: 10m
        annotations:
          summary: "mail queue > 100"
          description: "Check why mail queue so big on host: {{ $labels.hostname }}, check it via /usr/bin/mailq_custom.sh or /usr/bin/mailq"
          grafana: "{{ GRAFANA_MONIT_CHECK_STATUS_DASHBOARD }}"
          access: "{{ WIKI_MONITORING_ACCESS }}"
          priority: "P5"

      - alert: "mail queue > 4000 P4-5" 
        expr: node_mail_queue{host_priority=~"P[4-5]",mail_list="true"} > 4000
        for: 1d
        annotations:
          summary: "mail queue > 4000"
          description: "Check why mail queue so big on host: {{ $labels.hostname }}, check it via /usr/bin/mailq_custom.sh or /usr/bin/mailq"
          grafana: "{{ GRAFANA_MONIT_CHECK_STATUS_DASHBOARD }}"
          access: "{{ WIKI_MONITORING_ACCESS }}"
          priority: "P5"


      - alert: "mail queue > 100 P1-3" 
        expr: node_mail_queue{host_priority=~"P[1-3]",mail_list!="true"} > 100
        for: 10m
        annotations:
          summary: "mail queue > 100"
          description: "Check why mail queue so big on host: {{ $labels.hostname }}, check it via /usr/bin/mailq_custom.sh or /usr/bin/mailq"
          grafana: "{{ GRAFANA_MONIT_CHECK_STATUS_DASHBOARD }}"
          access: "{{ WIKI_MONITORING_ACCESS }}"
          priority: "P3"

      - alert: "mail queue > 4000 P1-3" 
        expr: node_mail_queue{host_priority=~"P[1-3]",mail_list="true"} > 4000
        for: 1d
        annotations:
          summary: "mail queue > 4000"
          description: "Check why mail queue so big on host: {{ $labels.hostname }}, check it via /usr/bin/mailq_custom.sh or /usr/bin/mailq"
          grafana: "{{ GRAFANA_MONIT_CHECK_STATUS_DASHBOARD }}"
          access: "{{ WIKI_MONITORING_ACCESS }}"
          priority: "P3"

