groups:
  - name: "nginx_exporter down alerts"
    rules:
      - alert: "nginx_exporter down P5"
        expr: up{host_priority="P5",instance=~".*:9113"} == 0
        for: 10m
        annotations:
          summary: "nginx_exporter down"
          description: 'Go to instance: "{{ $labels.instance }}" and check if service: "nginx_exporter" is running'
          grafana: "{{ GRAFANA_NGINX_EXPORTER_UP_DASHBOARD }}"
          access: "{{ WIKI_MONITORING_ACCESS }}"
          priority: "P3"

      - alert: "nginx_exporter down P4"
        expr: up{host_priority="P4",instance=~".*:9113"} == 0
        for: 5m
        annotations:
          summary: "nginx_exporter down"
          description: 'Go to instance: "{{ $labels.instance }}" and check if service: "nginx_exporter" is running'
          grafana: "{{ GRAFANA_NGINX_EXPORTER_UP_DASHBOARD }}"
          access: "{{ WIKI_MONITORING_ACCESS }}"
          priority: "P3"

      - alert: "nginx_exporter down P3"
        expr: up{host_priority=~"P3|^$",instance=~".*:9113"} == 0
        for: 4m
        annotations:
          summary: "nginx_exporter down"
          description: 'Go to instance: "{{ $labels.instance }}" and check if service: "nginx_exporter" is running'
          grafana: "{{ GRAFANA_NGINX_EXPORTER_UP_DASHBOARD }}"
          access: "{{ WIKI_MONITORING_ACCESS }}"
          priority: "P3"

      - alert: "nginx_exporter down P2"
        expr: up{host_priority="P2",instance=~".*:9113"} == 0
        for: 3m
        annotations:
          summary: "nginx_exporter down"
          description: 'Go to instance: "{{ $labels.instance }}" and check if service: "nginx_exporter" is running'
          grafana: "{{ GRAFANA_NGINX_EXPORTER_UP_DASHBOARD }}"
          access: "{{ WIKI_MONITORING_ACCESS }}"
          priority: "P2"

      - alert: "nginx_exporter down P1"
        expr: up{host_priority="P1",instance=~".*:9113"} == 0
        for: 2m
        annotations:
          summary: "nginx_exporter down"
          description: 'Go to instance: "{{ $labels.instance }}" and check if service: "nginx_exporter" is running'
          grafana: "{{ GRAFANA_NGINX_EXPORTER_UP_DASHBOARD }}"
          access: "{{ WIKI_MONITORING_ACCESS }}"
          priority: "P1"


  - name: "parse errors - nginx_exporter"
    rules:
      - alert: "nginx_exporter has new errors P1-3"
        expr: nginx_up{host_priority=~"P[1-3]"} != 1
        for: 5m
        annotations:
          summary: "nginx_exporter has new errors"
          description: 'Go to instance: "{{ $labels.instance }}" and check log for redis_exporter'
          grafana: "{{ GRAFANA_NGINX_EXPORTER_SCRAPE_DASHBOARD }}"
          access: "{{ WIKI_MONITORING_ACCESS }}"
          priority: "P2"
        labels:
          team: monitoring

      - alert: "nginx_exporter has new errors P4-5"
        expr: nginx_up{host_priority=~"P[4-5]|^$"} != 1
        for: 15m
        annotations:
          summary: "nginx_exporter has new errors"
          description: 'Go to instance: "{{ $labels.instance }}" and check log for redis_exporter'
          grafana: "{{ GRAFANA_NGINX_EXPORTER_SCRAPE_DASHBOARD }}"
          access: "{{ WIKI_MONITORING_ACCESS }}"
          priority: "P3"
        labels:
          team: monitoring

