groups:
  - name: "postgres_exporter down alerts"
    rules:
      - alert: "postgres_exporter down P5"
        expr: up{host_priority="P5",instance=~".*:9187"} == 0
        for: 15m
        annotations:
          summary: "postgres_exporter down"
          description: 'Go to host: "{{ $labels.hostname }}" and check if service: "postgres_exporter" is running'
          grafana: "{{ GRAFANA_POSTGRES_EXPORTER_UP_DASHBOARD }}"
          access: "{{ WIKI_MONITORING_ACCESS }}"
          priority: "P5"

      - alert: "postgres_exporter down P4"
        expr: up{host_priority=~"P4|^$",instance=~".*:9187"} == 0
        for: 10m
        annotations:
          summary: "postgres_exporter down"
          description: 'Go to host: "{{ $labels.hostname }}" and check if service: "postgres_exporter" is running'
          grafana: "{{ GRAFANA_POSTGRES_EXPORTER_UP_DASHBOARD }}"
          access: "{{ WIKI_MONITORING_ACCESS }}"
          priority: "P4"

      - alert: "postgres_exporter down P3"
        expr: up{host_priority="P3",instance=~".*:9187"} == 0
        for: 5m
        annotations:
          summary: "postgres_exporter down"
          description: 'Go to host: "{{ $labels.hostname }}" and check if service: "postgres_exporter" is running'
          grafana: "{{ GRAFANA_POSTGRES_EXPORTER_UP_DASHBOARD }}"
          access: "{{ WIKI_MONITORING_ACCESS }}"
          priority: "P2"

      - alert: "postgres_exporter down P2"
        expr: up{host_priority="P2",instance=~".*:9187"} == 0
        for: 3m
        annotations:
          summary: "postgres_exporter down"
          description: 'Go to host: "{{ $labels.hostname }}" and check if service: "postgres_exporter" is running'
          grafana: "{{ GRAFANA_POSTGRES_EXPORTER_UP_DASHBOARD }}"
          access: "{{ WIKI_MONITORING_ACCESS }}"
          priority: "P2"

      - alert: "postgres_exporter down P1"
        expr: up{host_priority="P1",instance=~".*:9187"} == 0
        for: 2m
        annotations:
          summary: "postgres_exporter down"
          description: 'Go to host: "{{ $labels.hostname }}" and check if service: "postgres_exporter" is running'
          grafana: "{{ GRAFANA_POSTGRES_EXPORTER_UP_DASHBOARD }}"
          access: "{{ WIKI_MONITORING_ACCESS }}"
          priority: "P1"


  - name: "db connection errors - postgres_exporter"
    rules:
      - alert: "postgres_exporter has db connection errors P1-3"
        expr: pg_up{host_priority=~"P[1-3]"} != 1
        for: 5m
        annotations:
          summary: "postgres_exporter has new errors"
          description: 'Go to host: "{{ $labels.hostname }}" and check log for postgres_exporter'
          grafana: "{{ GRAFANA_POSTGRES_EXPORTER_CONNECT_DASHBOARD }}"
          access: "{{ WIKI_MONITORING_ACCESS }}"
          priority: "P2"

      - alert: "postgres_exporter has db connection errors P4-5"
        expr: pg_up{host_priority=~"P[4-5]|^$"} != 1
        for: 10m
        annotations:
          summary: "postgres_exporter has new errors"
          description: 'Go to host: "{{ $labels.hostname }}" and check log for postgres_exporter'
          grafana: "{{ GRAFANA_POSTGRES_EXPORTER_CONNECT_DASHBOARD }}"
          access: "{{ WIKI_MONITORING_ACCESS }}"
          priority: "P5"


  - name: "parse errors - postgres_exporter"
    rules:
      - alert: "postgres_exporter has new errors P1-3"
        expr: pg_exporter_last_scrape_error{host_priority=~"P[1-3]"} != 0
        for: 5m
        annotations:
          summary: "postgres_exporter has new errors"
          description: 'Go to host: "{{ $labels.hostname }}" and check log for postgres_exporter'
          grafana: "{{ GRAFANA_POSTGRES_EXPORTER_SCRAPE_DASHBOARD }}"
          access: "{{ WIKI_MONITORING_ACCESS }}"
          priority: "P2"

      - alert: "postgres_exporter has new errors P4-5"
        expr: pg_exporter_last_scrape_error{host_priority=~"P[4-5]|^$"} != 0
        for: 10m
        annotations:
          summary: "postgres_exporter has new errors"
          description: 'Go to host: "{{ $labels.hostname }}" and check log for postgres_exporter'
          grafana: "{{ GRAFANA_POSTGRES_EXPORTER_SCRAPE_DASHBOARD }}"
          access: "{{ WIKI_MONITORING_ACCESS }}"
          priority: "P5"


  - name: "used connections errors - postgres_exporter"
    rules:
      - alert: "postgres used connections > 80% P1-3"
        expr: sum(pg_stat_activity_count{host_priority=~"P[1-3]"}) by (server_env,project,hostname) / max(pg_settings_max_connections) by (server_env,project,hostname) * 100 > 80
        annotations:
          summary: "postgres used connections > 80%"
          description: 'Go to host: "{{ $labels.hostname }}" and increase postgresql connections limit or check why to many connections in use'
          grafana: "{{ GRAFANA_POSTGRES_EXPORTER_CONNECTIONS_DASHBOARD }}"
          access: "{{ WIKI_MONITORING_ACCESS }}"
          priority: "P3"

      - alert: "postgres used connections > 80% P4-5"
        expr: sum(pg_stat_activity_count{host_priority=~"P[4-5]|^$"}) by (server_env,project,hostname) / max(pg_settings_max_connections) by (server_env,project,hostname) * 100 > 80
        for: 5m
        annotations:
          summary: "postgres used connections > 80%"
          description: 'Go to host: "{{ $labels.hostname }}" and increase postgresql connections limit or check to many connections in use'
          grafana: "{{ GRAFANA_POSTGRES_EXPORTER_CONNECTIONS_DASHBOARD }}"
          access: "{{ WIKI_MONITORING_ACCESS }}"
          priority: "P5"

