groups:
  - name: "prometheus exporter alerts"
    rules:
      - alert: "prometheus exporter has new errors (config reload)"
        expr: prometheus_config_last_reload_successful != 1
        for: 10m
        annotations:
          summary: "prometheus config reload fails"
          description: 'Go to host: "{{ $labels.hostname }}" and check why instance: "{{ $labels.instance }}" cannot reload config'
          grafana: "{{ GRAFANA_ALL_ALERTS_DASHBOARD }}"
          access: "{{ WIKI_MONITORING_ACCESS }}"
          priority: "P3"
          team: "monitoring"

  - name: "prometheus federate alerts"
    rules:
      - alert: "prometheus federate down P4-5"
        expr: up{host_priority=~"P[4-5]",instance=~".*:443",job=~"prometheus_federate.*"} == 0
        for: 15m
        annotations:
          summary: "Exporter: {{ $labels.instance }} have new errors"
          description: "Go to monitoring instance and check log for Exporter: {{ $labels.instance }}"
          grafana: "{{ GRAFANA_ALL_ALERTS_DASHBOARD }}"
          access: "{{ WIKI_MONITORING_ACCESS }}"
          priority: "P5"

      - alert: "prometheus federate down P1-3"
        expr: up{host_priority=~"P[1-3]",instance=~".*:443",job=~"prometheus_federate.*"} == 0
        for: 5m
        annotations:
          summary: "Exporter: {{ $labels.instance }} have new errors"
          description: "Go to monitoring instance and check log for Exporter: {{ $labels.instance }}"
          grafana: "{{ GRAFANA_ALL_ALERTS_DASHBOARD }}"
          access: "{{ WIKI_MONITORING_ACCESS }}"
          priority: "P2"

