---
- name: Add stats collection for monit daemon itself
  template:
    src: "monit.d/monit.conf.j2"
    dest: "/etc/monit.d/monit.conf"
    mode: 0640
    owner: root
    group: root
  notify: check_config_and_reload

