groups:
  - name: "cloudwatch_exporter down alerts"
    rules:
      - alert: "cloudwatch_exporter down P5"
        expr: up{host_priority="P5",instance=~".*:9106"} == 0
        for: 10m
        annotations:
          summary: "cloudwatch_exporter down"
          description: 'Go to instance: "{{ $labels.instance }}" and check if service: "cloudwatch_exporter" is running'
          grafana: "{{ grafana_cloudwatch_exporter_dashboard }}"
          access: "{{ wiki_monitoring_access }}"
          priority: "P3"

      - alert: "cloudwatch_exporter down P4"
        expr: up{host_priority="P4",instance=~".*:9106"} == 0
        for: 5m
        annotations:
          summary: "cloudwatch_exporter down"
          description: 'Go to instance: "{{ $labels.instance }}" and check if service: "cloudwatch_exporter" is running'
          grafana: "{{ grafana_cloudwatch_exporter_dashboard }}"
          access: "{{ wiki_monitoring_access }}"
          priority: "P3"

      - alert: "cloudwatch_exporter down P3"
        expr: up{host_priority="P3",instance=~".*:9106"} == 0
        for: 4m
        annotations:
          summary: "cloudwatch_exporter down"
          description: 'Go to instance: "{{ $labels.instance }}" and check if service: "cloudwatch_exporter" is running'
          grafana: "{{ grafana_cloudwatch_exporter_dashboard }}"
          access: "{{ wiki_monitoring_access }}"
          priority: "P2"

      - alert: "cloudwatch_exporter down P2"
        expr: up{host_priority="P2",instance=~".*:9106"} == 0
        for: 3m
        annotations:
          summary: "cloudwatch_exporter down"
          description: 'Go to instance: "{{ $labels.instance }}" and check if service: "cloudwatch_exporter" is running'
          grafana: "{{ grafana_cloudwatch_exporter_dashboard }}"
          access: "{{ wiki_monitoring_access }}"
          priority: "P2"

      - alert: "cloudwatch_exporter down P1"
        expr: up{host_priority="P1",instance=~".*:9106"} == 0
        for: 2m
        annotations:
          summary: "cloudwatch_exporter down"
          description: 'Go to instance: "{{ $labels.instance }}" and check if service: "cloudwatch_exporter" is running'
          grafana: "{{ grafana_cloudwatch_exporter_dashboard }}"
          access: "{{ wiki_monitoring_access }}"
          priority: "P1"

      - alert: "cloudwatch_exporter down"
        expr: up{host_priority!~"P[1-5]",instance=~".*:9106"} == 0
        for: 4m
        annotations:
          summary: "cloudwatch_exporter down"
          description: 'Go to instance: "{{ $labels.instance }}" and check if service: "cloudwatch_exporter" is running'
          grafana: "{{ grafana_cloudwatch_exporter_dashboard }}"
          access: "{{ wiki_monitoring_access }}"
          priority: "P3"


  - name: "parse errors - cloudwatch_exporter"
    rules:
      - alert: "cloudwatch_exporter has new errors P1-3"
        expr: cloudwatch_exporter_scrape_error{host_priority=~"P[1-3]"} != 0
        for: 5m
        annotations:
          summary: "cloudwatch_exporter has new errors"
          description: 'Go to instance: "{{ $labels.instance }}" and check log for cloudwatch_exporter'
          grafana: "{{ grafana_cloudwatch_exporter_dashboard }}"
          access: "{{ wiki_monitoring_access }}"
          priority: "P2"

      - alert: "cloudwatch_exporter has new errors P4-5"
        expr: cloudwatch_exporter_scrape_error{host_priority=~"P[4-5]"} != 0
        for: 15m
        annotations:
          summary: "cloudwatch_exporter has new errors"
          description: 'Go to instance: "{{ $labels.instance }}" and check log for cloudwatch_exporter'
          grafana: "{{ grafana_cloudwatch_exporter_dashboard }}"
          access: "{{ wiki_monitoring_access }}"
          priority: "P3"

      - alert: "cloudwatch_exporter has new errors"
        expr: cloudwatch_exporter_scrape_error{host_priority!~"P[1-5]"} != 0
        for: 10m
        annotations:
          summary: "cloudwatch_exporter has new errors"
          description: 'Go to instance: "{{ $labels.instance }}" and check log for cloudwatch_exporter'
          grafana: "{{ grafana_cloudwatch_exporter_dashboard }}"
          access: "{{ wiki_monitoring_access }}"
          priority: "P3"

