groups:
  - name: http checks
    rules:
      - alert: "ssl will be expired in next 10 days"
        expr: node_monit{key="port_certificate_valid"} < 10
        for: 10m
        annotations:
          summary: "ssl will be expired in next 10 days"
          description: 'Renew certificate of domain: "{{ $labels.name }}" if it managed by us or ask customer to get new one and install it'
          grafana: "{{ grafana_monit_dashboard }}"
          access: "{{ wiki_monitoring_access }}"
          priority: "P5"

      - alert: "ssl will be expired in next 2 days"
        expr: node_monit{key="port_certificate_valid"} < 2
        for: 10m
        annotations:
          summary: "ssl will be expired in next 2 days"
          description: 'Renew certificate of domain: "{{ $labels.name }}" if it managed by us or ask customer to get new one and install it'
          grafana: "{{ grafana_monit_dashboard }}"
          access: "{{ wiki_monitoring_access }}"
          priority: "P3"


