groups:
  - name: "processes alerts"
    rules:
      - alert: "process not running P4-5"
        expr: node_monit{host_priority=~"P[4-5]",type="process",key="status",name!~".*exporter|monit|monit_collector"} > 0
        for: 15m
        annotations:
          summary: 'process: "{{ $labels.name }}" not running'
          description: 'Go to instance: "{{ $labels.instance }}"; find more info in monit config (grep -r {{ $labels.name }} /etc/monit.d/); monit log: /var/log/monit_collector.log'
          grafana: "{{ grafana_all_alerts_dashboard }}"
          access: "{{ wiki_monitoring_access }}"
          priority: "P3"

      - alert: "process not running P1-3"
        expr: node_monit{host_priority=~"P[1-3]",type="process",key="status",name!~".*exporter|monit|monit_collector"} > 0
        for: 5m
        annotations:
          summary: 'process: "{{ $labels.name }}" not running'
          description: 'Go to instance: "{{ $labels.instance }}"; find more info in monit config (grep -r {{ $labels.name }} /etc/monit.d/); monit log: /var/log/monit_collector.log'
          grafana: "{{ grafana_all_alerts_dashboard }}"
          access: "{{ wiki_monitoring_access }}"
          priority: "P2"

