groups:
  - name: "prometheus exporter alerts"
    rules:
      - alert: "prometheus exporter have new errors"
        expr: up{instance=~".*:9090"} == 0
        for: 10m
        annotations:
          summary: "Exporter: {{ $labels.instance }} have new errors"
          description: "Go to monitoring instance and check log for Exporter: {{ $labels.instance }}"
          grafana: "{{ grafana_all_alerts_dashboard }}"
          access: "{{ wiki_monitoring_access }}"
          priority: "P3"

