groups:
  - name: "prometheus exporter alerts"
    rules:
      - alert: "prometheus exporter has new errors"
        expr: up{instance=~".*:9090"} == 0
        for: 10m
        annotations:
          summary: "Exporter: {{ $labels.instance }} has new errors"
          description: "Go to monitoring instance and check log for Exporter: {{ $labels.instance }}"
          grafana: "{{ grafana_all_alerts_dashboard }}"
          access: "{{ wiki_monitoring_access }}"
          priority: "P3"

groups:
  - name: "host down alerts - node_exporter"
    rules:
      - alert: "host down P5"
        expr: up{host_priority="P5",instance=~".*:9100"} == 0
        for: 30m
        annotations:
          summary: "host down"
          description: 'Go to host: "{{ $labels.hostname }}" and check if service "node_exporter" is running'
          grafana: "{{ GRAFANA_NODE_EXPORTER_ALERTS_DASHBOARD }}"
          access: "{{ WIKI_MONITORING_ACCESS }}"
          priority: "P3"

      - alert: "host down P4"
        expr: up{host_priority="P4",instance=~".*:9100"} == 0
        for: 20m
        annotations:
          summary: "host down"
          description: 'Go to host: "{{ $labels.hostname }}" and check if service "node_exporter" is running'
          grafana: "{{ GRAFANA_NODE_EXPORTER_ALERTS_DASHBOARD }}"
          access: "{{ WIKI_MONITORING_ACCESS }}"
          priority: "P3"

      - alert: "host down P3"
        expr: up{host_priority=~"P3|^$",instance=~".*:9100"} == 0
        for: 10m
        annotations:
          summary: "host down"
          description: 'Go to host: "{{ $labels.hostname }}" and check if service "node_exporter" is running'
          grafana: "{{ GRAFANA_NODE_EXPORTER_ALERTS_DASHBOARD }}"
          access: "{{ WIKI_MONITORING_ACCESS }}"
          priority: "P2"

      - alert: "host down P2"
        expr: up{host_priority="P2",instance=~".*:9100"} == 0
        for: 5m
        annotations:
          summary: "host down"
          description: 'Go to host: "{{ $labels.hostname }}" and check if service "node_exporter" is running'
          grafana: "{{ GRAFANA_NODE_EXPORTER_ALERTS_DASHBOARD }}"
          access: "{{ WIKI_MONITORING_ACCESS }}"
          priority: "P2"

      - alert: "host down P1"
        expr: up{host_priority="P1",instance=~".*:9100"} == 0
        for: 1m
        annotations:
          summary: "host down"
          description: 'Go to host: "{{ $labels.hostname }}" and check if service "node_exporter" is running'
          grafana: "{{ GRAFANA_NODE_EXPORTER_ALERTS_DASHBOARD }}"
          access: "{{ WIKI_MONITORING_ACCESS }}"
          priority: "P1"


  - name: "parse errors - node_exporter"
    rules:
      - alert: "node_exporter exporter has new errors P1-3"
        expr: node_scrape_collector_success{host_priority=~"P[1-3]"} != 1
        for: 5m
        annotations:
          summary: "node_exporter has new errors for some collectors"
          description: 'Go to host: "{{ $labels.hostname }}" and check log for node_exporter'
          grafana: "{{ GRAFANA_NODE_EXPORTER_ALERTS_DASHBOARD }}"
          access: "{{ WIKI_MONITORING_ACCESS }}"
          priority: "P2"

      - alert: "node_exporter exporter has new errors P4-5"
        expr: node_scrape_collector_success{host_priority=~"P[4-5]"} != 1
        for: 15m
        annotations:
          summary: "node_exporter has new errors for some collectors"
          description: 'Go to host: "{{ $labels.hostname }}" and check log for node_exporter'
          grafana: "{{ GRAFANA_NODE_EXPORTER_ALERTS_DASHBOARD }}"
          access: "{{ WIKI_MONITORING_ACCESS }}"
          priority: "P3"

      - alert: "node_exporter exporter has new errors"
        expr: node_scrape_collector_success{host_priority!~"P[1-5]"} != 1
        for: 10m
        annotations:
          summary: "node_exporter has new errors for some collectors"
          description: 'Go to host: "{{ $labels.hostname }}" and check log for node_exporter'
          grafana: "{{ GRAFANA_NODE_EXPORTER_ALERTS_DASHBOARD }}"
          access: "{{ WIKI_MONITORING_ACCESS }}"
          priority: "P3"


  - name: "parse errors - node_exporter text file"
    rules:
      - alert: "text file for node_exporter exporter has new errors P1-3"
        expr: node_textfile_scrape_error{host_priority=~"P[1-3]"} != 0
        for: 5m
        annotations:
          summary: "text file for node_exporter has new errors"
          description: 'Go to host: "{{ $labels.hostname }}" and check log for node_exporter'
          grafana: "{{ GRAFANA_NODE_EXPORTER_ALERTS_DASHBOARD }}"
          access: "{{ WIKI_MONITORING_ACCESS }}"
          priority: "P2"

      - alert: "text file for node_exporter exporter has new errors P4-5"
        expr: node_textfile_scrape_error{host_priority=~"P[4-5]"} != 0
        for: 15m
        annotations:
          summary: "text file for node_exporter has new errors"
          description: 'Go to host: "{{ $labels.hostname }}" and check log for node_exporter'
          grafana: "{{ GRAFANA_NODE_EXPORTER_ALERTS_DASHBOARD }}"
          access: "{{ WIKI_MONITORING_ACCESS }}"
          priority: "P3"

      - alert: "text file for node_exporter exporter has new errors"
        expr: node_textfile_scrape_error{host_priority!~"P[1-5]"} != 0
        for: 10m
        annotations:
          summary: "text file for node_exporter has new errors"
          description: 'Go to host: "{{ $labels.hostname }}" and check log for node_exporter'
          grafana: "{{ GRAFANA_NODE_EXPORTER_ALERTS_DASHBOARD }}"
          access: "{{ WIKI_MONITORING_ACCESS }}"
          priority: "P3"

