groups:
  - name: "prometheus exporter alerts"
    rules:
      - alert: "prometheus exporter has new errors (config reload)"
        expr: prometheus_config_last_reload_successful != 1
        for: 10m
        annotations:
          summary: "prometheus config reload fails"
          description: 'Go to host: "{{ $labels.hostname }}" and check why instance: "{{ $labels.instance }}" cannot reload config'
          grafana: "{{ GRAFANA_ALL_ALERTS_DASHBOARD }}"
          access: "{{ WIKI_MONITORING_ACCESS }}"
          priority: "P3"
          team: "monitoring"

