{
 "title": "All projects fails",
 "description": "Show monit stats as collector host",
 "tags": [
  "monit",
  "prometheus"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "precision",
    "query": "1s,10s,1m,5m,15m,30m,1h,3h,6h,12h,24h"
   },
   { "name": "instance", "query": "label_values(up, instance)" },
   { "name": "priority", "query": "P1,P2,P3,P4,P5" },
   {
    "name": "limit",
    "query": "1,2,3,4,5,6,7,8,9,10,15,30,60,100,99999999"
   }
  ]
 },
 "panels": [
  { "title": "Host down", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Host down alerts (top $limit)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk($limit, avg_over_time(ALERTS{alertname=~\"host down .*\",host_priority=~\"$priority\",alertstate=\"firing\",instance=~\"$instance\"}[$precision]))",
     "legendFormat": "{{host_priority}} + {{instance}}"
    }
   ]
  },
  { "title": "Exporter down", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "Exporter down alerts (top $limit)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk($limit, avg_over_time(ALERTS{alertname=~\"[a-z]+ exporter down .*\",alertstate=\"firing\",instance=~\"$instance\",host_priority=~\"$priority\"}[$precision]))",
     "legendFormat": "{{host_priority}} + {{alertname}} + {{instance}}"
    }
   ]
  },
  { "title": "Services", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "Services all alerts top($limit)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk($limit, avg_over_time(ALERTS{alertname!~\"host down .*\",alertstate=\"firing\",instance=~\"$instance\",host_priority=~\"$priority\"}[$precision]))",
     "legendFormat": "{{alertname}} + {{instance}}"
    }
   ]
  },
  {
   "title": "Monit status per service",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 },
   "collapsed": true,
   "panels": [
    {
     "title": "Monit status per service (top $limit)",
     "type": "graph",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 22 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "topk($limit, avg_over_time(node_monit{key=\"status\",host_priority=~\"$priority\",instance=~\"$instance\"}[$precision]))",
       "legendFormat": "{{instance}} + {{type}} + {{name}}"
      }
     ]
    }
   ]
  }
 ]
}