{
 "title": "All projects fails",
 "description": "Show monit stats as collector host",
 "tags": [
  "monit",
  "prometheus"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "job",
    "label": "Job",
    "query": "label_values(node_monit{service=\"system\",key=\"status\"}, job)"
   }
  ]
 },
 "panels": [
  {
   "title": "Host down alerts",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "ALERTS{alertname=\"host down P1\",alertstate=\"firing\"}",
     "legendFormat": "P1 {{instance}}"
    },
    {
     "expr": "ALERTS{alertname=\"host down P2\",alertstate=\"firing\"}",
     "legendFormat": "P2 {{instance}}"
    },
    {
     "expr": "ALERTS{alertname=\"host down P3\",alertstate=\"firing\"}",
     "legendFormat": "P3 {{instance}}"
    },
    {
     "expr": "ALERTS{alertname=\"host down P4\",alertstate=\"firing\"}",
     "legendFormat": "P4 {{instance}}"
    },
    {
     "expr": "ALERTS{alertname=\"host down P5\",alertstate=\"firing\"}",
     "legendFormat": "P5 {{instance}}"
    }
   ]
  },
  {
   "title": "Exporter down alerts",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "ALERTS{alertname=~\"[a-z]+ exporter down P1\",alertstate=\"firing\"}",
     "legendFormat": "P1 {{instance}}"
    },
    {
     "expr": "ALERTS{alertname=~\"[a-z]+ exporter down P2\",alertstate=\"firing\"}",
     "legendFormat": "P2 {{instance}}"
    },
    {
     "expr": "ALERTS{alertname=~\"[a-z]+ exporter down P3\",alertstate=\"firing\"}",
     "legendFormat": "P3 {{instance}}"
    },
    {
     "expr": "ALERTS{alertname=~\"[a-z]+ exporter down P4\",alertstate=\"firing\"}",
     "legendFormat": "P4 {{instance}}"
    },
    {
     "expr": "ALERTS{alertname=~\"[a-z]+ exporter down P5\",alertstate=\"firing\"}",
     "legendFormat": "P5 {{instance}}"
    }
   ]
  },
  {
   "title": "Services all alerts",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "ALERTS{alertname!~\"host down P[1-5]\",alertstate=\"firing\"}",
     "legendFormat": "{{name}} @ {{alertname}} @ {{instance}} "
    }
   ]
  },
  {
   "title": "Monit status per service",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_monit{key=\"status\"} > 0",
     "legendFormat": "{{instance}} @ {{type}} @ {{name}}"
    }
   ]
  }
 ]
}