{
 "title": "Cloudwatch RDS Copy(Prometheus)",
 "description": "Visualize OS metrics for Amazon RDS instance",
 "tags": [
  "cloudwatch",
  "db"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "env",
    "label": "Environment",
    "query": "label_values(aws_rds_cpuutilization_average, server_env)"
   },
   {
    "name": "region",
    "label": "Region",
    "query": "label_values(aws_rds_cpuutilization_average, region)"
   },
   {
    "name": "db_instance",
    "label": "DB Instance",
    "query": "label_values(aws_rds_cpuutilization_average{server_env=~\"$env\",region=~\"$region\"}, dbinstance_identifier)"
   }
  ]
 },
 "panels": [
  {
   "title": "CPU : $db_instance",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "repeat": "instance",
   "collapsed": true,
   "panels": [
    {
     "title": "CPU Utilization : $db_instance",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 1 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "alias": "CPU",
       "dimensions": { "DBInstanceIdentifier": "$instance" },
       "expr": "aws_rds_cpuutilization_average{server_env=~\"$env\",region=~\"$region\",dbinstance_identifier=~\"$db_instance\"}",
       "legendFormat": "{{ dbinstance_identifier }}",
       "metricName": "CPUUtilization",
       "namespace": "AWS/RDS",
       "period": "60",
       "region": "$region",
       "statistics": [ "Average" ]
      }
     ]
    },
    {
     "title": "CPU Credit Usage : $db_instance",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 1 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "alias": "Credits Accumulated",
       "dimensions": { "DBInstanceIdentifier": "$instance" },
       "expr": "aws_rds_cpucredit_usage_average{server_env=~\"$env\",region=~\"$region\",dbinstance_identifier=~\"$db_instance\"}",
       "legendFormat": "{{ dbinstance_identifier }}",
       "metricName": "CPUCreditBalance",
       "namespace": "AWS/RDS",
       "period": "300",
       "region": "$region",
       "statistics": [ "Average" ]
      }
     ]
    }
   ]
  },
  {
   "title": "Disk  : $db_instance",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "repeat": "instance",
   "collapsed": true,
   "panels": [
    {
     "title": "Disk Operations : $db_instance",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 2 },
     "yaxes": [
      { "format": "iops" }
     ],
     "targets": [
      {
       "alias": "Read",
       "dimensions": { "DBInstanceIdentifier": "$instance" },
       "expr": "aws_rds_write_iops_average{server_env=~\"$env\",region=~\"$region\",dbinstance_identifier=~\"$db_instance\"}",
       "legendFormat": "{{ dbinstance_identifier }} Write",
       "metricName": "ReadIOPS",
       "namespace": "AWS/RDS",
       "period": "60",
       "region": "$region",
       "statistics": [ "Average" ]
      },
      {
       "expr": "aws_rds_read_iops_average{server_env=~\"$env\",region=~\"$region\",dbinstance_identifier=~\"$db_instance\"}",
       "legendFormat": "{{ dbinstance_identifier }} Read"
      }
     ]
    },
    {
     "title": "Disk Latency : $db_instance",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 2 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "alias": "Read",
       "dimensions": { "DBInstanceIdentifier": "$instance" },
       "expr": "aws_rds_write_iops_average{server_env=~\"$env\",region=~\"$region\",dbinstance_identifier=~\"$db_instance\"}",
       "legendFormat": "{{ dbinstance_identifier }} Write",
       "metricName": "ReadLatency",
       "namespace": "AWS/RDS",
       "period": "60",
       "region": "$region",
       "statistics": [ "Average" ]
      },
      {
       "expr": "aws_rds_read_iops_average{server_env=~\"$env\",region=~\"$region\",dbinstance_identifier=~\"$db_instance\"}",
       "legendFormat": "{{ dbinstance_identifier }} Read"
      }
     ]
    },
    {
     "title": "Disk Queue Depth : $db_instance",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 9 },
     "repeat": "instance",
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "alias": "Outstanding IO Requests",
       "dimensions": { "DBInstanceIdentifier": "$instance" },
       "expr": "aws_rds_disk_queue_depth_average{server_env=~\"$env\",region=~\"$region\",dbinstance_identifier=~\"$db_instance\"}",
       "legendFormat": "{{ dbinstance_identifier }}",
       "metricName": "DiskQueueDepth",
       "namespace": "AWS/RDS",
       "period": "60",
       "region": "$region",
       "statistics": [ "Average" ]
      }
     ]
    },
    {
     "title": "Disk Throughput : $db_instance",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 9 },
     "repeat": "instance",
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "alias": "Read",
       "dimensions": { "DBInstanceIdentifier": "$instance" },
       "expr": "aws_rds_network_transmit_throughput_average{server_env=~\"$env\",region=~\"$region\",dbinstance_identifier=~\"$db_instance\"}",
       "legendFormat": "{{ dbinstance_identifier }} Transmit",
       "metricName": "ReadThroughput",
       "namespace": "AWS/RDS",
       "period": "60",
       "region": "$region",
       "statistics": [ "Average" ]
      },
      {
       "alias": "Write",
       "dimensions": { "DBInstanceIdentifier": "$instance" },
       "expr": "aws_rds_network_receive_throughput_average{server_env=~\"$env\",region=~\"$region\",dbinstance_identifier=~\"$db_instance\"}",
       "legendFormat": "{{ dbinstance_identifier }} Receive",
       "metricName": "WriteThroughput",
       "namespace": "AWS/RDS",
       "period": "60",
       "region": "$region",
       "statistics": [ "Average" ]
      }
     ]
    },
    {
     "title": "Free Storage Space : $db_instance",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 16 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "alias": "Available",
       "dimensions": { "DBInstanceIdentifier": "$instance" },
       "expr": "aws_rds_free_storage_space_average{server_env=~\"$env\",region=~\"$region\",dbinstance_identifier=~\"$db_instance\"}",
       "legendFormat": "{{ dbinstance_identifier }}",
       "metricName": "FreeStorageSpace",
       "namespace": "AWS/RDS",
       "period": "60",
       "region": "$region",
       "statistics": [ "Average" ]
      }
     ]
    }
   ]
  },
  {
   "title": "Memory : $db_instance",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "repeat": "instance",
   "collapsed": true,
   "panels": [
    {
     "title": "Memory : $db_instance",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 24 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "alias": "Available",
       "dimensions": { "DBInstanceIdentifier": "$instance" },
       "expr": "aws_rds_freeable_memory_average{server_env=~\"$env\",region=~\"$region\",dbinstance_identifier=~\"$db_instance\"}",
       "legendFormat": "{{ dbinstance_identifier }}",
       "metricName": "FreeableMemory",
       "namespace": "AWS/RDS",
       "period": "60",
       "region": "$region",
       "statistics": [ "Average" ]
      }
     ]
    }
   ]
  },
  {
   "title": "Swap & Network : $db_instance",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "repeat": "instance",
   "collapsed": true,
   "panels": [
    {
     "title": "Swap Usage : $db_instance",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 18 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "alias": "Used",
       "dimensions": { "DBInstanceIdentifier": "$instance" },
       "expr": "aws_rds_swap_usage_average{server_env=~\"$env\",region=~\"$region\",dbinstance_identifier=~\"$db_instance\"}",
       "legendFormat": "{{ dbinstance_identifier }}",
       "metricName": "SwapUsage",
       "namespace": "AWS/RDS",
       "period": "60",
       "region": "$region",
       "statistics": [ "Average" ]
      }
     ]
    },
    {
     "title": "Network Traffic : $db_instance",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 18 },
     "repeat": "instance",
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "alias": "Inbound",
       "dimensions": { "DBInstanceIdentifier": "$instance" },
       "expr": "aws_rds_network_transmit_throughput_average{server_env=~\"$env\",region=~\"$region\",dbinstance_identifier=~\"$db_instance\"}",
       "legendFormat": "{{ dbinstance_identifier }} Transmit",
       "metricName": "NetworkReceiveThroughput",
       "namespace": "AWS/RDS",
       "period": "60",
       "region": "$region",
       "statistics": [ "Average" ]
      },
      {
       "alias": "Outbound",
       "dimensions": { "DBInstanceIdentifier": "$instance" },
       "expr": "aws_rds_network_receive_throughput_average{server_env=~\"$env\",region=~\"$region\",dbinstance_identifier=~\"$db_instance\"}",
       "legendFormat": "{{ dbinstance_identifier }} Receive",
       "metricName": "NetworkTransmitThroughput",
       "namespace": "AWS/RDS",
       "period": "60",
       "region": "$region",
       "statistics": [ "Average" ]
      }
     ]
    }
   ]
  },
  {
   "title": "Replication",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "title": "Replication status",
     "type": "graph",
     "description": "0 = not active\n1 = active",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 5 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "pg_replication_status{server_env=~\"$env\",region=~\"$region\"}",
       "legendFormat": "{{ db_host }} - {{ slot_name }}"
      }
     ]
    },
    {
     "title": "Replication lag",
     "type": "graph",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 11 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "pg_replication_lag_bytes{server_env=~\"$env\",region=~\"$region\"}",
       "legendFormat": "{{ db_host }} - {{ slot_name }}"
      }
     ]
    }
   ]
  }
 ]
}