{
 "title": "Cloudwatch RDS",
 "description": "Visualize OS metrics for Amazon RDS instance",
 "tags": [
  "cloudwatch",
  "db",
  "mysql",
  "prometheus"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "env", "label": "Environment", "query": "label_values(up, server_env)" },
   {
    "name": "region",
    "label": "Region",
    "query": "label_values(aws_rds_cpuutilization_average, region)"
   },
   {
    "name": "db_instance",
    "label": "DB Instance",
    "query": "label_values(aws_rds_cpuutilization_average{server_env=~\"$env\",region=~\"$region\"}, dbinstance_identifier)"
   }
  ]
 },
 "panels": [
  {
   "title": "Status",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Exporter statuses",
     "type": "graph",
     "description": "Up is 1\nDown is 0",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 1 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "mysql_up{server_env=~\"$env\",region=~\"$region\",dbinstance_identifier=~\"$db_instance\"}",
       "legendFormat": "{{instance}} - Scrape status"
      },
      {
       "expr": "up{server_env=~\"$env\",region=~\"$region\",dbinstance_identifier=~\"$db_instance\",instance=~\".*:9104\"}",
       "legendFormat": "{{instance}} - Exporter status"
      },
      {
       "expr": "pg_up{server_env=~\"$env\",region=~\"$region\",dbinstance_identifier=~\"$db_instance\"}",
       "legendFormat": "{{instance}} - Scrape status"
      },
      {
       "expr": "up{server_env=~\"$env\",region=~\"$region\",dbinstance_identifier=~\"$db_instance\",instance=~\".*:9187\"}",
       "legendFormat": "{{instance}} - Exporter status"
      }
     ]
    }
   ]
  },
  {
   "title": "CPU",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "repeat": "instance",
   "collapsed": true,
   "panels": [
    {
     "title": "CPU Utilization : $db_instance",
     "type": "graph",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 9 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "alias": "CPU",
       "dimensions": { "DBInstanceIdentifier": "$instance" },
       "expr": "aws_rds_cpuutilization_average{server_env=~\"$env\",region=~\"$region\",dbinstance_identifier=~\"$db_instance\"}",
       "legendFormat": "{{ dbinstance_identifier }}",
       "metricName": "CPUUtilization",
       "namespace": "AWS/RDS",
       "period": "60",
       "region": "$region",
       "statistics": [ "Average" ]
      }
     ]
    },
    {
     "title": "CPU Credit Usage : $db_instance",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 15 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "alias": "Credits Accumulated",
       "dimensions": { "DBInstanceIdentifier": "$instance" },
       "expr": "aws_rds_cpucredit_usage_average{server_env=~\"$env\",region=~\"$region\",dbinstance_identifier=~\"$db_instance\"}",
       "legendFormat": "{{ dbinstance_identifier }}",
       "metricName": "CPUCreditBalance",
       "namespace": "AWS/RDS",
       "period": "300",
       "region": "$region",
       "statistics": [ "Average" ]
      }
     ]
    }
   ]
  },
  {
   "title": "Disk",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "repeat": "instance",
   "collapsed": true,
   "panels": [
    {
     "title": "Free Storage Space : $db_instance",
     "type": "graph",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 3 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "alias": "Available",
       "dimensions": { "DBInstanceIdentifier": "$instance" },
       "expr": "aws_rds_free_local_storage_average{server_env=~\"$env\",region=~\"$region\",dbinstance_identifier=~\"$db_instance\"}",
       "legendFormat": "{{ dbinstance_identifier }}",
       "metricName": "FreeStorageSpace",
       "namespace": "AWS/RDS",
       "period": "60",
       "region": "$region",
       "statistics": [ "Average" ]
      },
      {
       "alias": "Available",
       "dimensions": { "DBInstanceIdentifier": "$instance" },
       "expr": "aws_rds_free_storage_space_average{server_env=~\"$env\",region=~\"$region\",dbinstance_identifier=~\"$db_instance\"}",
       "legendFormat": "{{ dbinstance_identifier }}",
       "metricName": "FreeStorageSpace",
       "namespace": "AWS/RDS",
       "period": "60",
       "region": "$region",
       "statistics": [ "Average" ]
      }
     ]
    },
    {
     "title": "Disk Operations : $db_instance",
     "type": "graph",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 9 },
     "yaxes": [
      { "format": "iops" }
     ],
     "targets": [
      {
       "alias": "Read",
       "dimensions": { "DBInstanceIdentifier": "$instance" },
       "expr": "aws_rds_write_iops_average{server_env=~\"$env\",region=~\"$region\",dbinstance_identifier=~\"$db_instance\"}",
       "legendFormat": "{{ dbinstance_identifier }} Write",
       "metricName": "ReadIOPS",
       "namespace": "AWS/RDS",
       "period": "60",
       "region": "$region",
       "statistics": [ "Average" ]
      },
      {
       "expr": "aws_rds_read_iops_average{server_env=~\"$env\",region=~\"$region\",dbinstance_identifier=~\"$db_instance\"}",
       "legendFormat": "{{ dbinstance_identifier }} Read"
      }
     ]
    },
    {
     "title": "Disk Queue Depth : $db_instance",
     "type": "graph",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 15 },
     "repeat": "instance",
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "alias": "Outstanding IO Requests",
       "dimensions": { "DBInstanceIdentifier": "$instance" },
       "expr": "aws_rds_disk_queue_depth_average{server_env=~\"$env\",region=~\"$region\",dbinstance_identifier=~\"$db_instance\"}",
       "legendFormat": "{{ dbinstance_identifier }}",
       "metricName": "DiskQueueDepth",
       "namespace": "AWS/RDS",
       "period": "60",
       "region": "$region",
       "statistics": [ "Average" ]
      }
     ]
    },
    {
     "title": "Disk Latency : $db_instance",
     "type": "graph",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 21 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "alias": "Read",
       "dimensions": { "DBInstanceIdentifier": "$instance" },
       "expr": "aws_rds_write_iops_average{server_env=~\"$env\",region=~\"$region\",dbinstance_identifier=~\"$db_instance\"}",
       "legendFormat": "{{ dbinstance_identifier }} Write",
       "metricName": "ReadLatency",
       "namespace": "AWS/RDS",
       "period": "60",
       "region": "$region",
       "statistics": [ "Average" ]
      },
      {
       "expr": "aws_rds_read_iops_average{server_env=~\"$env\",region=~\"$region\",dbinstance_identifier=~\"$db_instance\"}",
       "legendFormat": "{{ dbinstance_identifier }} Read"
      }
     ]
    }
   ]
  },
  {
   "title": "Memory",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "repeat": "instance",
   "collapsed": true,
   "panels": [
    {
     "title": "Memory Free",
     "type": "graph",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 4 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "alias": "Available",
       "dimensions": { "DBInstanceIdentifier": "$instance" },
       "expr": "aws_rds_freeable_memory_average{server_env=~\"$env\",region=~\"$region\",dbinstance_identifier=~\"$db_instance\"}",
       "legendFormat": "{{ dbinstance_identifier }}",
       "metricName": "FreeableMemory",
       "namespace": "AWS/RDS",
       "period": "60",
       "region": "$region",
       "statistics": [ "Average" ]
      }
     ]
    },
    {
     "title": "Swap Usage : $db_instance",
     "type": "graph",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "alias": "Used",
       "dimensions": { "DBInstanceIdentifier": "$instance" },
       "expr": "aws_rds_swap_usage_average{server_env=~\"$env\",region=~\"$region\",dbinstance_identifier=~\"$db_instance\"}",
       "legendFormat": "{{ dbinstance_identifier }}",
       "metricName": "SwapUsage",
       "namespace": "AWS/RDS",
       "period": "60",
       "region": "$region",
       "statistics": [ "Average" ]
      }
     ]
    }
   ]
  },
  {
   "title": "Network",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "repeat": "instance",
   "collapsed": true,
   "panels": [
    {
     "title": "Network",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 5 },
     "repeat": "instance",
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "alias": "Inbound",
       "dimensions": { "DBInstanceIdentifier": "$instance" },
       "expr": "aws_rds_network_transmit_throughput_average{server_env=~\"$env\",region=~\"$region\",dbinstance_identifier=~\"$db_instance\"}",
       "legendFormat": "{{ dbinstance_identifier }} Transmit",
       "metricName": "NetworkReceiveThroughput",
       "namespace": "AWS/RDS",
       "period": "60",
       "region": "$region",
       "statistics": [ "Average" ]
      },
      {
       "alias": "Outbound",
       "dimensions": { "DBInstanceIdentifier": "$instance" },
       "expr": "aws_rds_network_receive_throughput_average{server_env=~\"$env\",region=~\"$region\",dbinstance_identifier=~\"$db_instance\"}",
       "legendFormat": "{{ dbinstance_identifier }} Receive",
       "metricName": "NetworkTransmitThroughput",
       "namespace": "AWS/RDS",
       "period": "60",
       "region": "$region",
       "statistics": [ "Average" ]
      }
     ]
    }
   ]
  },
  {
   "title": "Replication",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "collapsed": true,
   "panels": [
    {
     "title": "Replication lag",
     "type": "graph",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 19 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "aws_rds_aurora_replica_lag_average{server_env=~\"$env\",region=~\"$region\",dbinstance_identifier=~\"$db_instance\"}",
       "legendFormat": "{{ dbinstance_identifier }}"
      },
      {
       "expr": "aws_rds_replica_lag_average{server_env=~\"$env\",region=~\"$region\",dbinstance_identifier=~\"$db_instance\"}",
       "legendFormat": "{{ dbinstance_identifier }}"
      }
     ]
    }
   ]
  },
  { "title": "Engine", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "Database connections",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "aws_rds_database_connections_average{server_env=~\"$env\",region=~\"$region\",dbinstance_identifier=~\"$db_instance\"}",
     "legendFormat": "{{ dbinstance_identifier }}"
    }
   ]
  },
  {
   "title": "Database connections (%)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "(mysql_global_status_threads_connected{server_env=~\"$env\",dbinstance_identifier=~\"$db_instance\"} / mysql_global_variables_max_connections) * 100",
     "legendFormat": "{{ dbinstance_identifier }}"
    },
    {
     "expr": "(avg(aws_rds_database_connections_average{server_env=~\"$env\",region=~\"$region\",dbinstance_identifier=~\"$db_instance\"}) by (dbinstance_identifier, server_env, region) / avg(postgres_exporter_pg_settings_max_connections) by (dbinstance_identifier, server_env, region)) * 100",
     "legendFormat": "{{ dbinstance_identifier }}"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "aws_rds_engine_uptime_average{server_env=~\"$env\",region=~\"$region\",dbinstance_identifier=~\"$db_instance\"}",
     "legendFormat": "{{ dbinstance_identifier }}"
    }
   ]
  },
  {
   "title": "Queries",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 },
   "collapsed": true,
   "panels": [
    {
     "title": "Queries",
     "type": "graph",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 21 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "aws_rds_queries_average{server_env=~\"$env\",region=~\"$region\",dbinstance_identifier=~\"$db_instance\"}",
       "legendFormat": "{{ dbinstance_identifier }}"
      }
     ]
    },
    {
     "title": "Active Transactions",
     "type": "graph",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 27 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "aws_rds_active_transactions_average{server_env=~\"$env\",region=~\"$region\",dbinstance_identifier=~\"$db_instance\"}",
       "legendFormat": "{{ dbinstance_identifier }}"
      }
     ]
    },
    {
     "title": "Operations Throughput",
     "type": "graph",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 33 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "aws_rds_delete_throughput_average{server_env=~\"$env\",region=~\"$region\",dbinstance_identifier=~\"$db_instance\"}",
       "legendFormat": "{{ dbinstance_identifier }} - Delete"
      },
      {
       "expr": "aws_rds_insert_throughput_average{server_env=~\"$env\",region=~\"$region\",dbinstance_identifier=~\"$db_instance\"}",
       "legendFormat": "{{ dbinstance_identifier }} - Insert"
      },
      {
       "expr": "aws_rds_select_throughput_average{server_env=~\"$env\",region=~\"$region\",dbinstance_identifier=~\"$db_instance\"}",
       "legendFormat": "{{ dbinstance_identifier }} - Select"
      },
      {
       "expr": "aws_rds_update_throughput_average{server_env=~\"$env\",region=~\"$region\",dbinstance_identifier=~\"$db_instance\"}",
       "legendFormat": "{{ dbinstance_identifier }} - Update"
      }
     ]
    }
   ]
  }
 ]
}