{
 "title": "Containers metrics docker_exporter",
 "tags": [
  "prometheus",
  "docker"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "instance",
    "query": "label_values(up{instance=~\".*:9610\"},instance)"
   },
   { "name": "server_env", "query": "label_values(up,server_env)" },
   {
    "name": "limit",
    "query": "1,2,3,4,5,6,7,8,9,10,15,20,25,30,40,50,70,100,9999"
   },
   {
    "name": "container_name",
    "query": "label_values(docker_exporter_container_state{instance=\"$instance\"},container_name)"
   }
  ]
 },
 "panels": [
  { "title": "Containers status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Containers state (bottom $limit)",
   "type": "graph",
   "description": "Conainer state: {'running': 1, 'created': 0, 'exited': -1, 'restarting': -2, 'removing': -3, 'paused': -4, 'dead': -5}",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "bottomk($limit, docker_exporter_container_state{server_env=~\"$server_env\",instance=~\"$instance\",container_name=~\"$container_name\"})",
     "legendFormat": "{{container_name}}"
    }
   ]
  },
  {
   "title": "Containers data collection errors (top $limit)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk($limit, rate(docker_exporter_errors_total{server_env=~\"$server_env\",instance=~\"$instance\"}[5m]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Containers CPU",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU time total (top $limit)",
     "type": "graph",
     "description": "CPU time consumed in seconds",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 15 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "topk($limit, rate(docker_exporter_container_cpu_usage_total{server_env=~\"$server_env\",instance=~\"$instance\",container_name=~\"$container_name\"}[5m]))",
       "legendFormat": "{{container_name}}"
      }
     ]
    }
   ]
  },
  { "title": "Containers System", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "Uptime (bottom $limit)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "bottomk($limit, docker_exporter_container_uptime_seconds{server_env=~\"$server_env\",instance=~\"$instance\",container_name=~\"$container_name\"})",
     "legendFormat": "{{container_name}}"
    }
   ]
  },
  {
   "title": "Containers Memory",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 },
   "collapsed": true,
   "panels": [
    {
     "title": "Container memory usage (top $limit)",
     "type": "graph",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 17 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "topk($limit, docker_exporter_container_memory_usage_bytes{server_env=~\"$server_env\",instance=~\"$instance\",container_name=~\"$container_name\"})",
       "legendFormat": "{{container_name}}"
      }
     ]
    },
    {
     "title": "Container memory usage (top $limit)",
     "type": "graph",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 23 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "topk($limit, (docker_exporter_container_memory_usage_bytes{server_env=~\"$server_env\",instance=~\"$instance\",container_name=~\"$container_name\"} / docker_exporter_container_memory_limit_bytes) * 100)",
       "legendFormat": "{{container_name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Containers Network",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 },
   "collapsed": true,
   "panels": [
    {
     "title": "Network Receive / Transmit bytes (top $limit)",
     "type": "graph",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 18 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "topk($limit, rate(docker_exporter_container_network_rx_total_bytes{server_env=~\"$server_env\",instance=~\"$instance\",container_name=~\"$container_name\"}[5m]))",
       "legendFormat": "{{container_name}} - {{net_dev}} - Receive"
      },
      {
       "expr": "topk($limit, rate(docker_exporter_container_network_tx_total_bytes{server_env=~\"$server_env\",instance=~\"$instance\",container_name=~\"$container_name\"}[5m]))",
       "legendFormat": "{{container_name}} - {{net_dev}} - Transmit"
      }
     ]
    },
    {
     "title": "Network Receive / Transmit packets (top $limit)",
     "type": "graph",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 24 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "topk($limit, rate(docker_exporter_container_network_rx_packets_total{server_env=~\"$server_env\",instance=~\"$instance\",container_name=~\"$container_name\"}[5m]))",
       "legendFormat": "{{container_name}} - {{net_dev}} - Receive"
      },
      {
       "expr": "topk($limit, rate(docker_exporter_container_network_tx_packets_total{server_env=~\"$server_env\",instance=~\"$instance\",container_name=~\"$container_name\"}[5m]))",
       "legendFormat": "{{container_name}} - {{net_dev}} - Transmit"
      }
     ]
    },
    {
     "title": "Network Receive / Transmit errors (top $limit)",
     "type": "graph",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 30 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "topk($limit, rate(docker_exporter_container_network_rx_errors_total{server_env=~\"$server_env\",instance=~\"$instance\",container_name=~\"$container_name\"}[5m]))",
       "legendFormat": "{{container_name}} - {{net_dev}} - Receive"
      },
      {
       "expr": "topk($limit, rate(docker_exporter_container_network_tx_errors_total{server_env=~\"$server_env\",instance=~\"$instance\",container_name=~\"$container_name\"}[5m]))",
       "legendFormat": "{{container_name}} - {{net_dev}} - Transmit"
      }
     ]
    },
    {
     "title": "Network Receive / Transmit dropped packets (top $limit)",
     "type": "graph",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 36 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "topk($limit, rate(docker_exporter_container_network_rx_dropped_total{server_env=~\"$server_env\",instance=~\"$instance\",container_name=~\"$container_name\"}[5m]))",
       "legendFormat": "{{container_name}} - {{net_dev}} - Receive"
      },
      {
       "expr": "topk($limit, rate(docker_exporter_container_network_tx_dropped_total{server_env=~\"$server_env\",instance=~\"$instance\",container_name=~\"$container_name\"}[5m]))",
       "legendFormat": "{{container_name}} - {{net_dev}} - Transmit"
      }
     ]
    }
   ]
  },
  {
   "title": "Containers disk",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 },
   "collapsed": true,
   "panels": [
    {
     "title": "Disk Read / Write bytes (top $limit)",
     "type": "graph",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 19 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "topk($limit, rate(docker_exporter_container_io_service_bytes_recursive_write_bytes{server_env=~\"$server_env\",instance=~\"$instance\",container_name=~\"$container_name\"}[5m]))",
       "legendFormat": "{{container_name}} - Write"
      },
      {
       "expr": "topk($limit, rate(docker_exporter_container_io_service_bytes_recursive_read_bytes{server_env=~\"$server_env\",instance=~\"$instance\",container_name=~\"$container_name\"}[5m]))",
       "legendFormat": "{{container_name}} - Read"
      }
     ]
    },
    {
     "title": "Disk Read / Write operations (top $limit)",
     "type": "graph",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 25 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "topk($limit, rate(docker_exporter_container_io_serviced_recursive_write{server_env=~\"$server_env\",instance=~\"$instance\",container_name=~\"$container_name\"}[5m]))",
       "legendFormat": "{{container_name}} - Write"
      },
      {
       "expr": "topk($limit, rate(docker_exporter_container_io_serviced_recursive_read{server_env=~\"$server_env\",instance=~\"$instance\",container_name=~\"$container_name\"}[5m]))",
       "legendFormat": "{{container_name}} - Read"
      }
     ]
    }
   ]
  }
 ]
}