{
 "title": "EKS metrics",
 "tags": [
  "prometheus",
  "eks"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   { "name": "server_env", "query": "label_values(up,server_env)" },
   {
    "name": "namespace",
    "query": "label_values(container_cpu_system_seconds_total{server_env=~\".*$server_env.*\"},namespace)"
   },
   {
    "name": "asg",
    "query": "label_values(node_load1{server_env=~\".*$server_env.*\"},ASG)"
   },
   {
    "name": "pod_name",
    "query": "label_values(container_cpu_system_seconds_total{server_env=~\".*$server_env.*\",namespace=~\"$namespace\"},pod_name)"
   },
   {
    "name": "limit",
    "query": "1,2,3,4,5,6,7,8,9,10,15,20,25,30,40,50,70,100,9999"
   }
  ]
 },
 "panels": [
  {
   "title": "Containers status",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Containers Ready bottom $limit",
     "type": "graph",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 1 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "bottomk($limit, kubernetes_container_ready{server_env=~\"$server_env\",namespace=~\"$namespace\",pod_name=~\"$pod_name\"})",
       "legendFormat": "{{pod_name}} - {{container_name}}"
      }
     ]
    },
    {
     "title": "Containers state bottom $limit",
     "type": "graph",
     "description": "Container state, see vaules mapping: {'running': 1, 'waiting': 0, 'terminated': -1}",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 7 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "bottomk($limit, kubernetes_container_state{server_env=~\"$server_env\",namespace=~\"$namespace\",pod_name=~\"$pod_name\"})",
       "legendFormat": "{{pod_name}} - {{container_name}}"
      }
     ]
    },
    {
     "title": "Containers data collection errors",
     "type": "graph",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 13 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "topk($limit, container_scrape_error{server_env=~\"$server_env\"})",
       "legendFormat": "{{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Pods status",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Pods phase bottom $limit",
     "type": "graph",
     "description": "Pod phase, see vaules mapping: {'Running': 1, 'Pending': 0, 'Succeeded': -1, 'Unknown': -2, 'Failed': -3}",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 2 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "bottomk($limit, kubernetes_pod_phase{server_env=~\"$server_env\",namespace=~\"$namespace\",pod_name=~\"$pod_name\"})",
       "legendFormat": "{{pod_name}}"
      }
     ]
    },
    {
     "title": "Pods condition \"Ready\" bottom $limit",
     "type": "graph",
     "description": "Specifies whether the container has passed its readiness probe - True is 1, False is 0",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 8 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "bottomk($limit, kubernetes_pod_condition{server_env=~\"$server_env\",namespace=~\"$namespace\",pod_name=~\"$pod_name\",condition=\"Ready\"})",
       "legendFormat": "{{pod_name}} - {{condition}}"
      }
     ]
    },
    {
     "title": "Pods condition \"Scheduled\" bottom $limit",
     "type": "graph",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 14 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "bottomk($limit, kubernetes_pod_condition{server_env=~\"$server_env\",namespace=~\"$namespace\",pod_name=~\"$pod_name\",condition=\"PodScheduled\"})",
       "legendFormat": "{{pod_name}} - {{condition}}"
      }
     ]
    },
    {
     "title": "Pods condition \"Initialized\" bottom $limit",
     "type": "graph",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 20 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "bottomk($limit, kubernetes_pod_condition{server_env=~\"$server_env\",namespace=~\"$namespace\",pod_name=~\"$pod_name\",condition=\"Initialized\"})",
       "legendFormat": "{{pod_name}} - {{condition}}"
      }
     ]
    },
    {
     "title": "Pods condition \"Containers Ready\" bottom $limit",
     "type": "graph",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 26 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "bottomk($limit, kubernetes_pod_condition{server_env=~\"$server_env\",namespace=~\"$namespace\",pod_name=~\"$pod_name\",condition=\"ContainersReady\"})",
       "legendFormat": "{{pod_name}} - {{condition}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Exporters status",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "Exporters down",
     "type": "graph",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 33 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "up{server_env=~\"$server_env\"} != 1",
       "legendFormat": "{{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "API metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "API requests count all",
     "type": "graph",
     "description": "Counter of apiserver requests broken out for each verb, API resource, client, and HTTP response contentType and code",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 34 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(apiserver_request_count{server_env=~\"$server_env\"}[5m]))",
       "legendFormat": "all sum"
      }
     ]
    },
    {
     "title": "API requests count top $limit",
     "type": "graph",
     "description": "Counter of apiserver requests broken out for each verb, API resource, client, and HTTP response contentType and code",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 40 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "topk($limit, rate(apiserver_request_count{server_env=~\"$server_env\"}[5m]))",
       "legendFormat": "{{instance}} - {{resource}} - {{verb}} - {{code}}"
      }
     ]
    },
    {
     "title": "Depths of workqueues",
     "type": "graph",
     "description": "Current depth of workqueues",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 46 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "APIServiceOpenAPIAggregationControllerQueue1_depth{server_env=~\"$server_env\"}",
       "legendFormat": "{{instance}} APIServiceOpenAPIAggregationControllerQueue1_depth"
      },
      {
       "expr": "APIServiceRegistrationController_depth{server_env=~\"$server_env\"}",
       "legendFormat": "{{instance}} APIServiceRegistrationController_depth"
      },
      {
       "expr": "AvailableConditionController_depth{server_env=~\"$server_env\"}",
       "legendFormat": "{{instance}} AvailableConditionController_depth"
      },
      {
       "expr": "DiscoveryController_depth{server_env=~\"$server_env\"}",
       "legendFormat": "{{instance}} DiscoveryController_depth"
      },
      {
       "expr": "admission_quota_controller_depth{server_env=~\"$server_env\"}",
       "legendFormat": "{{instance}} admission_quota_controller_depth"
      },
      {
       "expr": "autoregister_depth{server_env=~\"$server_env\"}",
       "legendFormat": "{{instance}} autoregister_depth"
      },
      {
       "expr": "crdEstablishing_depth{server_env=~\"$server_env\"}",
       "legendFormat": "{{instance}} crdEstablishing_depth"
      }
     ]
    },
    {
     "title": "Adds to workqueues rate",
     "type": "graph",
     "description": "Current adds to workqueues",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 52 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(APIServiceOpenAPIAggregationControllerQueue1_adds{server_env=~\"$server_env\"}[5m])",
       "legendFormat": "{{instance}} APIServiceOpenAPIAggregationControllerQueue1_depth"
      },
      {
       "expr": "rate(APIServiceRegistrationController_adds{server_env=~\"$server_env\"}[5m])",
       "legendFormat": "{{instance}} APIServiceRegistrationController_depth"
      },
      {
       "expr": "rate(AvailableConditionController_adds{server_env=~\"$server_env\"}[5m])",
       "legendFormat": "{{instance}} AvailableConditionController_depth"
      },
      {
       "expr": "rate(DiscoveryController_adds{server_env=~\"$server_env\"}[5m])",
       "legendFormat": "{{instance}} DiscoveryController_depth"
      },
      {
       "expr": "rate(admission_quota_controller_adds{server_env=~\"$server_env\"}[5m])",
       "legendFormat": "{{instance}} admission_quota_controller_depth"
      },
      {
       "expr": "rate(autoregister_adds{server_env=~\"$server_env\"}[5m])",
       "legendFormat": "{{instance}} autoregister_depth"
      },
      {
       "expr": "rate(crdEstablishing_adds{server_env=~\"$server_env\"}[5m])",
       "legendFormat": "{{instance}} crdEstablishing_depth"
      }
     ]
    },
    {
     "title": "Failed token requests",
     "type": "graph",
     "description": "Counter of failed Token() requests to the alternate token source",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 58 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(get_token_fail_count{server_env=~\"$server_env\"}[5m])",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Get token requests",
     "type": "graph",
     "description": "Counter of total Token() requests to the alternate token source",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 64 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(get_token_count{server_env=~\"$server_env\"}[5m])",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Etcd objects count top $limit",
     "type": "graph",
     "description": "Number of stored objects at the time of last check split by kind",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 70 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "topk($limit, rate(etcd_object_counts{server_env=~\"$server_env\"}[5m]))",
       "legendFormat": "{{instance}} - {{resource}}"
      }
     ]
    }
   ]
  },
  { "title": "Nodes state", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "Nodes ready",
   "type": "graph",
   "description": "Ready == 1",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "kubernetes_node_condition{server_env=~\"$server_env\",condition=\"Ready\"}",
     "legendFormat": "{{node_name}}"
    }
   ]
  },
  {
   "title": "Nodes alert conditions top $limit",
   "type": "graph",
   "description": "Alert == 1",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "topk($limit, kubernetes_node_condition{server_env=~\"$server_env\",condition!=\"Ready\"})",
     "legendFormat": "{{node_name}} - {{condition}}"
    }
   ]
  },
  {
   "title": "Containers CPU",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU time total",
     "type": "graph",
     "description": "CPU time consumed in seconds",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 21 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "topk($limit, rate(container_cpu_usage_seconds_total{server_env=~\"$server_env\",namespace=~\"$namespace\",pod_name=~\"$pod_name\",container_name!~\"^POD$|^$\"}[5m]))",
       "legendFormat": "{{pod_name}} - {{container_name}}"
      }
     ]
    },
    {
     "title": "CPU time system",
     "type": "graph",
     "description": "CPU time consumed in seconds",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 27 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "topk($limit, rate(container_cpu_system_seconds_total{server_env=~\"$server_env\",namespace=~\"$namespace\",pod_name=~\"$pod_name\",container_name!~\"^POD$|^$\"}[5m]))",
       "legendFormat": "{{pod_name}} - {{container_name}}"
      }
     ]
    },
    {
     "title": "CPU time user",
     "type": "graph",
     "description": "CPU time consumed in seconds",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 33 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "topk($limit, rate(container_cpu_user_seconds_total{server_env=~\"$server_env\",namespace=~\"$namespace\",pod_name=~\"$pod_name\",container_name!~\"^POD$|^$\"}[5m]))",
       "legendFormat": "{{pod_name}} - {{container_name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Containers System",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 },
   "collapsed": true,
   "panels": [
    {
     "title": "Uptime",
     "type": "graph",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 24 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "bottomk($limit, container_last_seen{server_env=~\"$server_env\",namespace=~\"$namespace\",pod_name=~\"$pod_name\",container_name!~\"^POD$|^$\"} - container_start_time_seconds)",
       "legendFormat": "{{pod_name}} - {{container_name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Containers Memory",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 },
   "collapsed": true,
   "panels": [
    {
     "title": "container_memory_rss_bytes",
     "type": "graph",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 7 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "topk($limit, container_memory_rss{server_env=~\"$server_env\",namespace=~\"$namespace\",pod_name=~\"$pod_name\",container_name!~\"^POD$|^$\"})",
       "legendFormat": "{{pod_name}} - {{container_name}}"
      }
     ]
    },
    {
     "title": "container_memory_failures_total",
     "type": "graph",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 13 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "topk($limit, rate(container_memory_failures_total{server_env=~\"$server_env\",namespace=~\"$namespace\",pod_name=~\"$pod_name\",container_name!~\"^POD$|^$\"}[5m]))",
       "legendFormat": "{{pod_name}} - {{container_name}}"
      }
     ]
    },
    {
     "title": "container_memory_failcnt",
     "type": "graph",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 19 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "topk($limit, rate(container_memory_failcnt{server_env=~\"$server_env\",namespace=~\"$namespace\",pod_name=~\"$pod_name\",container_name!~\"^POD$|^$\"}[5m]))",
       "legendFormat": "{{pod_name}} - {{container_name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Containers Network",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 },
   "collapsed": true,
   "panels": [
    {
     "title": "Network Receive / Transmit bytes",
     "type": "graph",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 8 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "topk($limit, rate(container_network_receive_bytes_total{server_env=~\"$server_env\",namespace=~\"$namespace\",pod_name=~\"$pod_name\",container_name=\"POD\"}[5m]))",
       "legendFormat": "{{pod_name}} - {{container_name}} - {{interface}} - Receive"
      },
      {
       "expr": "topk($limit, rate(container_network_transmit_bytes_total{server_env=~\"$server_env\",namespace=~\"$namespace\",pod_name=~\"$pod_name\",container_name=\"POD\"}[5m]))",
       "legendFormat": "{{pod_name}} - {{container_name}} - {{interface}} - Transmit"
      }
     ]
    },
    {
     "title": "Network Receive / Transmit packets",
     "type": "graph",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 14 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "topk($limit, rate(container_network_receive_packets_total{server_env=~\"$server_env\",namespace=~\"$namespace\",pod_name=~\"$pod_name\",container_name=\"POD\"}[5m]))",
       "legendFormat": "{{pod_name}} - {{container_name}} - {{interface}} - Receive"
      },
      {
       "expr": "topk($limit, rate(container_network_transmit_packets_total{server_env=~\"$server_env\",namespace=~\"$namespace\",pod_name=~\"$pod_name\",container_name=\"POD\"}[5m]))",
       "legendFormat": "{{pod_name}} - {{container_name}} - {{interface}} - Transmit"
      }
     ]
    },
    {
     "title": "Network Receive / Transmit errors",
     "type": "graph",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 20 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "topk($limit, rate(container_network_receive_errors_total{server_env=~\"$server_env\",namespace=~\"$namespace\",pod_name=~\"$pod_name\",container_name=\"POD\"}[5m]))",
       "legendFormat": "{{pod_name}} - {{container_name}} - {{interface}} - Receive"
      },
      {
       "expr": "topk($limit, rate(container_network_transmit_errors_total{server_env=~\"$server_env\",namespace=~\"$namespace\",pod_name=~\"$pod_name\",container_name=\"POD\"}[5m]))",
       "legendFormat": "{{pod_name}} - {{container_name}} - {{interface}} - Transmit"
      }
     ]
    },
    {
     "title": "Network Receive / Transmit dropped packets",
     "type": "graph",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 26 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "topk($limit, rate(container_network_receive_packets_dropped_total{server_env=~\"$server_env\",namespace=~\"$namespace\",pod_name=~\"$pod_name\",container_name=\"POD\"}[5m]))",
       "legendFormat": "{{pod_name}} - {{container_name}} - {{interface}} - Receive"
      },
      {
       "expr": "topk($limit, rate(container_network_transmit_packets_dropped_total{server_env=~\"$server_env\",namespace=~\"$namespace\",pod_name=~\"$pod_name\",container_name=\"POD\"}[5m]))",
       "legendFormat": "{{pod_name}} - {{container_name}} - {{interface}} - Transmit"
      }
     ]
    }
   ]
  },
  {
   "title": "Host machines CPU",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU in use",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 25 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "1 - avg by (instance_id) (irate(node_cpu_seconds_total{mode=\"idle\",server_env=~\"$server_env\",ASG=\"$asg\"}[5m]))",
       "legendFormat": "{{instance}} {{instance_id}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Host machines System",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 },
   "collapsed": true,
   "panels": [
    {
     "title": "LA1 ASG",
     "type": "graph",
     "description": "Load Averages",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "node_load1{server_env=~\"$server_env\",ASG=\"$asg\"}",
       "legendFormat": "{{instance}} {{instance_id}}"
      },
      {
       "expr": "max (instance:node_cpus:count{server_env=~\"$server_env\",ASG=\"$asg\"})",
       "legendFormat": "number of cores"
      }
     ]
    },
    {
     "title": "Uptime",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "node_time_seconds{server_env=~\"$server_env\",ASG=\"$asg\"} - node_boot_time_seconds",
       "legendFormat": "{{instance}} | {{instance_id}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Host machines Memory",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 },
   "collapsed": true,
   "panels": [
    {
     "title": "Memory in use",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 11 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "(node_memory_MemTotal_bytes{server_env=~\"$server_env\",ASG=\"$asg\"} - node_memory_MemAvailable_bytes) / node_memory_MemTotal_bytes",
       "legendFormat": "{{instance}} {{instance_id}} "
      }
     ]
    }
   ]
  },
  {
   "title": "Host machines Network",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 },
   "collapsed": true,
   "panels": [
    {
     "title": "Network traffic",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 19 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "irate(node_network_receive_bytes_total{server_env=~\"$server_env\",ASG=\"$asg\"}[5m])",
       "legendFormat": "{{instance}} {{instance_id}} {{device}} - Receive"
      },
      {
       "expr": "irate(node_network_transmit_bytes_total{server_env=~\"$server_env\",ASG=\"$asg\"}[5m])",
       "legendFormat": "{{instance}} {{instance_id}} {{device}} - Transmit"
      }
     ]
    },
    {
     "title": "Network packets",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 19 },
     "yaxes": [
      { "format": "pps" }
     ],
     "targets": [
      {
       "expr": "irate(node_network_receive_packets_total{server_env=~\"$server_env\",ASG=\"$asg\"}[5m])",
       "legendFormat": "{{instance}} {{instance_id}} {{device}} - Receive"
      },
      {
       "expr": "irate(node_network_transmit_packets_total{server_env=~\"$server_env\",ASG=\"$asg\"}[5m])",
       "legendFormat": "{{instance}} {{instance_id}} {{device}} - Transmit"
      }
     ]
    }
   ]
  },
  {
   "title": "Host machines Disk",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 },
   "collapsed": true,
   "panels": [
    {
     "title": "Disk free %",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 22 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "100 * ( node_filesystem_avail_bytes{mountpoint=\"/\",server_env=~\"$server_env\",ASG=\"$asg\"} / (node_filesystem_size_bytes - ( node_filesystem_free_bytes - node_filesystem_avail_bytes)))",
       "legendFormat": "{{instance}} {{instance_id}}"
      }
     ]
    },
    {
     "title": "Disk free",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 22 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "node_filesystem_free_bytes{mountpoint=\"/\",server_env=~\"$server_env\",ASG=\"$asg\"}",
       "legendFormat": "{{instance}} {{instance_id}}"
      }
     ]
    },
    {
     "title": "Disk bytes",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 31 },
     "yaxes": [
      { "format": "Bps", "label": "Bytes read (-) / write (+)" }
     ],
     "targets": [
      {
       "expr": "irate(node_disk_read_bytes_total{server_env=~\"$server_env\",ASG=\"$asg\"}[5m])",
       "legendFormat": "{{instance}} {{instance_id}} {{device}} - Read bytes"
      },
      {
       "expr": "irate(node_disk_written_bytes_total{server_env=~\"$server_env\",ASG=\"$asg\"}[5m])",
       "legendFormat": "{{instance}} {{instance_id}} {{device}} - Write bytes"
      }
     ]
    },
    {
     "title": "Disk operations",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 31 },
     "yaxes": [
      { "format": "iops", "label": "Bytes read (-) / write (+)" }
     ],
     "targets": [
      {
       "expr": "irate(node_disk_reads_completed_total{server_env=~\"$server_env\",ASG=\"$asg\"}[5m])",
       "legendFormat": "{{instance}} {{instance_id}} {{device}} - Read"
      },
      {
       "expr": "irate(node_disk_writes_completed_total{server_env=~\"$server_env\",ASG=\"$asg\"}[5m])",
       "legendFormat": "{{instance}} {{instance_id}} {{device}} - Write "
      }
     ]
    }
   ]
  },
  {
   "title": "Core DNS metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 },
   "collapsed": true,
   "panels": [
    {
     "title": "Proxy requests duration sum",
     "type": "graph",
     "description": "Sum of all proxy requests time (in seconds)",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 14 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "rate(coredns_proxy_request_duration_seconds_count{server_env=~\"$server_env\"}[5m])",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Health requests duration sum",
     "type": "graph",
     "description": "Sum of all health requests time (in seconds)",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 20 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "rate(coredns_health_request_duration_seconds_count{server_env=~\"$server_env\"}[5m])",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "DNS requests duration sum",
     "type": "graph",
     "description": "Sum of all DNS requests time (in seconds)",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 26 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "rate(coredns_dns_request_duration_seconds_count{server_env=~\"$server_env\"}[5m])",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Panics number",
     "type": "graph",
     "description": "A metrics that counts the number of panics",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 32 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(coredns_panic_count_total{server_env=~\"$server_env\"}[5m])",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "DNS requests count",
     "type": "graph",
     "description": "Counter of DNS requests made per zone, protocol and family",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 38 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(coredns_dns_request_count_total{server_env=~\"$server_env\"}[5m])",
       "legendFormat": "{{instance}} - {{server}} - {{zone}}"
      }
     ]
    },
    {
     "title": "DNS response status codes count",
     "type": "graph",
     "description": "Counter of response status codes",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 44 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(coredns_dns_response_rcode_count_total{server_env=~\"$server_env\"}[5m])",
       "legendFormat": "{{instance}} -{{rcode}}- {{server}} - {{zone}}"
      }
     ]
    }
   ]
  }
 ]
}