{
 "title": "Elasticsearch (elasticsearch_exporter)",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "server_env",
    "label": "Environment",
    "query": "label_values(prometheus_config_last_reload_successful, server_env)"
   },
   { "name": "data_source", "label": "Data source", "query": "prometheus" },
   {
    "name": "project",
    "label": "Project",
    "query": "label_values(elasticsearch_cluster_health_up{server_env=~\"$server_env\"},project)"
   },
   {
    "name": "hostname",
    "label": "Host name",
    "query": "label_values(elasticsearch_cluster_health_up{server_env=~\"$server_env\",project=~\"$project\"},hostname)"
   },
   {
    "name": "limit",
    "query": "1,2,3,4,5,6,7,8,9,10,15,20,25,30,40,50,70,100,9999"
   }
  ]
 },
 "panels": [
  {
   "title": "Exporter status",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Elasticsearch exporter status (bottom $limit)",
     "type": "graph",
     "description": "OK = 1",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 1 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "bottomk($limit, up{instance=~\".*:9114\",server_env=~\"$server_env\",project=~\"$project\",hostname=~\"$hostname\"})",
       "legendFormat": "{{hostname}}"
      }
     ]
    },
    {
     "title": "Elasticsearch scrape status (bottom $limit)",
     "type": "graph",
     "description": "OK = 1\n\nWas the last scrape of the ElasticSearch cluster health endpoint successful.\n\nWas the last scrape of the ElasticSearch nodes endpoint successful.",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 7 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "bottomk($limit, elasticsearch_cluster_health_up{server_env=~\"$server_env\",project=~\"$project\",hostname=~\"$hostname\"})",
       "legendFormat": "{{hostname}} health"
      },
      {
       "expr": "bottomk($limit, elasticsearch_node_stats_up{server_env=~\"$server_env\",project=~\"$project\",hostname=~\"$hostname\"})",
       "legendFormat": "{{hostname}} node_stats"
      }
     ]
    }
   ]
  },
  {
   "title": "Health",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Health status (top $limit)",
     "type": "graph",
     "description": "Green = 1 = OK\n\nYellow = 1 = cluster is not healthy, but in working condition\n\nRed = 1 = cluster is not healthy",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 2 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "topk($limit, elasticsearch_cluster_health_status{server_env=~\"$server_env\",project=~\"$project\",hostname=~\"$hostname\"})",
       "legendFormat": "{{hostname}} {{color}}"
      }
     ]
    }
   ]
  },
  { "title": "JVM metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 } },
  {
   "title": "GC runs count (top $limit)",
   "type": "graph",
   "description": "Count of JVM GC runs",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 3 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk($limit, rate(elasticsearch_jvm_gc_collection_seconds_count{server_env=~\"$server_env\",project=~\"$project\",hostname=~\"$hostname\"}[5m]))",
     "legendFormat": "{{hostname}} {{gc}}"
    }
   ]
  },
  {
   "title": "GC run time (top $limit)",
   "type": "graph",
   "description": "GC run time in seconds",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "topk($limit, rate(elasticsearch_jvm_gc_collection_seconds_sum{server_env=~\"$server_env\",project=~\"$project\",hostname=~\"$hostname\"}[5m]))",
     "legendFormat": "{{hostname}} {{gc}}"
    }
   ]
  },
  {
   "title": "JVM buffer currently used (top $limit)",
   "type": "graph",
   "description": "JVM buffer currently used",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "topk($limit, elasticsearch_jvm_buffer_pool_used_bytes{server_env=~\"$server_env\",project=~\"$project\",hostname=~\"$hostname\"})",
     "legendFormat": "{{hostname}} {{type}}"
    }
   ]
  },
  {
   "title": "Buffer used (top $limit)",
   "type": "graph",
   "description": "JVM buffer currently used",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "topk($limit, elasticsearch_jvm_buffer_pool_used_bytes{server_env=~\"$server_env\",project=~\"$project\",hostname=~\"$hostname\"})",
     "legendFormat": "{{hostname}} {{type}}"
    }
   ]
  },
  {
   "title": "Memory used by pool (top $limit)",
   "type": "graph",
   "description": "JVM memory currently used by pool",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "topk($limit, elasticsearch_jvm_memory_pool_used_bytes{server_env=~\"$server_env\",project=~\"$project\",hostname=~\"$hostname\"})",
     "legendFormat": "{{hostname}} {{pool}}"
    }
   ]
  },
  {
   "title": "Memory used by area (top $limit)",
   "type": "graph",
   "description": "JVM memory currently used by area",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "topk($limit, elasticsearch_jvm_memory_used_bytes{server_env=~\"$server_env\",project=~\"$project\",hostname=~\"$hostname\"})",
     "legendFormat": "{{hostname}} {{area}}"
    }
   ]
  }
 ]
}