{
 "title": "Haproxy exporter custom",
 "description": "Show haproxy stats per host",
 "tags": [ "haproxy" ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "job",
    "label": "Job",
    "query": "label_values(node_monit{key=\"status\",type=\"system\"}, job)"
   },
   {
    "name": "node",
    "label": "Host:",
    "query": "label_values(haproxy_up{job=~\"$job\",instance=~\".*:9101\"}, instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "Haproxy status (up/down)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "haproxy_up{instance=\"$node\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Haproxy server status (up/down)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "haproxy_server_up{instance=\"$node\"}",
     "legendFormat": "{{server}}"
    }
   ]
  },
  {
   "title": "Haproxy backend status (up/down)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "haproxy_backend_up{instance=\"$node\"}",
     "legendFormat": "{{backend}}"
    }
   ]
  },
  {
   "title": "Requests per frontend",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "rate(haproxy_frontend_http_requests_total{instance=\"$node\"}[5m])",
     "legendFormat": "{{frontend}}"
    }
   ]
  },
  {
   "title": "Bytes per backend",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "rate(haproxy_backend_bytes_in_total{instance=\"$node\"}[5m]) * -1",
     "legendFormat": "{{backend}} IN"
    },
    {
     "expr": "rate(haproxy_backend_bytes_out_total{instance=\"$node\"}[5m])",
     "legendFormat": "{{backend}} OUT"
    }
   ]
  }
 ]
}