{
 "title": "HTTP checks (blackbox_exporter)",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "data_source", "label": "Data source", "query": "prometheus" },
   {
    "name": "hostname",
    "label": "Host",
    "query": "label_values(probe_success{job!=\"blackbox-exporter kubernetes services\"}, hostname)"
   },
   {
    "name": "limit",
    "query": "1,2,3,4,5,6,7,8,9,10,15,20,25,30,40,50,70,100,9999"
   }
  ]
 },
 "panels": [
  {
   "title": "Status",
   "type": "graph",
   "description": "1 = OK",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "probe_success{hostname=~\"$hostname\",job!=\"blackbox-exporter kubernetes services\"}",
     "legendFormat": "{{hostname}} {{instance}}"
    }
   ]
  },
  {
   "title": "Regex status",
   "type": "graph",
   "description": "0 = OK",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "probe_failed_due_to_regex{hostname=~\"$hostname\",job!=\"blackbox-exporter kubernetes services\"}",
     "legendFormat": "{{hostname}} {{instance}}"
    }
   ]
  },
  {
   "title": "Http status code",
   "type": "graph",
   "description": "Http code for check\nOK = 200",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "probe_http_status_code{hostname=~\"$hostname\",job!=\"blackbox-exporter kubernetes services\"}",
     "legendFormat": "{{hostname}} {{instance}}"
    }
   ]
  },
  {
   "title": "Check duration",
   "type": "graph",
   "description": "Check duration in seconds",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "probe_duration_seconds{hostname=~\"$hostname\",job!=\"blackbox-exporter kubernetes services\"}",
     "legendFormat": "{{hostname}} {{instance}}"
    }
   ]
  },
  {
   "title": "Check duration per step",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "probe_http_duration_seconds{hostname=~\"$hostname\",job!=\"blackbox-exporter kubernetes services\"}",
     "legendFormat": "{{hostname}} {{instance}} {{phase}}"
    }
   ]
  },
  {
   "title": "Content length",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "probe_http_content_length{hostname=~\"$hostname\",job!=\"blackbox-exporter kubernetes services\"}",
     "legendFormat": "{{hostname}} {{instance}}"
    }
   ]
  },
  {
   "title": "SSL expiration time",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "probe_ssl_earliest_cert_expiry{hostname=~\"$hostname\"} - time()",
     "legendFormat": "{{hostname}} {{instance}}"
    }
   ]
  }
 ]
}