{
 "title": "HTTP checks (pingdom-exporter)",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "server_env",
    "label": "Environment",
    "query": "label_values(prometheus_config_last_reload_successful, server_env)"
   },
   { "name": "data_source", "label": "Data source", "query": "prometheus" },
   {
    "name": "project",
    "label": "Project",
    "query": "label_values(pingdom_exporter_up{server_env=~\"$server_env\"},project)"
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": "label_values(pingdom_exporter_up{server_env=~\"$server_env\"},instance)"
   },
   {
    "name": "hostname",
    "label": "Host",
    "query": "label_values(pingdom_exporter_check_status{server_env=~\"$server_env\",project=~\"$project\"}, hostname)"
   },
   {
    "name": "limit",
    "query": "1,2,3,4,5,6,7,8,9,10,15,20,25,30,40,50,70,100,9999"
   }
  ]
 },
 "panels": [
  {
   "title": "Exporter status",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Exporter status (bottom $limit)",
     "type": "graph",
     "description": "Ok = 1",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 1 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "bottomk($limit, up{server_env=~\"$server_env\",project=~\"$project\",instance=~\"$instance\"})",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Exporter scrape status (bottom $limit)",
     "type": "graph",
     "description": "Ok = 1",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 8 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "bottomk($limit, pingdom_exporter_up{server_env=~\"$server_env\",project=~\"$project\",instance=~\"$instance\"})",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Exporter scrape errors (top $limit)",
     "type": "graph",
     "description": "Ok = 0",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 15 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "topk($limit, rate(pingdom_exporter_errors_total{server_env=~\"$server_env\",project=~\"$project\",instance=~\"$instance\"}[5m]))",
       "legendFormat": "{{instance}}"
      }
     ]
    }
   ]
  },
  { "title": "Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  {
   "title": "Status (bottom $limit)",
   "type": "graph",
   "description": "Current status of check \n\nup = 1\n\ndown = 0\n\nunconfirmed_down = -1\n\nunknown = -2\n\npaused = -3",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 2 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "bottomk($limit, pingdom_exporter_check_status{server_env=~\"$server_env\",project=~\"$project\",hostname=~\"$hostname\"})",
     "legendFormat": "{{name}} - {{hostname}}"
    }
   ]
  },
  { "title": "Response", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Response time (bottom $limit)",
   "type": "graph",
   "description": "Response time in seconds of last test.",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "bottomk($limit, pingdom_exporter_check_lastresponsetime_seconds{server_env=~\"$server_env\",project=~\"$project\",hostname=~\"$hostname\"})",
     "legendFormat": "{{name}} - {{hostname}}"
    }
   ]
  },
  { "title": "Error", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Last error (bottom $limit)",
   "type": "graph",
   "description": "Last error (if any) = seconds ago",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "bottomk($limit, time() - pingdom_exporter_check_lasterrortime_timestamp_seconds{server_env=~\"$server_env\",project=~\"$project\",hostname=~\"$hostname\"})",
     "legendFormat": "{{name}} - {{hostname}}"
    }
   ]
  },
  { "title": "Last test", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "Last test (bottom $limit)",
   "type": "graph",
   "description": "Last test time (if any) = seconds ago",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "bottomk($limit, time() - pingdom_exporter_check_lasttesttime_timestamp_seconds{server_env=~\"$server_env\",project=~\"$project\",hostname=~\"$hostname\"})",
     "legendFormat": "{{name}} - {{hostname}}"
    }
   ]
  },
  { "title": "Creation", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 } },
  {
   "title": "Creation time (bottom $limit)",
   "type": "graph",
   "description": "Creating time. Format is UNIX timestamp",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 34 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "bottomk($limit, time() - pingdom_exporter_check_created_timestamp_seconds{server_env=~\"$server_env\",project=~\"$project\",hostname=~\"$hostname\"})",
     "legendFormat": "{{name}} - {{hostname}}"
    }
   ]
  }
 ]
}