{
 "title": "Kubernetes metrics",
 "tags": [
  "prometheus",
  "eks"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "server_env",
    "query": "label_values(prometheus_config_last_reload_successful, server_env)"
   },
   { "name": "data_source", "label": "Data source", "query": "prometheus" },
   {
    "name": "node_name",
    "label": "Node name",
    "query": "label_values(node_load1{server_env=~\".*$server_env.*\"},node_name)"
   },
   {
    "name": "namespace",
    "query": "label_values(container_cpu_system_seconds_total{server_env=~\".*$server_env.*\"},namespace)"
   },
   {
    "name": "pod_name",
    "query": "label_values(container_cpu_system_seconds_total{server_env=~\".*$server_env.*\",namespace=~\"$namespace\"},pod_name)"
   },
   {
    "name": "service_name",
    "query": "label_values(container_cpu_system_seconds_total{server_env=~\".*$server_env.*\",namespace=~\"$namespace\"},pod_name)"
   },
   {
    "name": "container_name",
    "query": "label_values(container_start_time_seconds{server_env=~\".*$server_env.*\",namespace=~\"$namespace\"},container_name)"
   },
   {
    "name": "service_name_http",
    "query": "label_values(probe_success{server_env=~\".*$server_env.*\",job=\"blackbox-exporter kubernetes services\"}, service_name)"
   },
   {
    "name": "limit",
    "query": "1,2,3,4,5,6,7,8,9,10,15,20,25,30,40,50,70,100,9999"
   }
  ]
 },
 "panels": [
  {
   "title": "Services uptime",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "All services uptime (last 30 days)",
     "type": "graph",
     "description": "1 is OK\n0 is Fail",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 1 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "avg_over_time(service:http_status:minimal{server_env=\"$server_env\"}[30d])",
       "legendFormat": "uptime"
      }
     ]
    },
    {
     "title": "Uptime per service (last 30 days)",
     "type": "graph",
     "description": "1 is OK\n0 is Fail",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 7 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "avg_over_time(probe_success{server_env=~\"$server_env\",job=\"kubernetes-services-healthz\",request=\"/healthz\",service_name!~\"kube-dns|kubernetes|metrics-server|tiller-deploy|certificates|learning-objective-maker|lti-service|pdf-converter|progress-storage\",service_name=~\"$service_name_http\",namespace!=\"istio-system\"}[30d])",
       "legendFormat": "{{instance}}{{request}}"
      }
     ]
    },
    {
     "title": "Uptime per service (last 7 days)",
     "type": "graph",
     "description": "1 is OK\n0 is Fail",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 13 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "avg_over_time(probe_success{server_env=~\"$server_env\",job=\"kubernetes-services-healthz\",request=\"/healthz\",service_name!~\"kube-dns|kubernetes|metrics-server|tiller-deploy|certificates|learning-objective-maker|lti-service|pdf-converter|progress-storage\",service_name=~\"$service_name_http\",namespace!=\"istio-system\"}[7d])",
       "legendFormat": "{{instance}}{{request}}"
      },
      {
       "expr": "avg_over_time(probe_success{server_env=~\"$server_env\",job=\"kubernetes-services\",request=\"/\",service_name!~\"kube-dns|kubernetes|metrics-server|tiller-deploy\",service_name=~\"$service_name_http\",namespace!=\"istio-system\"}[7d])",
       "legendFormat": "{{instance}}{{request}}"
      }
     ]
    },
    {
     "title": "Uptime per service (last 24 hours)",
     "type": "graph",
     "description": "1 is OK\n0 is Fail",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 19 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "avg_over_time(probe_success{server_env=~\"$server_env\",job=\"kubernetes-services-healthz\",request=\"/healthz\",service_name!~\"kube-dns|kubernetes|metrics-server|tiller-deploy|certificates|learning-objective-maker|lti-service|pdf-converter|progress-storage\",service_name=~\"$service_name_http\",namespace!=\"istio-system\"}[24h])",
       "legendFormat": "{{instance}}{{request}}"
      },
      {
       "expr": "avg_over_time(probe_success{server_env=~\"$server_env\",job=\"kubernetes-services\",request=\"/\",service_name!~\"kube-dns|kubernetes|metrics-server|tiller-deploy\",service_name=~\"$service_name_http\",namespace!=\"istio-system\"}[24h])",
       "legendFormat": "{{instance}}{{request}}"
      }
     ]
    }
   ]
  },
  { "title": "Services resources usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  {
   "title": "Memory usage per service",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 2 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "topk($limit, sum(container_memory_rss{service=~\"$service_name\",instance=~\"$node_name\",server_env=~\"$server_env\",namespace=~\"$namespace\",pod_name=~\"$pod_name\",container_name!~\"^POD$|^$\"}) by (service))",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "CPU time total per service",
   "type": "graph",
   "description": "CPU time consumed in seconds",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk($limit, sum(rate(container_cpu_usage_seconds_total{service=~\"$service_name.*\",instance=~\"$node_name\",server_env=~\"$server_env\",namespace=~\"$namespace\",pod_name=~\"$pod_name\",container_name!~\"^POD$|^$\"}[5m])) by (service))",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "Services http checks",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 },
   "collapsed": true,
   "panels": [
    {
     "title": "Status (bottom $limit)",
     "type": "graph",
     "description": "1 is OK\n0 is Fail",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 3 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "bottomk($limit, probe_success{server_env=~\"$server_env\",service_name=~\"$service_name_http\",job=\"blackbox-exporter kubernetes services\"})",
       "legendFormat": "{{instance}}{{request}}"
      }
     ]
    },
    {
     "title": "probe_http_status_code (top $limit)",
     "type": "graph",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 9 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "topk($limit, probe_http_status_code{server_env=~\"$server_env\",service_name=~\"$service_name_http\",job=\"blackbox-exporter kubernetes services\"})",
       "legendFormat": "{{instance}}{{request}}"
      }
     ]
    },
    {
     "title": "probe_duration_seconds (top $limit)",
     "type": "graph",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 15 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "topk($limit, probe_duration_seconds{server_env=~\"$server_env\",service_name=~\"$service_name_http\",job=\"blackbox-exporter kubernetes services\"})",
       "legendFormat": "{{instance}}{{request}}"
      }
     ]
    },
    {
     "title": "probe_http_duration_seconds (top $limit)",
     "type": "graph",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 21 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "topk($limit, probe_http_duration_seconds{server_env=~\"$server_env\",service_name=~\"$service_name_http\",job=\"blackbox-exporter kubernetes services\"})",
       "legendFormat": "{{instance}}{{request}} - {{phase}}"
      }
     ]
    },
    {
     "title": "probe_http_content_length (bottom $limit)",
     "type": "graph",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 27 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "bottomk($limit, probe_http_content_length{server_env=~\"$server_env\",service_name=~\"$service_name_http\",job=\"blackbox-exporter kubernetes services\"})",
       "legendFormat": "{{instance}}{{request}}"
      }
     ]
    },
    {
     "title": "Services count",
     "type": "graph",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 33 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "count(probe_success{server_env=~\"$server_env\",service_name=~\"$service_name_http\",job=\"blackbox-exporter kubernetes services\"})",
       "legendFormat": "Count"
      }
     ]
    }
   ]
  },
  {
   "title": "Nodes state",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 },
   "collapsed": true,
   "panels": [
    {
     "title": "Nodes ready",
     "type": "graph",
     "description": "Ready = 1",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 4 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "kubernetes_node_condition{server_env=~\"$server_env\",node_name=~\"$node_name\",condition=\"Ready\"}",
       "legendFormat": "{{node_name}}"
      }
     ]
    },
    {
     "title": "Nodes alert conditions top $limit",
     "type": "graph",
     "description": "Alert == 1",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 12 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "topk($limit, kubernetes_node_condition{server_env=~\"$server_env\",node_name=~\"$node_name\",condition!=\"Ready\"})",
       "legendFormat": "{{node_name}} - {{condition}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Containers uptime",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 },
   "collapsed": true,
   "panels": [
    {
     "title": "Uptime (bottom $limit)",
     "type": "graph",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 5 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "bottomk($limit, container_last_seen{server_env=~\"$server_env\",service=~\"$service_name\",instance=~\"$node_name\",namespace=~\"$namespace\",pod_name=~\"$pod_name\",container_name!~\"^POD$|^$\",container_name=~\"$container_name\"} - container_start_time_seconds)",
       "legendFormat": "{{pod_name}} - {{container_name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Containers status",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "collapsed": true,
   "panels": [
    {
     "title": "Containers Restarts number (top $limit)",
     "type": "graph",
     "description": "OK = 0",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 6 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "topk($limit, delta(kubernetes_container_restarts_total{server_env=~\"$server_env\",service=~\"$service_name\",node_name=~\"$node_name\",namespace=~\"$namespace\",pod_name=~\"$pod_name\",container_name=~\"$container_name\"}[5m]))",
       "legendFormat": "{{pod_name}} - {{container_name}}"
      }
     ]
    },
    {
     "title": "Containers Ready (bottom $limit)",
     "type": "graph",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 12 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "bottomk($limit, kubernetes_container_ready{server_env=~\"$server_env\",service=~\"$service_name\",node_name=~\"$node_name\",namespace=~\"$namespace\",pod_name=~\"$pod_name\",container_name=~\"$container_name\"})",
       "legendFormat": "{{pod_name}} - {{container_name}}"
      }
     ]
    },
    {
     "title": "Containers state (bottom $limit)",
     "type": "graph",
     "description": "Container state, see vaules mapping: {'running': 1, 'waiting': 0, 'terminated': -1}",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 18 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "bottomk($limit, kubernetes_container_state{server_env=~\"$server_env\",service=~\"$service_name\",node_name=~\"$node_name\",namespace=~\"$namespace\",pod_name=~\"$pod_name\",container_name=~\"$container_name\"})",
       "legendFormat": "{{pod_name}} - {{container_name}}"
      }
     ]
    },
    {
     "title": "Containers data collection errors",
     "type": "graph",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 24 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "topk($limit, container_scrape_error{server_env=~\"$server_env\",instance=~\"$node_name\"})",
       "legendFormat": "{{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Pods status",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "collapsed": true,
   "panels": [
    {
     "title": "Pods phase bottom $limit",
     "type": "graph",
     "description": "Pod phase, see vaules mapping: {'Running': 1, 'Pending': 0, 'Succeeded': -1, 'Unknown': -2, 'Failed': -3}",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 7 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "bottomk($limit, kubernetes_pod_phase{server_env=~\"$server_env\",service=~\"$service_name\",node_name=~\"$node_name\",namespace=~\"$namespace\",pod_name=~\"$pod_name\"})",
       "legendFormat": "{{pod_name}}"
      }
     ]
    },
    {
     "title": "Pods condition \"Ready\" bottom $limit",
     "type": "graph",
     "description": "Specifies whether the container has passed its readiness probe - True is 1, False is 0",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 13 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "bottomk($limit, kubernetes_pod_condition{server_env=~\"$server_env\",service=~\"$service_name\",node_name=~\"$node_name\",namespace=~\"$namespace\",pod_name=~\"$pod_name\",condition=\"Ready\"})",
       "legendFormat": "{{pod_name}} - {{condition}}"
      }
     ]
    },
    {
     "title": "Pods condition \"Scheduled\" bottom $limit",
     "type": "graph",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 19 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "bottomk($limit, kubernetes_pod_condition{server_env=~\"$server_env\",service=~\"$service_name\",node_name=~\"$node_name\",namespace=~\"$namespace\",pod_name=~\"$pod_name\",condition=\"PodScheduled\"})",
       "legendFormat": "{{pod_name}} - {{condition}}"
      }
     ]
    },
    {
     "title": "Pods condition \"Initialized\" bottom $limit",
     "type": "graph",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 25 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "bottomk($limit, kubernetes_pod_condition{server_env=~\"$server_env\",service=~\"$service_name\",node_name=~\"$node_name\",namespace=~\"$namespace\",pod_name=~\"$pod_name\",condition=\"Initialized\"})",
       "legendFormat": "{{pod_name}} - {{condition}}"
      }
     ]
    },
    {
     "title": "Pods condition \"Containers Ready\" bottom $limit",
     "type": "graph",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 31 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "bottomk($limit, kubernetes_pod_condition{server_env=~\"$server_env\",service=~\"$service_name\",node_name=~\"$node_name\",namespace=~\"$namespace\",pod_name=~\"$pod_name\",condition=\"ContainersReady\"})",
       "legendFormat": "{{pod_name}} - {{condition}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Pods usage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 },
   "collapsed": true,
   "panels": [
    {
     "title": "Pods usage",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "(count(kubernetes_pod_phase{server_env=\"$server_env\",node_name=~\"$node_name\"}) by (node_name)) / (max(kubernetes_node_capacity) by (node_name)) * 100",
       "legendFormat": "{{node_name}}"
      }
     ]
    },
    {
     "title": "Pods available",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "(max(kubernetes_node_capacity{server_env=\"$server_env\",node_name=~\"$node_name\"}) by (node_name)) - (count(kubernetes_pod_phase) by (node_name))",
       "legendFormat": "{{node_name}}"
      },
      {
       "expr": "max(kubernetes_node_capacity{server_env=\"$server_env\",node_name=~\"$node_name\"})",
       "legendFormat": "Node capacity"
      }
     ]
    }
   ]
  },
  {
   "title": "Exporters status",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 },
   "collapsed": true,
   "panels": [
    {
     "title": "Kubernetes exporter status",
     "type": "graph",
     "description": "Ok = 1",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 9 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "up{instance=~\".*:9610\",server_env=~\"$server_env\",node_name=~\"$node_name\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Kubernetes exporter scrape status",
     "type": "graph",
     "description": "Ok = 1",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 15 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "kubernetes_exporter_up{instance=~\".*:9610\",server_env=~\"$server_env\",node_name=~\"$node_name\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Node exporter status",
     "type": "graph",
     "description": "Ok = 1",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 21 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "up{job=\"node_exporter kubernetes\",instance=~\".*:9100\",server_env=~\"$server_env\",node_name=~\"$node_name\"}",
       "legendFormat": "{{pod_name}}"
      }
     ]
    },
    {
     "title": "Node exporter scrape status",
     "type": "graph",
     "description": "Ok = 1",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 27 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "node_scrape_collector_success{job=\"node_exporter kubernetes\",instance=~\".*:9100\",server_env=~\"$server_env\",node_name=~\"$node_name\"}",
       "legendFormat": "{{pod_name}} {{collector}}"
      }
     ]
    }
   ]
  },
  {
   "title": "API metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 },
   "collapsed": true,
   "panels": [
    {
     "title": "API requests count all",
     "type": "graph",
     "description": "Counter of apiserver requests broken out for each verb, API resource, client, and HTTP response contentType and code",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(apiserver_request_count{server_env=~\"$server_env\"}[5m]))",
       "legendFormat": "all sum"
      }
     ]
    },
    {
     "title": "API requests count top $limit",
     "type": "graph",
     "description": "Counter of apiserver requests broken out for each verb, API resource, client, and HTTP response contentType and code",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 16 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "topk($limit, rate(apiserver_request_count{server_env=~\"$server_env\"}[5m]))",
       "legendFormat": "{{instance}} - {{resource}} - {{verb}} - {{code}}"
      }
     ]
    },
    {
     "title": "Depths of workqueues",
     "type": "graph",
     "description": "Current depth of workqueues",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 22 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "APIServiceOpenAPIAggregationControllerQueue1_depth{server_env=~\"$server_env\"}",
       "legendFormat": "{{instance}} APIServiceOpenAPIAggregationControllerQueue1_depth"
      },
      {
       "expr": "APIServiceRegistrationController_depth{server_env=~\"$server_env\"}",
       "legendFormat": "{{instance}} APIServiceRegistrationController_depth"
      },
      {
       "expr": "AvailableConditionController_depth{server_env=~\"$server_env\"}",
       "legendFormat": "{{instance}} AvailableConditionController_depth"
      },
      {
       "expr": "DiscoveryController_depth{server_env=~\"$server_env\"}",
       "legendFormat": "{{instance}} DiscoveryController_depth"
      },
      {
       "expr": "admission_quota_controller_depth{server_env=~\"$server_env\"}",
       "legendFormat": "{{instance}} admission_quota_controller_depth"
      },
      {
       "expr": "autoregister_depth{server_env=~\"$server_env\"}",
       "legendFormat": "{{instance}} autoregister_depth"
      },
      {
       "expr": "crdEstablishing_depth{server_env=~\"$server_env\"}",
       "legendFormat": "{{instance}} crdEstablishing_depth"
      }
     ]
    },
    {
     "title": "Adds to workqueues rate",
     "type": "graph",
     "description": "Current adds to workqueues",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 28 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(APIServiceOpenAPIAggregationControllerQueue1_adds{server_env=~\"$server_env\"}[5m])",
       "legendFormat": "{{instance}} APIServiceOpenAPIAggregationControllerQueue1_depth"
      },
      {
       "expr": "rate(APIServiceRegistrationController_adds{server_env=~\"$server_env\"}[5m])",
       "legendFormat": "{{instance}} APIServiceRegistrationController_depth"
      },
      {
       "expr": "rate(AvailableConditionController_adds{server_env=~\"$server_env\"}[5m])",
       "legendFormat": "{{instance}} AvailableConditionController_depth"
      },
      {
       "expr": "rate(DiscoveryController_adds{server_env=~\"$server_env\"}[5m])",
       "legendFormat": "{{instance}} DiscoveryController_depth"
      },
      {
       "expr": "rate(admission_quota_controller_adds{server_env=~\"$server_env\"}[5m])",
       "legendFormat": "{{instance}} admission_quota_controller_depth"
      },
      {
       "expr": "rate(autoregister_adds{server_env=~\"$server_env\"}[5m])",
       "legendFormat": "{{instance}} autoregister_depth"
      },
      {
       "expr": "rate(crdEstablishing_adds{server_env=~\"$server_env\"}[5m])",
       "legendFormat": "{{instance}} crdEstablishing_depth"
      }
     ]
    },
    {
     "title": "Failed token requests",
     "type": "graph",
     "description": "Counter of failed Token() requests to the alternate token source",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 34 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(get_token_fail_count{server_env=~\"$server_env\"}[5m])",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Get token requests",
     "type": "graph",
     "description": "Counter of total Token() requests to the alternate token source",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 40 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(get_token_count{server_env=~\"$server_env\"}[5m])",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Etcd objects count top $limit",
     "type": "graph",
     "description": "Number of stored objects at the time of last check split by kind",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 46 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "topk($limit, rate(etcd_object_counts{server_env=~\"$server_env\"}[5m]))",
       "legendFormat": "{{instance}} - {{resource}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Containers CPU",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU time total",
     "type": "graph",
     "description": "CPU time consumed in seconds",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 11 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "topk($limit, rate(container_cpu_usage_seconds_total{server_env=~\"$server_env\",service=~\"$service_name\",instance=~\"$node_name\",namespace=~\"$namespace\",pod_name=~\"$pod_name\",container_name!~\"^POD$|^$\",container_name=~\"$container_name\"}[5m]))",
       "legendFormat": "{{pod_name}} - {{container_name}}"
      }
     ]
    },
    {
     "title": "CPU time system",
     "type": "graph",
     "description": "CPU time consumed in seconds",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 17 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "topk($limit, rate(container_cpu_system_seconds_total{server_env=~\"$server_env\",service=~\"$service_name\",instance=~\"$node_name\",namespace=~\"$namespace\",pod_name=~\"$pod_name\",container_name!~\"^POD$|^$\",container_name=~\"$container_name\"}[5m]))",
       "legendFormat": "{{pod_name}} - {{container_name}}"
      }
     ]
    },
    {
     "title": "CPU time user",
     "type": "graph",
     "description": "CPU time consumed in seconds",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 23 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "topk($limit, rate(container_cpu_user_seconds_total{server_env=~\"$server_env\",service=~\"$service_name\",instance=~\"$node_name\",namespace=~\"$namespace\",pod_name=~\"$pod_name\",container_name!~\"^POD$|^$\",container_name=~\"$container_name\"}[5m]))",
       "legendFormat": "{{pod_name}} - {{container_name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Containers Memory",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 },
   "collapsed": true,
   "panels": [
    {
     "title": "Containers memory usage (top $limit)",
     "type": "graph",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 19 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "topk($limit, container_memory_rss{server_env=~\"$server_env\",service=~\"$service_name\",instance=~\"$node_name\",namespace=~\"$namespace\",pod_name=~\"$pod_name\",container_name!~\"^POD$|^$\",container_name=~\"$container_name\"})",
       "legendFormat": "{{pod_name}} - {{container_name}}"
      },
      {
       "expr": "max(container_spec_memory_limit_bytes{server_env=~\"$server_env\",service=\"$service_name\",instance=~\"$node_name\",namespace=~\"$namespace\",pod_name=~\"$pod_name\",container_name!~\"^POD$|^$\",container_name=~\"$container_name\"})",
       "legendFormat": "Max Limit"
      }
     ]
    },
    {
     "title": "Containers memory usage % (top $limit)",
     "type": "graph",
     "description": "100% = limit",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 25 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "topk($limit, (container_memory_rss{server_env=~\"$server_env\",service=~\"$service_name\",instance=~\"$node_name\",namespace=~\"$namespace\",pod_name=~\"$pod_name\",container_name!~\"^POD$|^$\",container_name=~\"$container_name\"} / (container_spec_memory_limit_bytes - 1) * 100) > 0)",
       "legendFormat": "{{pod_name}} - {{container_name}}"
      }
     ]
    },
    {
     "title": "container_memory_failures_total",
     "type": "graph",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 31 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "topk($limit, rate(container_memory_failures_total{server_env=~\"$server_env\",service=~\"$service_name\",instance=~\"$node_name\",namespace=~\"$namespace\",pod_name=~\"$pod_name\",container_name!~\"^POD$|^$\",container_name=~\"$container_name\"}[5m]))",
       "legendFormat": "{{pod_name}} - {{container_name}}"
      }
     ]
    },
    {
     "title": "container_memory_failcnt",
     "type": "graph",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 37 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "topk($limit, rate(container_memory_failcnt{server_env=~\"$server_env\",service=~\"$service_name\",instance=~\"$node_name\",namespace=~\"$namespace\",pod_name=~\"$pod_name\",container_name!~\"^POD$|^$\",container_name=~\"$container_name\"}[5m]))",
       "legendFormat": "{{pod_name}} - {{container_name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Containers Network",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 },
   "collapsed": true,
   "panels": [
    {
     "title": "Network Receive / Transmit bytes",
     "type": "graph",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 13 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "topk($limit, rate(container_network_receive_bytes_total{server_env=~\"$server_env\",service=~\"$service_name\",instance=~\"$node_name\",namespace=~\"$namespace\",pod_name=~\"$pod_name\",container_name=\"POD\"}[5m]))",
       "legendFormat": "{{pod_name}} - {{interface}} - Receive"
      },
      {
       "expr": "topk($limit, rate(container_network_transmit_bytes_total{server_env=~\"$server_env\",service=~\"$service_name\",instance=~\"$node_name\",namespace=~\"$namespace\",pod_name=~\"$pod_name\",container_name=\"POD\"}[5m]))",
       "legendFormat": "{{pod_name}} - {{interface}} - Transmit"
      }
     ]
    },
    {
     "title": "Network Receive / Transmit packets",
     "type": "graph",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 19 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "topk($limit, rate(container_network_receive_packets_total{server_env=~\"$server_env\",service=~\"$service_name\",instance=~\"$node_name\",namespace=~\"$namespace\",pod_name=~\"$pod_name\",container_name=\"POD\"}[5m]))",
       "legendFormat": "{{pod_name}} - {{interface}} - Receive"
      },
      {
       "expr": "topk($limit, rate(container_network_transmit_packets_total{server_env=~\"$server_env\",service=~\"$service_name\",instance=~\"$node_name\",namespace=~\"$namespace\",pod_name=~\"$pod_name\",container_name=\"POD\"}[5m]))",
       "legendFormat": "{{pod_name}} - {{interface}} - Transmit"
      }
     ]
    },
    {
     "title": "Network Receive / Transmit errors",
     "type": "graph",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 25 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "topk($limit, rate(container_network_receive_errors_total{server_env=~\"$server_env\",service=~\"$service_name\",instance=~\"$node_name\",namespace=~\"$namespace\",pod_name=~\"$pod_name\",container_name=\"POD\"}[5m]))",
       "legendFormat": "{{pod_name}} - {{interface}} - Receive"
      },
      {
       "expr": "topk($limit, rate(container_network_transmit_errors_total{server_env=~\"$server_env\",service=~\"$service_name\",instance=~\"$node_name\",namespace=~\"$namespace\",pod_name=~\"$pod_name\",container_name=\"POD\"}[5m]))",
       "legendFormat": "{{pod_name}} -  {{interface}} - Transmit"
      }
     ]
    },
    {
     "title": "Network Receive / Transmit dropped packets",
     "type": "graph",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 31 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "topk($limit, rate(container_network_receive_packets_dropped_total{server_env=~\"$server_env\",service=~\"$service_name\",instance=~\"$node_name\",namespace=~\"$namespace\",pod_name=~\"$pod_name\",container_name=\"POD\"}[5m]))",
       "legendFormat": "{{pod_name}} - {{interface}} - Receive"
      },
      {
       "expr": "topk($limit, rate(container_network_transmit_packets_dropped_total{server_env=~\"$server_env\",service=\"$service_name\",instance=~\"$node_name\",namespace=~\"$namespace\",pod_name=~\"$pod_name\",container_name=\"POD\"}[5m]))",
       "legendFormat": "{{pod_name}} - {{interface}} - Transmit"
      }
     ]
    }
   ]
  },
  {
   "title": "Host machines CPU",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU in use",
     "type": "graph",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 14 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "topk($limit, 1 - sum(irate(node_cpu_seconds_total{job=\"node_exporter kubernetes\",mode=\"idle\",server_env=~\"$server_env\",node_name=~\"$node_name\",pod_name=~\"node-exporter.*\"}[5m])) without (cpu,mode) / instance:node_cpus:count)",
       "legendFormat": "{{node_name}}"
      }
     ]
    },
    {
     "title": "CPU stack  average",
     "type": "graph",
     "description": "System - Processes executing in kernel mode\n\nUser - Normal processes executing in user mode\n\nNice - Niced processes executing in user mode\n\nIdle - Waiting for something to happen\n\nIowait - Waiting for I/O to complete\n\nIrq - Servicing interrupts\n\nSoftirq - Servicing softirqs\n\nSteal - Time spent in other operating systems when running in a virtualized environment\n\nGuest - Time spent running a virtual CPU for a guest operating system",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 20 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "avg(topk($limit, sum(irate(node_cpu_seconds_total{job=\"node_exporter kubernetes\",mode=\"system\",server_env=~\"$server_env\",node_name=~\"$node_name\",pod_name=~\"node-exporter.*\"}[5m])) without (cpu,mode) / instance:node_cpus:count))",
       "legendFormat": "System"
      },
      {
       "expr": "avg(topk($limit, sum(irate(node_cpu_seconds_total{job=\"node_exporter kubernetes\",mode='user',server_env=~\"$server_env\",node_name=~\"$node_name\",pod_name=~\"node-exporter.*\"}[5m])) without (cpu,mode) / instance:node_cpus:count))",
       "legendFormat": "User"
      },
      {
       "expr": "avg(topk($limit, sum(irate(node_cpu_seconds_total{job=\"node_exporter kubernetes\",mode='nice',server_env=~\"$server_env\",node_name=~\"$node_name\",pod_name=~\"node-exporter.*\"}[5m])) without (cpu,mode) / instance:node_cpus:count))",
       "legendFormat": "Nice"
      },
      {
       "expr": "avg(topk($limit, sum(irate(node_cpu_seconds_total{job=\"node_exporter kubernetes\",mode='idle',server_env=~\"$server_env\",node_name=~\"$node_name\",pod_name=~\"node-exporter.*\"}[5m])) without (cpu,mode) / instance:node_cpus:count))",
       "legendFormat": "Idle"
      },
      {
       "expr": "avg(topk($limit, sum(irate(node_cpu_seconds_total{job=\"node_exporter kubernetes\",mode='iowait',server_env=~\"$server_env\",node_name=~\"$node_name\",pod_name=~\"node-exporter.*\"}[5m])) without (cpu,mode) / instance:node_cpus:count))",
       "legendFormat": "Iowait"
      },
      {
       "expr": "avg(topk($limit, sum(irate(node_cpu_seconds_total{job=\"node_exporter kubernetes\",mode='irq',server_env=~\"$server_env\",node_name=~\"$node_name\",pod_name=~\"node-exporter.*\"}[5m])) without (cpu,mode) / instance:node_cpus:count))",
       "legendFormat": "Irq"
      },
      {
       "expr": "avg(topk($limit, sum(irate(node_cpu_seconds_total{job=\"node_exporter kubernetes\",mode='softirq',server_env=~\"$server_env\",node_name=~\"$node_name\",pod_name=~\"node-exporter.*\"}[5m])) without (cpu,mode) / instance:node_cpus:count))",
       "legendFormat": "Softirq"
      },
      {
       "expr": "avg(topk($limit, sum(irate(node_cpu_seconds_total{job=\"node_exporter kubernetes\",mode='steal',server_env=~\"$server_env\",node_name=~\"$node_name\",pod_name=~\"node-exporter.*\"}[5m])) without (cpu,mode) / instance:node_cpus:count))",
       "legendFormat": "Steal"
      },
      {
       "expr": "avg(topk($limit, sum(irate(node_cpu_seconds_total{job=\"node_exporter kubernetes\",mode='guest',server_env=~\"$server_env\",node_name=~\"$node_name\",pod_name=~\"node-exporter.*\"}[5m])) without (cpu,mode) / instance:node_cpus:count))",
       "legendFormat": "Guest"
      }
     ]
    }
   ]
  },
  {
   "title": "Host machines System",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 },
   "collapsed": true,
   "panels": [
    {
     "title": "LA1",
     "type": "graph",
     "description": "Load Averages",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 15 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "node_load1{job=\"node_exporter kubernetes\",server_env=~\"$server_env\",node_name=~\"$node_name\"}",
       "legendFormat": "{{node_name}}"
      },
      {
       "expr": "max(instance:node_cpus:count{job=\"node_exporter kubernetes\",server_env=~\"$server_env\",node_name=~\"$node_name\"})",
       "legendFormat": "Max number of cores"
      }
     ]
    },
    {
     "title": "Uptime",
     "type": "graph",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 21 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "node_time_seconds{job=\"node_exporter kubernetes\",server_env=~\"$server_env\",node_name=~\"$node_name\",pod_name=~\"node-exporter.*\"} - node_boot_time_seconds",
       "legendFormat": "{{node_name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Host machines Memory",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 },
   "collapsed": true,
   "panels": [
    {
     "title": "Memory in use %",
     "type": "graph",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 16 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "(node_memory_MemTotal_bytes{job=\"node_exporter kubernetes\",server_env=~\"$server_env\",node_name=~\"$node_name\",pod_name=~\"node-exporter.*\"} - node_memory_MemAvailable_bytes) / node_memory_MemTotal_bytes",
       "legendFormat": "{{node_name}}"
      }
     ]
    },
    {
     "title": "Memory in use",
     "type": "graph",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 22 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "node_memory_MemTotal_bytes{job=\"node_exporter kubernetes\",server_env=~\"$server_env\",node_name=~\"$node_name\",pod_name=~\"node-exporter.*\"} - node_memory_MemAvailable_bytes",
       "legendFormat": "{{node_name}}"
      },
      {
       "expr": "max(node_memory_MemTotal_bytes{job=\"node_exporter kubernetes\",server_env=~\"$server_env\",node_name=~\"$node_name\",pod_name=~\"node-exporter.*\"})",
       "legendFormat": "Max memory"
      }
     ]
    },
    {
     "title": "Memory stack average",
     "type": "graph",
     "description": "Apps - Memory used by user-space applications\n\nPageTables - Memory used to map between virtual and physical memory addresses\n\nSwapCache - Memory that keeps track of pages that have been fetched from swap but not yet been modified\n\nSlab - Memory used by the kernel to cache data structures for its own use (caches like inode, dentry, etc)\n\nCache - Parked file data (file content) cache\n\nBuffers - Block device (e.g. harddisk) cache\n\nUnused - Free memory unasigned\n\nSwap - Swap space used\n\nHarware Corrupted - Amount of RAM that the kernel identified as corrupted / not working",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 28 },
     "yaxes": [
      { "format": "bytes", "label": "Bytes" }
     ],
     "targets": [
      {
       "expr": "avg(topk($limit, node_memory_MemTotal_bytes{job=\"node_exporter kubernetes\",server_env=~\"$server_env\",node_name=~\"$node_name\",pod_name=~\"node-exporter.*\"} - node_memory_MemFree_bytes - node_memory_Buffers_bytes - node_memory_Cached_bytes - node_memory_Slab_bytes - node_memory_PageTables_bytes - node_memory_SwapCached_bytes))",
       "legendFormat": "Apps"
      },
      {
       "expr": "avg(topk($limit, node_memory_PageTables_bytes{job=\"node_exporter kubernetes\",server_env=~\"$server_env\",node_name=~\"$node_name\",pod_name=~\"node-exporter.*\"}))",
       "legendFormat": "PageTables"
      },
      {
       "expr": "avg(topk($limit, node_memory_SwapCached_bytes{job=\"node_exporter kubernetes\",server_env=~\"$server_env\",node_name=~\"$node_name\",pod_name=~\"node-exporter.*\"}))",
       "legendFormat": "SwapCache"
      },
      {
       "expr": "avg(topk($limit, node_memory_Slab_bytes{job=\"node_exporter kubernetes\",server_env=~\"$server_env\",node_name=~\"$node_name\",pod_name=~\"node-exporter.*\"}))",
       "legendFormat": "Slab"
      },
      {
       "expr": "avg(topk($limit, node_memory_Cached_bytes{job=\"node_exporter kubernetes\",server_env=~\"$server_env\",node_name=~\"$node_name\",pod_name=~\"node-exporter.*\"}))",
       "legendFormat": "Cache"
      },
      {
       "expr": "avg(topk($limit, node_memory_Buffers_bytes{job=\"node_exporter kubernetes\",server_env=~\"$server_env\",node_name=~\"$node_name\",pod_name=~\"node-exporter.*\"}))",
       "legendFormat": "Buffers"
      },
      {
       "expr": "avg(topk($limit, node_memory_MemFree_bytes{job=\"node_exporter kubernetes\",server_env=~\"$server_env\",node_name=~\"$node_name\",pod_name=~\"node-exporter.*\"}))",
       "legendFormat": "Unused"
      },
      {
       "expr": "avg(topk($limit, node_memory_SwapTotal_bytes{job=\"node_exporter kubernetes\",server_env=~\"$server_env\",node_name=~\"$node_name\",pod_name=~\"node-exporter.*\"} - node_memory_SwapFree_bytes))",
       "legendFormat": "Swap"
      },
      {
       "expr": "avg(topk($limit, node_memory_HardwareCorrupted_bytes{job=\"node_exporter kubernetes\",server_env=~\"$server_env\",node_name=~\"$node_name\",pod_name=~\"node-exporter.*\"}))",
       "legendFormat": "Harware Corrupted"
      }
     ]
    }
   ]
  },
  {
   "title": "Host machines Network",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 },
   "collapsed": true,
   "panels": [
    {
     "title": "Network traffic",
     "type": "graph",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 17 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "irate(node_network_receive_bytes_total{job=\"node_exporter kubernetes\",server_env=~\"$server_env\",node_name=~\"$node_name\",pod_name=~\"node-exporter.*\"}[5m])",
       "legendFormat": "{{node_name}} {{device}} Receive"
      },
      {
       "expr": "irate(node_network_transmit_bytes_total{job=\"node_exporter kubernetes\",server_env=~\"$server_env\",node_name=~\"$node_name\",pod_name=~\"node-exporter.*\"}[5m])",
       "legendFormat": "{{node_name}} {{device}} Transmit"
      }
     ]
    },
    {
     "title": "Network packets",
     "type": "graph",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 23 },
     "yaxes": [
      { "format": "pps" }
     ],
     "targets": [
      {
       "expr": "irate(node_network_receive_packets_total{job=\"node_exporter kubernetes\",server_env=~\"$server_env\",node_name=~\"$node_name\",pod_name=~\"node-exporter.*\"}[5m])",
       "legendFormat": "{{node_name}} {{device}} Receive"
      },
      {
       "expr": "irate(node_network_transmit_packets_total{job=\"node_exporter kubernetes\",server_env=~\"$server_env\",node_name=~\"$node_name\",pod_name=~\"node-exporter.*\"}[5m])",
       "legendFormat": "{{node_name}} {{device}} Transmit"
      }
     ]
    }
   ]
  },
  {
   "title": "Host machines Disk",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 },
   "collapsed": true,
   "panels": [
    {
     "title": "Disk free %",
     "type": "graph",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 18 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "100 * ( node_filesystem_avail_bytes{job=\"node_exporter kubernetes\",mountpoint=\"/\",server_env=~\"$server_env\",node_name=~\"$node_name\",pod_name=~\"node-exporter.*\"} / (node_filesystem_size_bytes - ( node_filesystem_free_bytes - node_filesystem_avail_bytes)))",
       "legendFormat": "{{node_name}} - {{mountpoint}}"
      }
     ]
    },
    {
     "title": "Disk free",
     "type": "graph",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 24 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "node_filesystem_free_bytes{job=\"node_exporter kubernetes\",mountpoint=\"/\",server_env=~\"$server_env\",node_name=~\"$node_name\",pod_name=~\"node-exporter.*\"}",
       "legendFormat": "{{node_name}} - {{mountpoint}}"
      }
     ]
    },
    {
     "title": "Disk operations",
     "type": "graph",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 30 },
     "yaxes": [
      { "format": "iops", "label": "Bytes read (-) / write (+)" }
     ],
     "targets": [
      {
       "expr": "irate(node_disk_reads_completed_total{job=\"node_exporter kubernetes\",server_env=~\"$server_env\",node_name=~\"$node_name\",pod_name=~\"node-exporter.*\"}[5m])",
       "legendFormat": "{{node_name}} - {{device}} - Read"
      },
      {
       "expr": "irate(node_disk_writes_completed_total{job=\"node_exporter kubernetes\",server_env=~\"$server_env\",node_name=~\"$node_name\",pod_name=~\"node-exporter.*\"}[5m])",
       "legendFormat": "{{node_name}} - {{device}} - Write "
      }
     ]
    },
    {
     "title": "Disk bytes",
     "type": "graph",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 36 },
     "yaxes": [
      { "format": "Bps", "label": "Bytes read (-) / write (+)" }
     ],
     "targets": [
      {
       "expr": "irate(node_disk_read_bytes_total{job=\"node_exporter kubernetes\",server_env=~\"$server_env\",node_name=~\"$node_name\",pod_name=~\"node-exporter.*\"}[5m])",
       "legendFormat": "{{node_name}} - {{device}} - Read bytes"
      },
      {
       "expr": "irate(node_disk_written_bytes_total{job=\"node_exporter kubernetes\",server_env=~\"$server_env\",node_name=~\"$node_name\",pod_name=~\"node-exporter.*\"}[5m])",
       "legendFormat": "{{node_name}} - {{device}} - Write bytes"
      }
     ]
    }
   ]
  },
  {
   "title": "Core DNS metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 },
   "collapsed": true,
   "panels": [
    {
     "title": "Proxy requests duration sum",
     "type": "graph",
     "description": "Sum of all proxy requests time (in seconds)",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 19 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "rate(coredns_proxy_request_duration_seconds_count{server_env=~\"$server_env\"}[5m])",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Health requests duration sum",
     "type": "graph",
     "description": "Sum of all health requests time (in seconds)",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 25 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "rate(coredns_health_request_duration_seconds_count{server_env=~\"$server_env\"}[5m])",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "DNS requests duration sum",
     "type": "graph",
     "description": "Sum of all DNS requests time (in seconds)",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 31 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "rate(coredns_dns_request_duration_seconds_count{server_env=~\"$server_env\"}[5m])",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Panics number",
     "type": "graph",
     "description": "A metrics that counts the number of panics",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 37 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(coredns_panic_count_total{server_env=~\"$server_env\"}[5m])",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "DNS requests count",
     "type": "graph",
     "description": "Counter of DNS requests made per zone, protocol and family",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 43 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(coredns_dns_request_count_total{server_env=~\"$server_env\"}[5m])",
       "legendFormat": "{{instance}} - {{server}} - {{zone}}"
      }
     ]
    },
    {
     "title": "DNS response status codes count",
     "type": "graph",
     "description": "Counter of response status codes",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 49 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(coredns_dns_response_rcode_count_total{server_env=~\"$server_env\"}[5m])",
       "legendFormat": "{{instance}} -{{rcode}}- {{server}} - {{zone}}"
      }
     ]
    }
   ]
  }
 ]
}