{
 "title": "Kubernetes metrics",
 "tags": [
  "prometheus",
  "kubernetes"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   { "name": "data_source", "label": "Data source", "query": "prometheus" },
   { "name": "node_name", "label": "Node", "query": "label_values(node_load1,node)" },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": "label_values(container_cpu_usage_seconds_total{node=~\"$node_name\"},namespace)"
   },
   {
    "name": "service_name",
    "label": "Service",
    "query": "label_values(container_cpu_system_seconds_total{node=~\"$node_name\",namespace=~\"$namespace\"},pod_name)"
   },
   {
    "name": "pod_name",
    "label": "Pod",
    "query": "label_values(container_cpu_usage_seconds_total{node=~\"$node_name\",namespace=~\"$namespace\",pod_name=~\"$service_name.*\"},pod_name)"
   },
   {
    "name": "container_name",
    "label": "Container",
    "query": "label_values(container_cpu_usage_seconds_total{node=~\"$node_name\",container_name!~\"POD|^$\",namespace=~\"$namespace\",pod_name=~\"$service_name.*\",pod_name=~\"$pod_name\"},container_name)"
   },
   {
    "name": "service_name_http",
    "query": "label_values(probe_success{job=\"blackbox-exporter kubernetes services\"}, service_name)"
   },
   {
    "name": "limit",
    "query": "1,2,3,4,5,6,7,8,9,10,15,20,25,30,40,50,70,100,9999"
   }
  ]
 },
 "panels": [
  { "title": "Services resources usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Memory usage per service",
   "type": "graph",
   "description": "Total usage by all service's containers across all nodes in cluster",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "topk($limit, sum(label_replace(container_memory_rss{node=~\"$node_name\",pod_name=~\"$service_name.*\",namespace=~\"$namespace\",container_name!~\"^POD$|^$\"}, \"service_name\", \"$1\", \"pod_name\", \"(.*)-[0-9a-z]{4}.*\")) by (service_name))",
     "legendFormat": "{{service_name}}"
    }
   ]
  },
  {
   "title": "CPU time total per service",
   "type": "graph",
   "description": "Total usage by all service's containers across all nodes in cluster\n\nCPU time consumed in seconds",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk($limit, sum(label_replace(rate(container_cpu_usage_seconds_total{node=~\"$node_name\",pod_name=~\"$service_name.*\",namespace=~\"$namespace\",container_name!~\"^POD$|^$\"}[5m]), \"service_name\", \"$1\", \"pod_name\", \"(.*)-[0-9a-z]{4}.*\")) by (service_name))",
     "legendFormat": "{{service_name}}"
    }
   ]
  },
  {
   "title": "Services http checks",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 },
   "collapsed": true,
   "panels": [
    {
     "title": "Status (bottom $limit)",
     "type": "graph",
     "description": "1 is OK\n0 is Fail",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 2 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "bottomk($limit, probe_success{service_name=~\"$service_name_http\",job=\"blackbox-exporter kubernetes services\"})",
       "legendFormat": "{{instance}}{{request}}"
      }
     ]
    },
    {
     "title": "probe_http_status_code (top $limit)",
     "type": "graph",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 8 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "topk($limit, probe_http_status_code{service_name=~\"$service_name_http\",job=\"blackbox-exporter kubernetes services\"})",
       "legendFormat": "{{instance}}{{request}}"
      }
     ]
    },
    {
     "title": "probe_duration_seconds (top $limit)",
     "type": "graph",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 14 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "topk($limit, probe_duration_seconds{service_name=~\"$service_name_http\",job=\"blackbox-exporter kubernetes services\"})",
       "legendFormat": "{{instance}}{{request}}"
      }
     ]
    },
    {
     "title": "probe_http_duration_seconds (top $limit)",
     "type": "graph",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 20 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "topk($limit, probe_http_duration_seconds{service_name=~\"$service_name_http\",job=\"blackbox-exporter kubernetes services\"})",
       "legendFormat": "{{instance}}{{request}} - {{phase}}"
      }
     ]
    },
    {
     "title": "probe_http_content_length (bottom $limit)",
     "type": "graph",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 26 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "bottomk($limit, probe_http_content_length{service_name=~\"$service_name_http\",job=\"blackbox-exporter kubernetes services\"})",
       "legendFormat": "{{instance}}{{request}}"
      }
     ]
    },
    {
     "title": "Services count",
     "type": "graph",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 32 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "count(probe_success{service_name=~\"$service_name_http\",job=\"blackbox-exporter kubernetes services\"})",
       "legendFormat": "Count"
      }
     ]
    }
   ]
  },
  {
   "title": "Nodes state",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 },
   "collapsed": true,
   "panels": [
    {
     "title": "Nodes ready",
     "type": "graph",
     "description": "Ready = 1",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 3 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "kube_node_status_condition{node=~\"$node_name\",condition=\"Ready\",status=\"true\"}",
       "legendFormat": "{{node}}"
      }
     ]
    },
    {
     "title": "Nodes alert conditions top $limit",
     "type": "graph",
     "description": "Alert == 1",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 11 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "topk($limit, kube_node_status_condition{node=~\"$node_name\",condition!=\"Ready\",status=\"true\"})",
       "legendFormat": "{{node}} - {{condition}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Containers uptime",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 },
   "collapsed": true,
   "panels": [
    {
     "title": "Uptime (bottom $limit)",
     "type": "graph",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 16 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "bottomk($limit, container_last_seen{node=~\"$node_name\",pod_name=~\"$service_name.*\",namespace=~\"$namespace\",pod_name=~\"$pod_name\",container_name!~\"^POD$|^$\",container_name=~\"$container_name\"} - container_start_time_seconds)",
       "legendFormat": "{{pod_name}} - {{container_name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Containers status",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 },
   "collapsed": true,
   "panels": [
    {
     "title": "Containers Restarts number (top $limit)",
     "type": "graph",
     "description": "OK = 0",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 23 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "topk($limit, delta(kube_pod_container_status_restarts_total{namespace=~\"$namespace\",pod=~\"$pod_name\",container=~\"$container_name\"}[5m]))",
       "legendFormat": "{{pod}} - {{container}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Pods status",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "collapsed": true,
   "panels": [
    {
     "title": "Pods phase bottom $limit",
     "type": "graph",
     "description": "Pod phase:\nPending | Running | Succeeded | Failed | Unknown\n\nIf value is 1, then this phase is active",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 12 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "bottomk($limit, kube_pod_status_phase{namespace=~\"$namespace\",pod=~\"$service_name.*\",pod=~\"$pod_name\"})",
       "legendFormat": "{{pod}} - {{phase}}"
      }
     ]
    },
    {
     "title": "Pods condition Ready (top $limit)",
     "type": "graph",
     "description": "Pod ready conditions:\n\ntrue | false | unknown\n\nIf value is 1, then this phase is active",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 18 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "topk($limit, kube_pod_status_ready{namespace=~\"$namespace\",pod=~\"$service_name.*\",pod=~\"$pod_name\"})",
       "legendFormat": "{{pod}} - {{condition}}"
      }
     ]
    },
    {
     "title": "Pods condition \"Scheduled\" (top $limit)",
     "type": "graph",
     "description": "Pod Scheduled conditions:\n\ntrue | false | unknown\n\nIf value is 1, then this phase is active",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 24 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "topk($limit, kube_pod_status_scheduled{namespace=~\"$namespace\",pod=~\"$service_name.*\",pod=~\"$pod_name\"})",
       "legendFormat": "{{pod}} - {{condition}}"
      }
     ]
    },
    {
     "title": "Pods condition \"Containers Ready\" bottom $limit",
     "type": "graph",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 30 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "bottomk($limit, kube_pod_container_status_ready{namespace=~\"$namespace\",pod=~\"$service_name.*\",pod=~\"$pod_name\"})",
       "legendFormat": "{{pod}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Pods usage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "collapsed": true,
   "panels": [
    {
     "title": "Pods usage",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 31 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "(count(kube_pod_info{node=~\"$node_name\"}) by (node)) / (max(kube_node_status_capacity{resource=\"pods\"}) by (node)) * 100",
       "legendFormat": "{{node}}"
      }
     ]
    },
    {
     "title": "Pods available",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 39 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "(max(kube_node_status_capacity{node=~\"$node_name\",resource=\"pods\"}) by (node)) - (count(kube_pod_info{node=~\"$node_name\"}) by (node))",
       "legendFormat": "{{node}}"
      },
      {
       "expr": "max(kube_node_status_capacity{node=~\"$node_name\",resource=\"pods\"})",
       "legendFormat": "Node capacity"
      }
     ]
    }
   ]
  },
  {
   "title": "Exporters status",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 },
   "collapsed": true,
   "panels": [
    {
     "title": "Node exporter status",
     "type": "graph",
     "description": "Ok = 1",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 48 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "up{job=\"node-exporter\",node=~\"$node_name\"}",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Node exporter scrape status (bottom $limit)",
     "type": "graph",
     "description": "Ok = 1",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 54 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "bottomk($limit, node_scrape_collector_success{job=\"node-exporter\",node=~\"$node_name\"})",
       "legendFormat": "{{pod}} {{collector}}"
      }
     ]
    }
   ]
  },
  {
   "title": "API metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 },
   "collapsed": true,
   "panels": [
    {
     "title": "API requests count all",
     "type": "graph",
     "description": "Counter of apiserver requests broken out for each verb, API resource, client, and HTTP response contentType and code",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 61 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(apiserver_request_count[5m]))",
       "legendFormat": "all sum"
      }
     ]
    },
    {
     "title": "API requests count top $limit",
     "type": "graph",
     "description": "Counter of apiserver requests broken out for each verb, API resource, client, and HTTP response contentType and code",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 67 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "topk($limit, rate(apiserver_request_count[5m]))",
       "legendFormat": "{{instance}} - {{resource}} - {{verb}} - {{code}}"
      }
     ]
    },
    {
     "title": "Depths of workqueues",
     "type": "graph",
     "description": "Current depth of workqueues",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 73 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "APIServiceOpenAPIAggregationControllerQueue1_depth",
       "legendFormat": "{{instance}} APIServiceOpenAPIAggregationControllerQueue1_depth"
      },
      {
       "expr": "APIServiceRegistrationController_depth",
       "legendFormat": "{{instance}} APIServiceRegistrationController_depth"
      },
      {
       "expr": "AvailableConditionController_depth",
       "legendFormat": "{{instance}} AvailableConditionController_depth"
      },
      {
       "expr": "DiscoveryController_depth",
       "legendFormat": "{{instance}} DiscoveryController_depth"
      },
      {
       "expr": "admission_quota_controller_depth",
       "legendFormat": "{{instance}} admission_quota_controller_depth"
      },
      {
       "expr": "autoregister_depth",
       "legendFormat": "{{instance}} autoregister_depth"
      },
      {
       "expr": "crdEstablishing_depth",
       "legendFormat": "{{instance}} crdEstablishing_depth"
      }
     ]
    },
    {
     "title": "Adds to workqueues rate",
     "type": "graph",
     "description": "Current adds to workqueues",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 79 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(APIServiceOpenAPIAggregationControllerQueue1_adds[5m])",
       "legendFormat": "{{instance}} APIServiceOpenAPIAggregationControllerQueue1_depth"
      },
      {
       "expr": "rate(APIServiceRegistrationController_adds[5m])",
       "legendFormat": "{{instance}} APIServiceRegistrationController_depth"
      },
      {
       "expr": "rate(AvailableConditionController_adds{server_env=~\"$server_env\"}[5m])",
       "legendFormat": "{{instance}} AvailableConditionController_depth"
      },
      {
       "expr": "rate(DiscoveryController_adds{server_env=~\"$server_env\"}[5m])",
       "legendFormat": "{{instance}} DiscoveryController_depth"
      },
      {
       "expr": "rate(admission_quota_controller_adds{server_env=~\"$server_env\"}[5m])",
       "legendFormat": "{{instance}} admission_quota_controller_depth"
      },
      {
       "expr": "rate(autoregister_adds{server_env=~\"$server_env\"}[5m])",
       "legendFormat": "{{instance}} autoregister_depth"
      },
      {
       "expr": "rate(crdEstablishing_adds{server_env=~\"$server_env\"}[5m])",
       "legendFormat": "{{instance}} crdEstablishing_depth"
      }
     ]
    },
    {
     "title": "Failed token requests",
     "type": "graph",
     "description": "Counter of failed Token() requests to the alternate token source",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 85 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      { "expr": "rate(get_token_fail_count[5m])", "legendFormat": "{{instance}}" }
     ]
    },
    {
     "title": "Get token requests",
     "type": "graph",
     "description": "Counter of total Token() requests to the alternate token source",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 91 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      { "expr": "rate(get_token_count[5m])", "legendFormat": "{{instance}}" }
     ]
    },
    {
     "title": "Etcd objects count top $limit",
     "type": "graph",
     "description": "Number of stored objects at the time of last check split by kind",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 97 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "topk($limit, rate(etcd_object_counts[5m]))",
       "legendFormat": "{{instance}} - {{resource}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Containers CPU",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU time total",
     "type": "graph",
     "description": "CPU time consumed in seconds",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 62 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "topk($limit, rate(container_cpu_usage_seconds_total{node=~\"$node_name\",service=\"prometheus-operator-kubelet\",pod_name=~\"$service_name.*\",namespace=~\"$namespace\",pod_name=~\"$pod_name\",container_name!~\"^POD$|^$\",container_name=~\"$container_name\"}[5m]))",
       "legendFormat": "{{pod_name}} - {{container_name}}"
      }
     ]
    },
    {
     "title": "CPU time system",
     "type": "graph",
     "description": "CPU time consumed in seconds",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 68 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "topk($limit, rate(container_cpu_system_seconds_total{node=~\"$node_name\",service=\"prometheus-operator-kubelet\",pod_name=~\"$service_name.*\",namespace=~\"$namespace\",pod_name=~\"$pod_name\",container_name!~\"^POD$|^$\",container_name=~\"$container_name\"}[5m]))",
       "legendFormat": "{{pod_name}} - {{container_name}}"
      }
     ]
    },
    {
     "title": "CPU time user",
     "type": "graph",
     "description": "CPU time consumed in seconds",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 74 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "topk($limit, rate(container_cpu_user_seconds_total{node=~\"$node_name\",service=\"prometheus-operator-kubelet\",pod_name=~\"$service_name.*\",namespace=~\"$namespace\",pod_name=~\"$pod_name\",container_name!~\"^POD$|^$\",container_name=~\"$container_name\"}[5m]))",
       "legendFormat": "{{pod_name}} - {{container_name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Containers Memory",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 },
   "collapsed": true,
   "panels": [
    {
     "title": "Containers memory usage (top $limit)",
     "type": "graph",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 12 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "topk($limit, container_memory_rss{node=~\"$node_name\",service=\"prometheus-operator-kubelet\",pod_name=~\"$service_name.*\",namespace=~\"$namespace\",pod_name=~\"$pod_name\",container_name!~\"^POD$|^$\",container_name=~\"$container_name\"})",
       "legendFormat": "{{pod_name}} - {{container_name}}"
      },
      {
       "expr": "max(container_spec_memory_limit_bytes{node=~\"$node_name\",pod_name=~\"$service_name.*\",namespace=~\"$namespace\",pod_name=~\"$pod_name\",container_name!~\"^POD$|^$\",container_name=~\"$container_name\"})",
       "legendFormat": "Max Limit"
      }
     ]
    },
    {
     "title": "Containers memory usage % (top $limit)",
     "type": "graph",
     "description": "100% = limit",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 18 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "topk($limit, (container_memory_rss{node=~\"$node_name\",service=\"prometheus-operator-kubelet\",pod_name=~\"$service_name.*\",namespace=~\"$namespace\",pod_name=~\"$pod_name\",container_name!~\"^POD$|^$\",container_name=~\"$container_name\"} / (container_spec_memory_limit_bytes - 1) * 100) > 0)",
       "legendFormat": "{{pod_name}} - {{container_name}}"
      }
     ]
    },
    {
     "title": "container_memory_failures_total (top $limit)",
     "type": "graph",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 24 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "topk($limit, rate(container_memory_failures_total{node=~\"$node_name\",service=\"prometheus-operator-kubelet\",pod_name=~\"$service_name.*\",namespace=~\"$namespace\",pod_name=~\"$pod_name\",container_name!~\"^POD$|^$\",container_name=~\"$container_name\"}[5m]))",
       "legendFormat": "{{pod_name}} - {{container_name}} - {{type}} - {{scope}}"
      }
     ]
    },
    {
     "title": "container_memory_failcnt (top $limit)",
     "type": "graph",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 30 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "topk($limit, rate(container_memory_failcnt{node=~\"$node_name\",service=\"prometheus-operator-kubelet\",pod_name=~\"$service_name.*\",namespace=~\"$namespace\",pod_name=~\"$pod_name\",container_name!~\"^POD$|^$\",container_name=~\"$container_name\"}[5m]))",
       "legendFormat": "{{pod_name}} - {{container_name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Host machines CPU",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU in use",
     "type": "graph",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 13 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "topk($limit, 1 - sum(irate(node_cpu_seconds_total{job=\"node-exporter\",mode=\"idle\",node=~\"$node_name\"}[5m])) without (cpu,mode) / count(node_cpu_seconds_total{mode=\"idle\"}) without (cpu,mode))",
       "legendFormat": "{{node}}"
      }
     ]
    },
    {
     "title": "CPU stack  average",
     "type": "graph",
     "description": "System - Processes executing in kernel mode\n\nUser - Normal processes executing in user mode\n\nNice - Niced processes executing in user mode\n\nIdle - Waiting for something to happen\n\nIowait - Waiting for I/O to complete\n\nIrq - Servicing interrupts\n\nSoftirq - Servicing softirqs\n\nSteal - Time spent in other operating systems when running in a virtualized environment\n\nGuest - Time spent running a virtual CPU for a guest operating system",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 19 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "avg(topk($limit, sum(irate(node_cpu_seconds_total{job=\"node-exporter\",mode=\"system\",node=~\"$node_name\"}[5m])) without (cpu,mode) / count(node_cpu_seconds_total{mode=\"system\"}) without (cpu,mode)))",
       "legendFormat": "System"
      },
      {
       "expr": "avg(topk($limit, sum(irate(node_cpu_seconds_total{job=\"node-exporter\",mode=\"user\",node=~\"$node_name\"}[5m])) without (cpu,mode) / count(node_cpu_seconds_total{mode=\"user\"}) without (cpu,mode)))",
       "legendFormat": "User"
      },
      {
       "expr": "avg(topk($limit, sum(irate(node_cpu_seconds_total{job=\"node-exporter\",mode=\"nice\",node=~\"$node_name\"}[5m])) without (cpu,mode) / count(node_cpu_seconds_total{mode=\"nice\"}) without (cpu,mode)))",
       "legendFormat": "Nice"
      },
      {
       "expr": "avg(topk($limit, sum(irate(node_cpu_seconds_total{job=\"node-exporter\",mode=\"idle\",node=~\"$node_name\"}[5m])) without (cpu,mode) / count(node_cpu_seconds_total{mode=\"idle\"}) without (cpu,mode)))",
       "legendFormat": "Idle"
      },
      {
       "expr": "avg(topk($limit, sum(irate(node_cpu_seconds_total{job=\"node-exporter\",mode=\"iowait\",node=~\"$node_name\"}[5m])) without (cpu,mode) / count(node_cpu_seconds_total{mode=\"iowait\"}) without (cpu,mode)))",
       "legendFormat": "Iowait"
      },
      {
       "expr": "avg(topk($limit, sum(irate(node_cpu_seconds_total{job=\"node-exporter\",mode=\"irq\",node=~\"$node_name\"}[5m])) without (cpu,mode) / count(node_cpu_seconds_total{mode=\"irq\"}) without (cpu,mode)))",
       "legendFormat": "Irq"
      },
      {
       "expr": "avg(topk($limit, sum(irate(node_cpu_seconds_total{job=\"node-exporter\",mode=\"softirq\",node=~\"$node_name\"}[5m])) without (cpu,mode) / count(node_cpu_seconds_total{mode=\"softirq\"}) without (cpu,mode)))",
       "legendFormat": "Softirq"
      },
      {
       "expr": "avg(topk($limit, sum(irate(node_cpu_seconds_total{job=\"node-exporter\",mode=\"steal\",node=~\"$node_name\"}[5m])) without (cpu,mode) / count(node_cpu_seconds_total{mode=\"steal\"}) without (cpu,mode)))",
       "legendFormat": "Steal"
      },
      {
       "expr": "avg(topk($limit, sum(irate(node_cpu_seconds_total{job=\"node-exporter\",mode=\"guest\",node=~\"$node_name\"}[5m])) without (cpu,mode) / count(node_cpu_seconds_total{mode=\"guest\"}) without (cpu,mode)))",
       "legendFormat": "Guest"
      }
     ]
    }
   ]
  },
  {
   "title": "Host machines System",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 },
   "collapsed": true,
   "panels": [
    {
     "title": "LA1",
     "type": "graph",
     "description": "Load Averages",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 14 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "node_load1{job=\"node-exporter\",node=~\"$node_name\"}",
       "legendFormat": "{{node}}"
      },
      {
       "expr": "max(count(node_cpu_seconds_total{mode=\"system\",job=\"node-exporter\",node=~\"$node_name\"}) without (cpu,mode))",
       "legendFormat": "Max number of cores"
      }
     ]
    },
    {
     "title": "Uptime",
     "type": "graph",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 20 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "node_time_seconds{job=\"node-exporter\",node=~\"$node_name\"} - node_boot_time_seconds",
       "legendFormat": "{{node}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Host machines Memory",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 },
   "collapsed": true,
   "panels": [
    {
     "title": "Memory in use %",
     "type": "graph",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 15 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "(node_memory_MemTotal_bytes{job=\"node-exporter\",node=~\"$node_name\"} - node_memory_MemAvailable_bytes) / node_memory_MemTotal_bytes",
       "legendFormat": "{{node}}"
      }
     ]
    },
    {
     "title": "Memory in use",
     "type": "graph",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 21 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "node_memory_MemTotal_bytes{job=\"node-exporter\",node=~\"$node_name\"} - node_memory_MemAvailable_bytes",
       "legendFormat": "{{node}}"
      },
      {
       "expr": "max(node_memory_MemTotal_bytes{job=\"node-exporter\",node=~\"$node_name\"})",
       "legendFormat": "Max memory"
      }
     ]
    },
    {
     "title": "Memory stack average",
     "type": "graph",
     "description": "Apps - Memory used by user-space applications\n\nPageTables - Memory used to map between virtual and physical memory addresses\n\nSwapCache - Memory that keeps track of pages that have been fetched from swap but not yet been modified\n\nSlab - Memory used by the kernel to cache data structures for its own use (caches like inode, dentry, etc)\n\nCache - Parked file data (file content) cache\n\nBuffers - Block device (e.g. harddisk) cache\n\nUnused - Free memory unasigned\n\nSwap - Swap space used\n\nHarware Corrupted - Amount of RAM that the kernel identified as corrupted / not working",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 27 },
     "yaxes": [
      { "format": "bytes", "label": "Bytes" }
     ],
     "targets": [
      {
       "expr": "avg(topk($limit, node_memory_MemTotal_bytes{job=\"node-exporter\",node=~\"$node_name\"} - node_memory_MemFree_bytes - node_memory_Buffers_bytes - node_memory_Cached_bytes - node_memory_Slab_bytes - node_memory_PageTables_bytes - node_memory_SwapCached_bytes))",
       "legendFormat": "Apps"
      },
      {
       "expr": "avg(topk($limit, node_memory_PageTables_bytes{job=\"node-exporter\",node=~\"$node_name\"}))",
       "legendFormat": "PageTables"
      },
      {
       "expr": "avg(topk($limit, node_memory_SwapCached_bytes{job=\"node-exporter\",node=~\"$node_name\"}))",
       "legendFormat": "SwapCache"
      },
      {
       "expr": "avg(topk($limit, node_memory_Slab_bytes{job=\"node-exporter\",node=~\"$node_name\"}))",
       "legendFormat": "Slab"
      },
      {
       "expr": "avg(topk($limit, node_memory_Cached_bytes{job=\"node-exporter\",node=~\"$node_name\"}))",
       "legendFormat": "Cache"
      },
      {
       "expr": "avg(topk($limit, node_memory_Buffers_bytes{job=\"node-exporter\",node=~\"$node_name\"}))",
       "legendFormat": "Buffers"
      },
      {
       "expr": "avg(topk($limit, node_memory_MemFree_bytes{job=\"node-exporter\",node=~\"$node_name\"}))",
       "legendFormat": "Unused"
      },
      {
       "expr": "avg(topk($limit, node_memory_SwapTotal_bytes{job=\"node-exporter\",node=~\"$node_name\"} - node_memory_SwapFree_bytes))",
       "legendFormat": "Swap"
      },
      {
       "expr": "avg(topk($limit, node_memory_HardwareCorrupted_bytes{job=\"node-exporter\",node=~\"$node_name\"}))",
       "legendFormat": "Harware Corrupted"
      }
     ]
    }
   ]
  },
  {
   "title": "Host machines Network",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 },
   "collapsed": true,
   "panels": [
    {
     "title": "Network traffic",
     "type": "graph",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 16 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "irate(node_network_receive_bytes_total{job=\"node-exporter\",node=~\"$node_name\"}[5m])",
       "legendFormat": "{{node}} {{device}} Receive"
      },
      {
       "expr": "irate(node_network_transmit_bytes_total{job=\"node-exporter\",node=~\"$node_name\"}[5m])",
       "legendFormat": "{{node}} {{device}} Transmit"
      }
     ]
    },
    {
     "title": "Network packets",
     "type": "graph",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 22 },
     "yaxes": [
      { "format": "pps" }
     ],
     "targets": [
      {
       "expr": "irate(node_network_receive_packets_total{job=\"node-exporter\",node=~\"$node_name\"}[5m])",
       "legendFormat": "{{node}} {{device}} Receive"
      },
      {
       "expr": "irate(node_network_transmit_packets_total{job=\"node-exporter\",node=~\"$node_name\"}[5m])",
       "legendFormat": "{{node}} {{device}} Transmit"
      }
     ]
    }
   ]
  },
  {
   "title": "Host machines Disk",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 },
   "collapsed": true,
   "panels": [
    {
     "title": "Disk free %",
     "type": "graph",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 17 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "100 * ( node_filesystem_avail_bytes{job=\"node-exporter\",node=~\"$node_name\"} / (node_filesystem_size_bytes - ( node_filesystem_free_bytes - node_filesystem_avail_bytes)))",
       "legendFormat": "{{node}} - {{mountpoint}}"
      }
     ]
    },
    {
     "title": "Disk free",
     "type": "graph",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 23 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "node_filesystem_free_bytes{job=\"node-exporter\",node=~\"$node_name\"}",
       "legendFormat": "{{node}} - {{mountpoint}}"
      }
     ]
    },
    {
     "title": "Disk operations",
     "type": "graph",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 29 },
     "yaxes": [
      { "format": "iops", "label": "Bytes read (-) / write (+)" }
     ],
     "targets": [
      {
       "expr": "irate(node_disk_reads_completed_total{job=\"node-exporter\",node=~\"$node_name\"}[5m])",
       "legendFormat": "{{node}} - {{device}} - Read"
      },
      {
       "expr": "irate(node_disk_writes_completed_total{job=\"node-exporter\",node=~\"$node_name\"}[5m])",
       "legendFormat": "{{node}} - {{device}} - Write "
      }
     ]
    },
    {
     "title": "Disk bytes",
     "type": "graph",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 35 },
     "yaxes": [
      { "format": "Bps", "label": "Bytes read (-) / write (+)" }
     ],
     "targets": [
      {
       "expr": "irate(node_disk_read_bytes_total{job=\"node-exporter\",node=~\"$node_name\"}[5m])",
       "legendFormat": "{{node}} - {{device}} - Read bytes"
      },
      {
       "expr": "irate(node_disk_written_bytes_total{job=\"node-exporter\",node=~\"$node_name\"}[5m])",
       "legendFormat": "{{node}} - {{device}} - Write bytes"
      }
     ]
    }
   ]
  }
 ]
}