{
 "title": "MongoDB (mongodb_exporter)",
 "description": "MongoDB Prometheus Exporter Dashboard. \r\nWorks well with https://github.com/dcu/mongodb_exporter\r\n\r\nIf you have the node_exporter running on the mongo instance, you will also get some useful alert panels related to disk io and cpu.",
 "tags": [ "prometheus" ],
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   { "name": "data_source", "label": "Data source", "query": "prometheus" },
   {
    "name": "project",
    "label": "Project",
    "query": "label_values(mongodb_connections,project)"
   },
   {
    "name": "hostname",
    "label": "Hostname",
    "query": "label_values(mongodb_connections{project=~\"$project\"}, hostname)"
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": "label_values(mongodb_connections{project=~\"$project\",hostname=~\"$hostname\"}, instance)"
   },
   {
    "name": "interval",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   {
    "name": "limit",
    "query": "1,2,3,4,5,6,7,8,9,10,15,20,25,30,40,50,70,100,9999"
   }
  ]
 },
 "panels": [
  {
   "title": "Exporter status",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Mongodb exporter status",
     "type": "graph",
     "description": "1 = OK",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 1 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "topk($limit, up{instance=~\".*:9001\",project=~\"$project\",hostname=~\"$hostname\",instance=~\"$instance\"})",
       "legendFormat": "{{hostname}} - {{instance}}"
      }
     ]
    },
    {
     "title": "Mongodb scrape status",
     "type": "graph",
     "description": "Fail if < 10k",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 7 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "topk($limit, delta(http_response_size_bytes_sum{instance=~\".*:9001\"}[1m]))",
       "legendFormat": "{{hostname}} - {{instance}}"
      }
     ]
    }
   ]
  },
  { "title": "Query Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 }, "repeat": "env" },
  {
   "title": "Query Operations",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 2 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "rate(mongodb_op_counters_total{project=~\"$project\",hostname=~\"$hostname\",instance=~\"$instance\"}[$interval])",
     "legendFormat": "{{hostname}} {{type}}"
    }
   ]
  },
  {
   "title": "Document Operations",
   "type": "graph",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(mongodb_metrics_document_total{project=~\"$project\",hostname=~\"$hostname\",instance=~\"$instance\"}[$interval])",
     "legendFormat": "{{hostname}} {{state}}"
    }
   ]
  },
  {
   "title": "Document Query Executor",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(mongodb_metrics_query_executor_total{project=~\"$project\",hostname=~\"$hostname\",instance=~\"$instance\"}[$interval])",
     "legendFormat": "{{hostname}} {{state}}"
    }
   ]
  },
  {
   "title": "Replica Set Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 },
   "repeat": "env",
   "collapsed": true,
   "panels": [
    {
     "title": "Oplog Lag",
     "type": "graph",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 3 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "rate(mongodb_replset_oplog_head_timestamp{project=~\"$project\",hostname=~\"$hostname\",instance=~\"$instance\"}[5m])",
       "legendFormat": "{{hostname}}"
      }
     ]
    },
    {
     "title": "Replicatoin Lag",
     "type": "graph",
     "description": "https://docs.mongodb.com/manual/reference/command/replSetGetStatus/#replSetGetStatus.members[n].optimeDate\n\nhttps://docs.mongodb.com/manual/tutorial/troubleshoot-replica-sets/#check-the-replication-lag",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 8 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "abs(max without(name, state) (mongodb_replset_member_optime_date{state=\"PRIMARY\"}) - min without(name, state) (mongodb_replset_member_optime_date{state=\"SECONDARY\"}))",
       "legendFormat": "{{hostname}}"
      }
     ]
    },
    {
     "title": "Member Health",
     "type": "graph",
     "gridPos": { "h": 5, "w": 10, "x": 0, "y": 13 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "mongodb_replset_number_of_members{project=~\"$project\",hostname=~\"$hostname\",instance=~\"$instance\"}",
       "legendFormat": "{{hostname}} # members"
      },
      {
       "expr": "sum(mongodb_replset_member_health{instance=~\"$env\"})",
       "legendFormat": "healthy members"
      }
     ]
    },
    {
     "title": "Member State",
     "type": "graph",
     "description": "See which node is currently acting as the primary, secondary, ...",
     "gridPos": { "h": 5, "w": 14, "x": 10, "y": 13 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "mongodb_replset_member_state{project=~\"$project\",hostname=~\"$hostname\",instance=~\"$instance\"}",
       "legendFormat": "{{hostname}} {{state}} - {{name}}"
      }
     ]
    },
    {
     "title": "Replica Query Operations",
     "type": "graph",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 18 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "rate(mongodb_op_counters_repl_total{project=~\"$project\",hostname=~\"$hostname\",instance=~\"$instance\"}[$interval])",
       "legendFormat": "{{hostname}} {{type}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Health metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "repeat": "env",
   "collapsed": true,
   "panels": [
    {
     "title": "Uptime",
     "type": "graph",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 18 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "mongodb_instance_uptime_seconds{project=~\"$project\",hostname=~\"$hostname\",instance=~\"$instance\"}",
       "legendFormat": "{{hostname}}"
      }
     ]
    },
    {
     "title": "Available Connections",
     "type": "graph",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 23 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "mongodb_connections{project=~\"$project\",hostname=~\"$hostname\",instance=~\"$instance\",state=\"available\"}",
       "legendFormat": "{{hostname}}"
      }
     ]
    },
    {
     "title": "Open Connections",
     "type": "graph",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 28 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "mongodb_connections{project=~\"$project\",hostname=~\"$hostname\",instance=~\"$instance\",state=\"current\"}",
       "legendFormat": "{{hostname}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Resource Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "collapsed": true,
   "panels": [
    {
     "title": "Oplog Size",
     "type": "graph",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 34 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "mongodb_replset_oplog_size_bytes{project=~\"$project\",hostname=~\"$hostname\",instance=~\"$instance\"}",
       "legendFormat": "{{hostname}} {{type}}"
      }
     ]
    },
    {
     "title": "Memory",
     "type": "graph",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 39 },
     "yaxes": [
      { "format": "decmbytes", "label": "MB" }
     ],
     "targets": [
      {
       "expr": "mongodb_memory{project=~\"$project\",hostname=~\"$hostname\",instance=~\"$instance\",type=~\"resident|virtual\"}",
       "legendFormat": "{{hostname}} {{type}}"
      }
     ]
    },
    {
     "title": "Network I/O",
     "type": "graph",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 44 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "rate(mongodb_network_bytes_total{project=~\"$project\",hostname=~\"$hostname\",instance=~\"$instance\"}[$interval])",
       "legendFormat": "{{hostname}} {{state}}"
      }
     ]
    }
   ]
  }
 ]
}