{
 "title": "Monit exporter",
 "description": "Show monit stats as collector host",
 "tags": [ "monit" ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "job",
    "label": "Job",
    "query": "label_values(node_monit{key=\"status\",type=\"system\"}, job)"
   },
   {
    "name": "node",
    "label": "Host:",
    "query": "label_values(node_monit{key=\"status\",type=\"system\",job=~\"$job\"}, instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "Status per service",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_monit{instance=\"$node\",key=\"status\"} > 0",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Uptime per service",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "dtdurations" }
   ],
   "targets": [
    {
     "expr": "node_monit{instance=\"$node\",key=\"uptime\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Port response time per service (Seconds)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "node_monit{instance=\"$node\",key=\"port_responsetime\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Load (LA)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_monit{instance=\"$node\",key=\"system_load_avg01\"}",
     "legendFormat": "LA 1"
    },
    {
     "expr": "node_monit{instance=\"$node\",key=\"system_load_avg05\"}",
     "legendFormat": "LA 5"
    },
    {
     "expr": "node_monit{instance=\"$node\",key=\"system_load_avg15\"}",
     "legendFormat": "LA 15"
    }
   ]
  },
  {
   "title": "Cpu total usage (Percent)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "node_monit{instance=\"$node\",key=\"system_cpu_system\"}",
     "legendFormat": "system usage"
    },
    {
     "expr": "node_monit{instance=\"$node\",key=\"system_cpu_user\"}",
     "legendFormat": "user usage"
    },
    {
     "expr": "node_monit{instance=\"$node\",key=\"system_cpu_wait\"}",
     "legendFormat": "I/O wait"
    }
   ]
  },
  {
   "title": "Cpu usage per service (Percent)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "node_monit{instance=\"$node\",key=\"cpu_percenttotal\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Memory total usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "node_monit{instance=\"$node\",key=\"system_memory_percent\"}",
     "legendFormat": "memory usage"
    },
    {
     "expr": "node_monit{instance=\"$node\",key=\"system_swap_percent\"}",
     "legendFormat": "swap usage"
    }
   ]
  },
  {
   "title": "Memory usage per service",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 27 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "node_monit{instance=\"$node\",key=\"memory_percenttotal\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Threads number per service",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_monit{instance=\"$node\",key=\"threads\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Childrens number per service",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 36 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_monit{instance=\"$node\",key=\"children\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Read / Write operations/sec per disk",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 45 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_monit{instance=\"$node\",key=\"read_operations_count\",type=\"filesystem\"} * -1",
     "legendFormat": "{{name}} Read"
    },
    {
     "expr": "node_monit{instance=\"$node\",key=\"write_operations_count\",type=\"filesystem\"}",
     "legendFormat": "{{name}} Write"
    }
   ]
  },
  {
   "title": "Read / Write bytes/sec per disk",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 45 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "node_monit{instance=\"$node\",key=\"read_bytes_count\",type=\"filesystem\"} * -1",
     "legendFormat": "{{name}} Read"
    },
    {
     "expr": "node_monit{instance=\"$node\",key=\"write_bytes_count\",type=\"filesystem\"}",
     "legendFormat": "{{name}} Write"
    }
   ]
  },
  {
   "title": "Network Download / Upload packets per interface",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 54 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_monit{instance=\"$node\",key=\"link_download_packets_now\"} * -1",
     "legendFormat": "{{name}} Download"
    },
    {
     "expr": "node_monit{instance=\"$node\",key=\"link_upload_packets_now\"}",
     "legendFormat": "{{name}} Upload"
    }
   ]
  },
  {
   "title": "Network Download / Upload bytes per interface",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 54 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "node_monit{instance=\"$node\",key=\"link_download_bytes_now\"} * -1",
     "legendFormat": "{{name}} Download"
    },
    {
     "expr": "node_monit{instance=\"$node\",key=\"link_upload_bytes_now\"}",
     "legendFormat": "{{name}} Upload"
    }
   ]
  },
  {
   "title": "Disk usage per disk",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 63 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "node_monit{instance=\"$node\",key=\"block_percent\"}",
     "legendFormat": "{{name}} Data"
    },
    {
     "expr": "node_monit{instance=\"$node\",key=\"inode_percent\"}",
     "legendFormat": "{{name}} Inodes"
    }
   ]
  },
  {
   "title": "Network Download / Upload errors per interface",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 63 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_monit{instance=\"$node\",key=\"link_download_errors_now\"} * -1",
     "legendFormat": "{{name}} Download"
    },
    {
     "expr": "node_monit{instance=\"$node\",key=\"link_upload_errors_now\"}",
     "legendFormat": "{{name}} Upload"
    }
   ]
  }
 ]
}