{
 "title": "Monit exporter",
 "description": "Show monit stats as collector host",
 "tags": [ "monit" ],
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "server_env",
    "label": "Environment",
    "query": "label_values(prometheus_config_last_reload_successful, server_env)"
   },
   { "name": "data_source", "label": "Data source", "query": "prometheus" },
   {
    "name": "project",
    "label": "Project",
    "query": "label_values(node_monit{key=\"status\",type=\"system\",server_env=~\"$server_env\"},project)"
   },
   {
    "name": "hostname",
    "label": "Host:",
    "query": "label_values(node_monit{key=\"status\",type=\"system\",server_env=~\"$server_env\"}, hostname)"
   },
   {
    "name": "mountpoint",
    "label": "Mount point",
    "query": "label_values(node_monit{hostname=~\"$hostname\",project=~\"$project\",server_env=~\"$server_env\",key=\"block_percent\"},name)"
   },
   {
    "name": "limit",
    "query": "1,2,3,4,5,6,7,8,9,10,15,20,30,40,60,80,100,9999"
   }
  ]
 },
 "panels": [
  { "title": "Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Status per service (top $limit)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk($limit, max_over_time(node_monit{server_env=~\"$server_env\",hostname=~\"$hostname\",project=~\"$project\",key=\"status\"}[$__interval]))",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Number of checks (bottom $limit)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "bottomk($limit, count(node_monit{server_env=~\"$server_env\",hostname=~\"$hostname\",project=~\"$project\",key=\"status\"}) by (hostname))",
     "legendFormat": "Count {{hostname}}"
    }
   ]
  },
  {
   "title": "Uptime per service (bottom $limit)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "dtdurations" }
   ],
   "targets": [
    {
     "expr": "bottomk($limit, node_monit{server_env=~\"$server_env\",hostname=~\"$hostname\",project=~\"$project\",key=\"uptime\"})",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Load",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 },
   "collapsed": true,
   "panels": [
    {
     "title": "Load - LA (top $limit)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 2 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "topk($limit, node_monit{server_env=~\"$server_env\",hostname=~\"$hostname\",project=~\"$project\",key=\"system_load_avg01\"})",
       "legendFormat": "LA 1 {{hostname}}"
      },
      {
       "expr": "max(instance:node_cpus:count{server_env=~\"$server_env\",hostname=~\"$hostname\",project=~\"$project\"})",
       "legendFormat": "Max number of cores"
      }
     ]
    }
   ]
  },
  {
   "title": "Response time",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 },
   "collapsed": true,
   "panels": [
    {
     "title": "Port response time per service (top $limit)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 3 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "topk($limit, node_monit{server_env=~\"$server_env\",hostname=~\"$hostname\",project=~\"$project\",key=\"port_responsetime\"})",
       "legendFormat": "{{name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "CPU",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 },
   "collapsed": true,
   "panels": [
    {
     "title": "Cpu total usage - Percent (top $limit)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 4 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "topk($limit, node_monit{server_env=~\"$server_env\",hostname=~\"$hostname\",project=~\"$project\",key=\"system_cpu_system\"})",
       "legendFormat": "system usage  {{hostname}}"
      },
      {
       "expr": "topk($limit, node_monit{server_env=~\"$server_env\",hostname=~\"$hostname\",project=~\"$project\",key=\"system_cpu_user\"})",
       "legendFormat": "user usage  {{hostname}}"
      },
      {
       "expr": "topk($limit, node_monit{server_env=~\"$server_env\",hostname=~\"$hostname\",project=~\"$project\",key=\"system_cpu_wait\"})",
       "legendFormat": "I/O wait  {{hostname}}"
      }
     ]
    },
    {
     "title": "Cpu usage per service (top $limit)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 11 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "topk($limit, node_monit{server_env=~\"$server_env\",hostname=~\"$hostname\",project=~\"$project\",key=\"cpu_percenttotal\"})",
       "legendFormat": "{{name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Memory",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 },
   "collapsed": true,
   "panels": [
    {
     "title": "Memory total usage (top $limit)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 5 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "topk($limit, node_monit{server_env=~\"$server_env\",hostname=~\"$hostname\",project=~\"$project\",key=\"system_memory_percent\"})",
       "legendFormat": "memory usage {{hostname}}"
      },
      {
       "expr": "topk($limit, node_monit{server_env=~\"$server_env\",hostname=~\"$hostname\",project=~\"$project\",key=\"system_swap_percent\"})",
       "legendFormat": "swap usage  {{hostname}}"
      }
     ]
    },
    {
     "title": "Memory usage per service (top $limit)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 12 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "topk($limit, node_monit{server_env=~\"$server_env\",hostname=~\"$hostname\",project=~\"$project\",key=\"memory_percenttotal\"})",
       "legendFormat": "{{name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Threads",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 },
   "collapsed": true,
   "panels": [
    {
     "title": "Threads number per service (top $limit)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 6 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "topk($limit, node_monit{server_env=~\"$server_env\",hostname=~\"$hostname\",project=~\"$project\",key=\"threads\"})",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Childrens number per service (top $limit)",
     "type": "graph",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 13 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "topk($limit, node_monit{server_env=~\"$server_env\",hostname=~\"$hostname\",project=~\"$project\",key=\"children\"})",
       "legendFormat": "{{name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Disk",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 },
   "collapsed": true,
   "panels": [
    {
     "title": "Read / Write operations/sec per disk (top $limit)",
     "type": "graph",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 7 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "topk($limit, node_monit{name=~\"$mountpoint\",server_env=~\"$server_env\",hostname=~\"$hostname\",project=~\"$project\",key=\"read_operations_count\",type=\"filesystem\"})",
       "legendFormat": "{{name}} Read"
      },
      {
       "expr": "topk($limit, node_monit{name=~\"$mountpoint\",server_env=~\"$server_env\",hostname=~\"$hostname\",project=~\"$project\",key=\"write_operations_count\",type=\"filesystem\"})",
       "legendFormat": "{{name}} Write"
      }
     ]
    },
    {
     "title": "Read / Write bytes/sec per disk (top ($limit)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 13 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "topk($limit, node_monit{name=~\"$mountpoint\",name=~\"$mountpoint\",server_env=~\"$server_env\",hostname=~\"$hostname\",project=~\"$project\",key=\"read_bytes_count\",type=\"filesystem\"})",
       "legendFormat": "{{name}} Read"
      },
      {
       "expr": "topk($limit, node_monit{name=~\"$mountpoint\",name=~\"$mountpoint\",server_env=~\"$server_env\",hostname=~\"$hostname\",project=~\"$project\",key=\"write_bytes_count\",type=\"filesystem\"})",
       "legendFormat": "{{name}} Write"
      }
     ]
    },
    {
     "title": "Disk usage per disk (top $limit)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 20 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "topk($limit, node_monit{name=~\"$mountpoint\",server_env=~\"$server_env\",hostname=~\"$hostname\",project=~\"$project\",key=\"block_percent\"})",
       "legendFormat": "{{name}} Data"
      },
      {
       "expr": "topk($limit, node_monit{name=~\"$mountpoint\",server_env=~\"$server_env\",hostname=~\"$hostname\",project=~\"$project\",key=\"inode_percent\"})",
       "legendFormat": "{{name}} Inodes"
      }
     ]
    }
   ]
  },
  {
   "title": "Network",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 },
   "collapsed": true,
   "panels": [
    {
     "title": "Network Download / Upload packets per interface (top $limit)",
     "type": "graph",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 8 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "topk($limit, node_monit{server_env=~\"$server_env\",hostname=~\"$hostname\",project=~\"$project\",key=\"link_download_packets_now\"})",
       "legendFormat": "{{name}} Download"
      },
      {
       "expr": "topk($limit, node_monit{server_env=~\"$server_env\",hostname=~\"$hostname\",project=~\"$project\",key=\"link_upload_packets_now\"})",
       "legendFormat": "{{name}} Upload"
      }
     ]
    },
    {
     "title": "Network Download / Upload bytes per interface (top $limit)",
     "type": "graph",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 14 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "topk($limit, node_monit{server_env=~\"$server_env\",hostname=~\"$hostname\",project=~\"$project\",key=\"link_download_bytes_now\"})",
       "legendFormat": "{{name}} Download"
      },
      {
       "expr": "topk($limit, node_monit{server_env=~\"$server_env\",hostname=~\"$hostname\",project=~\"$project\",key=\"link_upload_bytes_now\"})",
       "legendFormat": "{{name}} Upload"
      }
     ]
    },
    {
     "title": "Network Download / Upload errors per interface (top $limit)",
     "type": "graph",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 20 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "topk($limit, node_monit{server_env=~\"$server_env\",hostname=~\"$hostname\",project=~\"$project\",key=\"link_download_errors_now\"})",
       "legendFormat": "{{name}} Download"
      },
      {
       "expr": "topk($limit, node_monit{server_env=~\"$server_env\",hostname=~\"$hostname\",project=~\"$project\",key=\"link_upload_errors_now\"})",
       "legendFormat": "{{name}} Upload"
      }
     ]
    }
   ]
  }
 ]
}