{
 "title": "Monit exporter",
 "description": "Show monit stats as collector host",
 "tags": [ "monit" ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "node",
    "label": "Host:",
    "query": "label_values(node_monit{key=\"status\",type=\"system\"}, instance)"
   },
   {
    "name": "limit",
    "query": "1,2,3,4,5,6,7,8,9,10,15,20,30,40,60,80,100,9999"
   },
   {
    "name": "precision",
    "query": "1s,10s,1m,5m,15m,30m,1h,3h,6h,12h,24h"
   }
  ]
 },
 "panels": [
  {
   "title": "Status per service (top $limit)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk($limit, avg_over_time(node_monit{instance=\"$node\",key=\"status\"}[$precision]))",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Uptime per service (bottom $limit)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "dtdurations" }
   ],
   "targets": [
    {
     "expr": "bottomk($limit, node_monit{instance=\"$node\",key=\"uptime\"})",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Port response time per service (top $limit)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "topk($limit, node_monit{instance=\"$node\",key=\"port_responsetime\"})",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Load (LA)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_monit{instance=\"$node\",key=\"system_load_avg01\"}",
     "legendFormat": "LA 1"
    },
    {
     "expr": "instance:node_cpus:count{instance=\"$node\"}",
     "legendFormat": "Number of cores"
    }
   ]
  },
  {
   "title": "Cpu total usage (Percent)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "node_monit{instance=\"$node\",key=\"system_cpu_system\"}",
     "legendFormat": "system usage"
    },
    {
     "expr": "node_monit{instance=\"$node\",key=\"system_cpu_user\"}",
     "legendFormat": "user usage"
    },
    {
     "expr": "node_monit{instance=\"$node\",key=\"system_cpu_wait\"}",
     "legendFormat": "I/O wait"
    }
   ]
  },
  {
   "title": "Cpu usage per service (top $limit)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "topk($limit, node_monit{instance=\"$node\",key=\"cpu_percenttotal\"})",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Memory total usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "node_monit{instance=\"$node\",key=\"system_memory_percent\"}",
     "legendFormat": "memory usage"
    },
    {
     "expr": "node_monit{instance=\"$node\",key=\"system_swap_percent\"}",
     "legendFormat": "swap usage"
    }
   ]
  },
  {
   "title": "Memory usage per service (top $limit)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 27 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "topk($limit, node_monit{instance=\"$node\",key=\"memory_percenttotal\"})",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Threads number per service (top $limit)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk($limit, node_monit{instance=\"$node\",key=\"threads\"})",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Childrens number per service (top $limit)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 36 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk($limit, node_monit{instance=\"$node\",key=\"children\"})",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Read / Write operations/sec per disk (top $limit)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 45 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk($limit, node_monit{instance=\"$node\",key=\"read_operations_count\",type=\"filesystem\"})",
     "legendFormat": "{{name}} Read"
    },
    {
     "expr": "topk($limit, node_monit{instance=\"$node\",key=\"write_operations_count\",type=\"filesystem\"})",
     "legendFormat": "{{name}} Write"
    }
   ]
  },
  {
   "title": "Read / Write bytes/sec per disk (top ($limit)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 45 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "topk($limit, node_monit{instance=\"$node\",key=\"read_bytes_count\",type=\"filesystem\"})",
     "legendFormat": "{{name}} Read"
    },
    {
     "expr": "topk($limit, node_monit{instance=\"$node\",key=\"write_bytes_count\",type=\"filesystem\"})",
     "legendFormat": "{{name}} Write"
    }
   ]
  },
  {
   "title": "Network Download / Upload packets per interface (top $limit)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 54 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk($limit, node_monit{instance=\"$node\",key=\"link_download_packets_now\"})",
     "legendFormat": "{{name}} Download"
    },
    {
     "expr": "topk($limit, node_monit{instance=\"$node\",key=\"link_upload_packets_now\"})",
     "legendFormat": "{{name}} Upload"
    }
   ]
  },
  {
   "title": "Network Download / Upload bytes per interface (top $limit)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 54 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "topk($limit, node_monit{instance=\"$node\",key=\"link_download_bytes_now\"})",
     "legendFormat": "{{name}} Download"
    },
    {
     "expr": "topk($limit, node_monit{instance=\"$node\",key=\"link_upload_bytes_now\"})",
     "legendFormat": "{{name}} Upload"
    }
   ]
  },
  {
   "title": "Disk usage per disk (top $limit)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 63 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "topk($limit, node_monit{instance=\"$node\",key=\"block_percent\"})",
     "legendFormat": "{{name}} Data"
    },
    {
     "expr": "topk($limit, node_monit{instance=\"$node\",key=\"inode_percent\"})",
     "legendFormat": "{{name}} Inodes"
    }
   ]
  },
  {
   "title": "Network Download / Upload errors per interface (top $limit)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 63 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk($limit, node_monit{instance=\"$node\",key=\"link_download_errors_now\"})",
     "legendFormat": "{{name}} Download"
    },
    {
     "expr": "topk($limit, node_monit{instance=\"$node\",key=\"link_upload_errors_now\"})",
     "legendFormat": "{{name}} Upload"
    }
   ]
  }
 ]
}