{
 "title": "MySQL (mysqld_exporter)",
 "tags": [
  "dba",
  "operations",
  "featured"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "server_env",
    "label": "Environment",
    "query": "label_values(prometheus_config_last_reload_successful, server_env)"
   },
   { "name": "data_source", "label": "Data source", "query": "prometheus" },
   {
    "name": "project",
    "label": "Project",
    "query": "label_values(mysql_up{server_env=~\"$server_env\"},project)"
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": "label_values(mysql_up{server_env=~\"$server_env\",project=~\"$project\"}, instance)"
   },
   {
    "name": "limit",
    "query": "1,2,3,4,5,6,7,8,9,10,15,20,25,30,40,50,70,100,9999"
   }
  ]
 },
 "panels": [
  {
   "title": "Exporter",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Mysql exporter scrape status (bottom $limit)",
     "type": "graph",
     "description": "1 = OK",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 1 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "bottomk($limit, up{job=~\"mysqld_exporter.*\",instance=~\"$instance\",server_env=~\"$server_env\",project=~\"$project\"})",
       "legendFormat": "{{ instance }}"
      }
     ]
    },
    {
     "title": "Scrape duration (top $limit)",
     "type": "graph",
     "description": "Duration of the scrape",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 6 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "topk($limit, scrape_duration_seconds{job=~\"mysqld_exporter.*\",instance=~\"$instance\",server_env=~\"$server_env\",project=~\"$project\"})",
       "legendFormat": "{{ instance }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Info",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Version info",
     "type": "table",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 2 },
     "targets": [
      {
       "expr": "topk($limit, mysql_version_info{instance=~\"$instance\"})"
      }
     ]
    }
   ]
  },
  {
   "title": "Processes",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "Processlist",
     "type": "graph",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 3 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "mysql_info_schema_threads{instance=~\"$instance\",server_env=~\"$server_env\",project=~\"$project\",state=\"idle\"}",
       "legendFormat": "{{ instance }} - Idle"
      },
      {
       "expr": "mysql_info_schema_threads{instance=~\"$instance\",server_env=~\"$server_env\",project=~\"$project\",state=\"updating\"}",
       "legendFormat": "{{ instance }} - Updating"
      },
      {
       "expr": "mysql_info_schema_threads{instance=~\"$instance\",server_env=~\"$server_env\",project=~\"$project\",state=\"altering table\"}",
       "legendFormat": "{{ instance }} - Altering Table"
      },
      {
       "expr": "sum(mysql_info_schema_threads{instance=~\"$instance\",server_env=~\"$server_env\",project=~\"$project\",state=~\".*waiting.*\"})",
       "legendFormat": "{{ instance }} - Waiting"
      },
      {
       "expr": "mysql_info_schema_threads{instance=~\"$instance\",server_env=~\"$server_env\",project=~\"$project\",state=\"init\"}",
       "legendFormat": "{{ instance }} - Init"
      },
      {
       "expr": "mysql_info_schema_threads{instance=~\"$instance\",server_env=~\"$server_env\",project=~\"$project\",state=\"sending data\"}",
       "legendFormat": "{{ instance }} - Sending data"
      },
      {
       "expr": "sum(mysql_info_schema_threads{instance=~\"$instance\",server_env=~\"$server_env\",project=~\"$project\",state=~\".*tmp.*\"})",
       "legendFormat": "{{ instance }} - Tmp Table"
      },
      {
       "expr": "sum(mysql_info_schema_threads{instance=~\"$instance\",server_env=~\"$server_env\",project=~\"$project\",state=~\".*Binlog.*\"})",
       "legendFormat": "{{ instance }} - Binlog"
      },
      {
       "expr": "sum(mysql_info_schema_threads{instance=~\"$instance\",server_env=~\"$server_env\",project=~\"$project\",state=~\".*Relay.*\"})",
       "legendFormat": "{{ instance }} - Relay Log"
      },
      {
       "expr": "sum(mysql_info_schema_threads{instance=~\"$instance\",server_env=~\"$server_env\",project=~\"$project\",state=\"sleep\"})",
       "legendFormat": "{{ instance }} - Sleep"
      },
      {
       "expr": "sum(mysql_info_schema_threads{instance=~\"$instance\",server_env=~\"$server_env\",project=~\"$project\",state=\"other\"})",
       "legendFormat": "{{ instance }} - Other"
      }
     ]
    }
   ]
  },
  { "title": "Traffic", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 } },
  {
   "title": "Traffic (aggregated for all selected hosts)",
   "type": "graph",
   "description": "Total bytes received/sent from all clients\n\nAverage if more than one instance selected",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "avg(irate(mysql_global_status_bytes_received{instance=~\"$instance\",server_env=~\"$server_env\",project=~\"$project\"}[5m]))",
     "legendFormat": "Received"
    },
    {
     "expr": "avg(irate(mysql_global_status_bytes_sent{instance=~\"$instance\",server_env=~\"$server_env\",project=~\"$project\"}[5m]))",
     "legendFormat": "Sent"
    }
   ]
  },
  {
   "title": "Traffic (top $limit)",
   "type": "graph",
   "description": "Total bytes received/sent from all clients",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "topk($limit, irate(mysql_global_status_bytes_received{instance=~\"$instance\",server_env=~\"$server_env\",project=~\"$project\"}[5m]))",
     "legendFormat": "{{ instance }} - Received"
    },
    {
     "expr": "topk($limit, irate(mysql_global_status_bytes_sent{instance=~\"$instance\",server_env=~\"$server_env\",project=~\"$project\"}[5m]))",
     "legendFormat": "{{ instance }} - Sent"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 },
   "collapsed": true,
   "panels": [
    {
     "title": "Uptime (bottom $limit)",
     "type": "graph",
     "description": "Service uptime",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 12 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "bottomk($limit, mysql_global_status_uptime{job=~\"mysqld_exporter.*\",instance=~\"$instance\",server_env=~\"$server_env\",project=~\"$project\"})",
       "legendFormat": "{{ instance }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Connections",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "collapsed": true,
   "panels": [
    {
     "title": "Connections (aggregated for all selected hosts)",
     "type": "graph",
     "description": "Connections stats\n\nAverage if more than one instance selected",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 6 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "avg(rate(mysql_global_status_connections{instance=~\"$instance\",server_env=~\"$server_env\",project=~\"$project\"}[5m]))",
       "legendFormat": "New connections"
      },
      {
       "expr": "max(mysql_global_variables_max_connections)",
       "legendFormat": "MAX"
      },
      {
       "expr": "avg(mysql_global_status_threads_connected{instance=~\"$instance\",server_env=~\"$server_env\",project=~\"$project\"})",
       "legendFormat": "Coonnected"
      },
      {
       "expr": "avg(mysql_global_status_threads_running{instance=~\"$instance\",server_env=~\"$server_env\",project=~\"$project\"})",
       "legendFormat": "Running"
      }
     ]
    },
    {
     "title": "Connections (top $limit)",
     "type": "graph",
     "description": "Connections stats",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 11 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "topk($limit, rate(mysql_global_status_connections{instance=~\"$instance\",server_env=~\"$server_env\",project=~\"$project\"}[5m]))",
       "legendFormat": "{{ instance }} - New connections"
      },
      {
       "expr": "max(mysql_global_variables_max_connections)",
       "legendFormat": "MAX"
      },
      {
       "expr": "topk($limit, mysql_global_status_threads_connected{instance=~\"$instance\",server_env=~\"$server_env\",project=~\"$project\"})",
       "legendFormat": "{{ instance }} - Coonnected"
      },
      {
       "expr": "topk($limit, mysql_global_status_threads_running{instance=~\"$instance\",server_env=~\"$server_env\",project=~\"$project\"})",
       "legendFormat": "{{ instance }} - Running"
      }
     ]
    },
    {
     "title": "Connection problems (aggregated for all selected hosts)",
     "type": "graph",
     "description": "Average if more than one instance selected",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 16 },
     "yaxes": [
      { "format": "short", "label": "problems/s" }
     ],
     "targets": [
      {
       "expr": "avg(rate(mysql_global_status_aborted_connects{instance=~\"$instance\",server_env=~\"$server_env\",project=~\"$project\"}[5m]))",
       "legendFormat": "Aborted Connects"
      },
      {
       "expr": "avg(rate(mysql_global_variables_connect_timeout{instance=~\"$instance\",server_env=~\"$server_env\",project=~\"$project\"}[5m]))",
       "legendFormat": "Connect Timeout"
      },
      {
       "expr": "avg(rate(mysql_global_status_aborted_clients{instance=~\"$instance\",server_env=~\"$server_env\",project=~\"$project\"}[5m]))",
       "legendFormat": "Aborted clients"
      },
      {
       "expr": "avg(rate(mysql_global_status_commands_total{command=\"kill\",instance=~\"$instance\",server_env=~\"$server_env\",project=~\"$project\"}[5m]))",
       "legendFormat": "Kill Commands"
      }
     ]
    },
    {
     "title": "Connection problems (top $limit)",
     "type": "graph",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 21 },
     "yaxes": [
      { "format": "short", "label": "problems/s" }
     ],
     "targets": [
      {
       "expr": "topk($limit, rate(mysql_global_status_aborted_connects{instance=~\"$instance\",server_env=~\"$server_env\",project=~\"$project\"}[5m]))",
       "legendFormat": "{{ instance }} - Aborted Connects"
      },
      {
       "expr": "topk($limit, rate(mysql_global_variables_connect_timeout{instance=~\"$instance\",server_env=~\"$server_env\",project=~\"$project\"}[5m]))",
       "legendFormat": "{{ instance }} - Connect Timeout"
      },
      {
       "expr": "topk($limit, rate(mysql_global_status_aborted_clients{instance=~\"$instance\",server_env=~\"$server_env\",project=~\"$project\"}[5m]))",
       "legendFormat": "{{ instance }} - Aborted clients"
      },
      {
       "expr": "topk($limit, rate(mysql_global_status_commands_total{command=\"kill\",instance=~\"$instance\",server_env=~\"$server_env\",project=~\"$project\"}[5m]))",
       "legendFormat": "{{ instance }} - Kill Commands"
      }
     ]
    },
    {
     "title": "Potential contention causes (top $limit)",
     "type": "graph",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 26 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "topk($limit, rate(mysql_global_status_innodb_log_waits{instance=~\"$instance\",server_env=~\"$server_env\",project=~\"$project\"}[5m]))",
       "legendFormat": "{{ instance }} - Innodb Log Waits"
      },
      {
       "expr": "topk($limit, rate(mysql_global_status_binlog_cache_disk_use{instance=~\"$instance\",server_env=~\"$server_env\",project=~\"$project\"}[5m]))",
       "legendFormat": "{{ instance }} - Binlog Disk Use"
      },
      {
       "expr": "topk($limit, rate(mysql_global_status_innodb_deadlocks{instance=~\"$instance\",server_env=~\"$server_env\",project=~\"$project\"}[5m]))",
       "legendFormat": "{{ instance }} - InnoDB deadlocks"
      },
      {
       "expr": "topk($limit, rate(mysql_global_status_table_locks_waited{instance=~\"$instance\",server_env=~\"$server_env\",project=~\"$project\"}[5m]))",
       "legendFormat": "{{ instance }} - Table Locks Waited"
      },
      {
       "expr": "topk($limit, rate(mysql_global_status_qcache_inserts{instance=~\"$instance\",server_env=~\"$server_env\",project=~\"$project\"}[5m]))",
       "legendFormat": "{{ instance }} - Query Cache Inserts"
      },
      {
       "expr": "topk($limit, rate(mysql_global_status_innodb_row_lock_waits{instance=~\"$instance\",server_env=~\"$server_env\",project=~\"$project\"}[5m]))",
       "legendFormat": "{{ instance }} - InnoDB Row Lock Waits"
      }
     ]
    }
   ]
  },
  {
   "title": "Queries",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "collapsed": true,
   "panels": [
    {
     "title": "Queries Per Second (top $limit)",
     "type": "graph",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 7 },
     "yaxes": [
      { "format": "ops", "label": "# queries / s" }
     ],
     "targets": [
      {
       "expr": "topk($limit, irate(mysql_global_status_queries{instance=~\"$instance\",server_env=~\"$server_env\",project=~\"$project\"}[5m]))",
       "legendFormat": "{{ instance }} - Queries per second"
      },
      {
       "expr": "topk($limit, irate(mysql_global_status_questions{instance=~\"$instance\",server_env=~\"$server_env\",project=~\"$project\"}[5m]))",
       "legendFormat": "{{ instance }} - Questions per second"
      },
      {
       "expr": "topk($limit, irate(mysql_global_status_commands_total{instance=~\"$instance\",server_env=~\"$server_env\",project=~\"$project\",command=\"select\"}[5m]))",
       "legendFormat": "{{ instance }} - SELECTs"
      }
     ]
    },
    {
     "title": "Write Query Stats (top $limit)",
     "type": "graph",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 13 },
     "yaxes": [
      { "format": "wps", "label": "writes/s" }
     ],
     "targets": [
      {
       "expr": "topk($limit, irate(mysql_global_status_commands_total{instance=~\"$instance\",server_env=~\"$server_env\",project=~\"$project\",command=\"insert\"}[5m]))",
       "legendFormat": "{{ instance }} - INSERT"
      },
      {
       "expr": "topk($limit, irate(mysql_global_status_commands_total{instance=~\"$instance\",server_env=~\"$server_env\",project=~\"$project\",command=\"update\"}[5m]))",
       "legendFormat": "{{ instance }} - UPDATE"
      },
      {
       "expr": "topk($limit, irate(mysql_global_status_commands_total{instance=~\"$instance\",server_env=~\"$server_env\",project=~\"$project\",command=\"delete\"}[5m]))",
       "legendFormat": "{{ instance }} - DELETE"
      },
      {
       "expr": "topk($limit, irate(mysql_global_status_commands_total{instance=~\"$instance\",server_env=~\"$server_env\",project=~\"$project\",command=\"replace\"}[5m]))",
       "legendFormat": "{{ instance }} - REPLACE"
      },
      {
       "expr": "topk($limit, irate(mysql_global_status_commands_total{instance=~\"$instance\",server_env=~\"$server_env\",project=~\"$project\",command=\"insert_select\"}[5m]))",
       "legendFormat": "{{ instance }} - INSERT... SELECT"
      }
     ]
    },
    {
     "title": "Select Types (top $limit)",
     "type": "graph",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 19 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "topk($limit, rate(mysql_global_status_select_full_range_join{instance=~\"$instance\",server_env=~\"$server_env\",project=~\"$project\"}[5m]))",
       "legendFormat": "{{ instance }} - Select Full Range Join"
      },
      {
       "expr": "topk($limit, rate(mysql_global_status_select_full_join{instance=~\"$instance\",server_env=~\"$server_env\",project=~\"$project\"}[5m]))",
       "legendFormat": "{{ instance }} - Select Full Join"
      },
      {
       "expr": "topk($limit, rate(mysql_global_status_select_range{instance=~\"$instance\",server_env=~\"$server_env\",project=~\"$project\"}[5m]))",
       "legendFormat": "{{ instance }} - Select Range"
      },
      {
       "expr": "topk($limit, rate(mysql_global_status_select_scan{instance=~\"$instance\",server_env=~\"$server_env\",project=~\"$project\"}[5m]))",
       "legendFormat": "{{ instance }} - Select Scan"
      },
      {
       "expr": "topk($limit, rate(mysql_global_status_select_range_check{instance=~\"$instance\",server_env=~\"$server_env\",project=~\"$project\"}[5m]))",
       "legendFormat": "{{ instance }} - Select Range Check"
      }
     ]
    }
   ]
  },
  {
   "title": "Buffer",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 },
   "collapsed": true,
   "panels": [
    {
     "title": "InnoDB Buffer Pool (top $limit)",
     "type": "graph",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 8 },
     "yaxes": [
      { "format": "bytes", "label": "Total Bytes" }
     ],
     "targets": [
      {
       "expr": "topk($limit, mysql_global_variables_innodb_buffer_pool_size{instance=~\"$instance\",server_env=~\"$server_env\",project=~\"$project\"})",
       "legendFormat": "{{ instance }} - innodb_buffer_pool_size"
      },
      {
       "expr": "topk($limit, mysql_global_status_innodb_buffer_pool_bytes_data{instance=~\"$instance\",server_env=~\"$server_env\",project=~\"$project\"})",
       "legendFormat": "{{ instance }} - innodb_buffer_pool_bytes_data"
      },
      {
       "expr": "topk($limit, mysql_global_status_innodb_buffer_pool_bytes_dirty{instance=~\"$instance\",server_env=~\"$server_env\",project=~\"$project\"})",
       "legendFormat": "{{ instance }} - innodb_buffer_pool_bytes_dirty"
      }
     ]
    },
    {
     "title": "InnoDB Buffer Pool Activity (top $limit)",
     "type": "graph",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 14 },
     "yaxes": [
      { "format": "short", "label": "pages/s" }
     ],
     "targets": [
      {
       "expr": "topk($limit, irate(mysql_global_status_innodb_pages_created{instance=~\"$instance\",server_env=~\"$server_env\",project=~\"$project\"}[5m]))",
       "legendFormat": "{{ instance }} - InnoDB Pages Created"
      },
      {
       "expr": "topk($limit, irate(mysql_global_status_innodb_pages_read{instance=~\"$instance\",server_env=~\"$server_env\",project=~\"$project\"}[5m]))",
       "legendFormat": "{{ instance }} - InnoDB Pages Read"
      },
      {
       "expr": "topk($limit, irate(mysql_global_status_innodb_pages_written{instance=~\"$instance\",server_env=~\"$server_env\",project=~\"$project\"}[5m]))",
       "legendFormat": "{{ instance }} - InnoDB Pages Written"
      }
     ]
    },
    {
     "title": "Change Buffer (top $limit)",
     "type": "graph",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 20 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "topk($limit, rate(mysql_global_status_innodb_ibuf_merged_inserts{instance=~\"$instance\",server_env=~\"$server_env\",project=~\"$project\"}[5m]))",
       "legendFormat": "Change Buffer Merged Inserts"
      },
      {
       "expr": "topk($limit, rate(mysql_global_status_innodb_ibuf_merges{instance=~\"$instance\",server_env=~\"$server_env\",project=~\"$project\"}[5m]))",
       "legendFormat": "Change Buffer Merges"
      },
      {
       "expr": "topk($limit, rate(mysql_global_status_innodb_ibuf_merged_deletes{instance=~\"$instance\",server_env=~\"$server_env\",project=~\"$project\"}[5m]))",
       "legendFormat": "Change Buffer Merged Deletes"
      },
      {
       "expr": "topk($limit, mysql_global_status_innodb_ibuf_size{instance=~\"$instance\",server_env=~\"$server_env\",project=~\"$project\"})",
       "legendFormat": "Insert Buffer Size"
      },
      {
       "expr": "topk($limit, rate(mysql_global_status_innodb_ibuf_free_list{instance=~\"$instance\",server_env=~\"$server_env\",project=~\"$project\"}[5m]))",
       "legendFormat": "Change Buffer Free List"
      }
     ]
    },
    {
     "title": "InnoDB Buffer Pool Efficiency (top $limit)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 26 },
     "yaxes": [
      {
       "format": "percentunit",
       "label": "1 - Buffer reads / Buffer Read Requests"
      }
     ],
     "targets": [
      {
       "expr": "topk($limit, irate(mysql_global_status_innodb_buffer_pool_read_requests{instance=~\"$instance\",server_env=~\"$server_env\",project=~\"$project\"}[5m])/(irate(mysql_global_status_innodb_buffer_pool_reads{instance=~\"$instance\",server_env=~\"$server_env\",project=~\"$project\"}[5m]) + irate(mysql_global_status_innodb_buffer_pool_read_requests{instance=~\"$instance\",server_env=~\"$server_env\",project=~\"$project\"}[5m])))",
       "legendFormat": "{{ instance }} - hit ratio"
      },
      {
       "expr": "topk($limit, 1 - (irate(mysql_global_status_innodb_buffer_pool_reads{instance=~\"$instance\",server_env=~\"$server_env\",project=~\"$project\"}[5m]) / irate(mysql_global_status_innodb_buffer_pool_read_requests{instance=~\"$instance\",server_env=~\"$server_env\",project=~\"$project\"}[5m])))",
       "legendFormat": "{{ instance }} - hit ratio (excluding out of band writes, can be negative)"
      }
     ]
    }
   ]
  },
  {
   "title": "Tables",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 },
   "collapsed": true,
   "panels": [
    {
     "title": "Temporary Tables (top $limit)",
     "type": "graph",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 9 },
     "yaxes": [
      { "format": "short", "label": "# per second" }
     ],
     "targets": [
      {
       "expr": "topk($limit, rate(mysql_global_status_created_tmp_tables{instance=~\"$instance\",server_env=~\"$server_env\",project=~\"$project\"}[5m]))",
       "legendFormat": "{{ instance }} - Created Tmp Tables"
      },
      {
       "expr": "topk($limit, rate(mysql_global_status_created_tmp_disk_tables{instance=~\"$instance\",server_env=~\"$server_env\",project=~\"$project\"}[5m]))",
       "legendFormat": "{{ instance }} - Created Tmp Disk Tables"
      },
      {
       "expr": "topk($limit, rate(mysql_global_status_created_tmp_files{instance=~\"$instance\",server_env=~\"$server_env\",project=~\"$project\"}[5m]))",
       "legendFormat": "{{ instance }} - Created Tmp Files"
      }
     ]
    }
   ]
  },
  {
   "title": "Replication",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 },
   "collapsed": true,
   "panels": [
    {
     "title": "Replication Lag (top $limit)",
     "type": "graph",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "topk($limit, mysql_slave_status_seconds_behind_master{instance=~\"$instance\",server_env=~\"$server_env\",project=~\"$project\"})",
       "legendFormat": "{{ instance }} - Seconds Behind Master ({{ connection_name }}:{{ master_host }})"
      }
     ]
    }
   ]
  },
  {
   "title": "Innodb wait time",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 },
   "collapsed": true,
   "panels": [
    {
     "title": "InnoDB Wait Time (top $limit)",
     "type": "graph",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 17 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "topk($limit, rate(mysql_global_status_innodb_row_lock_time{instance=~\"$instance\",server_env=~\"$server_env\",project=~\"$project\"}[5m]))",
       "legendFormat": "{{ instance }} - InnoDB Row Lock Time"
      },
      {
       "expr": "0",
       "legendFormat": "InnoDB Semaphore Wait Time (not working)"
      }
     ]
    }
   ]
  },
  {
   "title": "Innodb I/O",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 },
   "collapsed": true,
   "panels": [
    {
     "title": "InnoDB I/O (operations) (top $limit)",
     "type": "graph",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 11 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "topk($limit, rate(mysql_global_status_innodb_data_reads{instance=~\"$instance\",server_env=~\"$server_env\",project=~\"$project\"}[5m]))",
       "legendFormat": "{{ instance }} - InnoDB Data Reads"
      },
      {
       "expr": "topk($limit, rate(mysql_global_status_innodb_data_writes{instance=~\"$instance\",server_env=~\"$server_env\",project=~\"$project\"}[5m]))",
       "legendFormat": "{{ instance }} - InnoDB Data Writes"
      },
      {
       "expr": "topk($limit, rate(mysql_global_status_innodb_log_writes{instance=~\"$instance\",server_env=~\"$server_env\",project=~\"$project\"}[5m]))",
       "legendFormat": "{{ instance }} - InnoDB Log Writes"
      },
      {
       "expr": "topk($limit, rate(mysql_global_status_innodb_data_fsyncs{instance=~\"$instance\",server_env=~\"$server_env\",project=~\"$project\"}[5m]))",
       "legendFormat": "{{ instance }} - InnoDB Data Fsyncs"
      },
      {
       "expr": "topk($limit, rate(mysql_global_status_innodb_os_log_fsyncs{instance=~\"$instance\",server_env=~\"$server_env\",project=~\"$project\"}[5m]))",
       "legendFormat": "{{ instance }} - InnoDB OS Log Fsyncs"
      },
      {
       "expr": "topk($limit, mysql_global_status_innodb_data_pending_fsyncs{instance=~\"$instance\",server_env=~\"$server_env\",project=~\"$project\"})",
       "legendFormat": "{{ instance }} - InnoDB Data Pending Fsyncs"
      },
      {
       "expr": "topk($limit, mysql_global_status_innodb_data_pending_reads{instance=~\"$instance\",server_env=~\"$server_env\",project=~\"$project\"})",
       "legendFormat": "{{ instance }} - InnoDB Data Pending Reads"
      },
      {
       "expr": "topk($limit, mysql_global_status_innodb_data_pending_writes{instance=~\"$instance\",server_env=~\"$server_env\",project=~\"$project\"})",
       "legendFormat": "{{ instance }} - InnoDB Data Pending Writes"
      },
      {
       "expr": "topk($limit, mysql_global_status_innodb_os_log_pending_fsyncs{instance=~\"$instance\",server_env=~\"$server_env\",project=~\"$project\"})",
       "legendFormat": "{{ instance }} - InnoDB OS Log pending Fsyncs"
      },
      {
       "expr": "topk($limit, mysql_global_status_innodb_os_log_pending_writes{instance=~\"$instance\",server_env=~\"$server_env\",project=~\"$project\"})",
       "legendFormat": "{{ instance }} - InnoDB OS Log pending Writes"
      }
     ]
    }
   ]
  },
  {
   "title": "Innodb checkpoint",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 },
   "collapsed": true,
   "panels": [
    {
     "title": "InnoDB Checkpoint Age (top $limit)",
     "type": "graph",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 13 },
     "yaxes": [
      { "format": "bytes", "label": "bytes" }
     ],
     "targets": [
      {
       "expr": "topk($limit, mysql_global_status_innodb_checkpoint_age{instance=~\"$instance\",server_env=~\"$server_env\",project=~\"$project\"})",
       "legendFormat": "{{ instance }} - innodb_checkpoint_age"
      },
      {
       "expr": "topk($limit, mysql_global_status_innodb_checkpoint_max_age{instance=~\"$instance\",server_env=~\"$server_env\",project=~\"$project\"})",
       "legendFormat": "{{ instance }} - Max Checkpoint Age"
      },
      {
       "expr": "topk($limit, mysql_global_variables_innodb_log_file_size{instance=~\"$instance\",server_env=~\"$server_env\",project=~\"$project\"}*mysql_global_variables_innodb_log_files_in_group{instance=~\"$instance\",server_env=~\"$server_env\",project=~\"$project\"})",
       "legendFormat": "{{ instance }} - Combined log file size"
      }
     ]
    }
   ]
  },
  {
   "title": "Innodb purge",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 },
   "collapsed": true,
   "panels": [
    {
     "title": "Innodb Purge Lag (top $limit)",
     "type": "graph",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 14 },
     "yaxes": [
      { "format": "short", "label": "size" }
     ],
     "targets": [
      {
       "bucketAggs": [
        { "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
       ],
       "expr": "topk($limit, mysql_global_status_innodb_history_list_length{instance=~\"$instance\",server_env=~\"$server_env\",project=~\"$project\"})",
       "legendFormat": "InnoDB History List Length",
       "metrics": [
        { "id": "1", "type": "count" }
       ],
       "timeField": "@timestamp"
      }
     ]
    }
   ]
  },
  {
   "title": "Handler",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 },
   "collapsed": true,
   "panels": [
    {
     "title": "Handler Stats (top $limit)",
     "type": "graph",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 15 },
     "yaxes": [
      { "format": "short", "label": "rows/s" }
     ],
     "targets": [
      {
       "expr": "topk($limit, rate(mysql_global_status_handlers_total{instance=~\"$instance\",server_env=~\"$server_env\",project=~\"$project\",handler=\"read_rnd_next\"}[5m]))",
       "legendFormat": "{{ instance }} - read_rnd_next"
      },
      {
       "expr": "topk($limit, rate(mysql_global_status_handlers_total{instance=~\"$instance\",server_env=~\"$server_env\",project=~\"$project\",handler=\"read_next\"}[5m]))",
       "legendFormat": "{{ instance }} - read_next"
      },
      {
       "expr": "topk($limit, rate(mysql_global_status_handlers_total{instance=~\"$instance\",server_env=~\"$server_env\",project=~\"$project\",handler=\"read_key\"}[5m]))",
       "legendFormat": "{{ instance }} - read_key"
      },
      {
       "expr": "topk($limit, irate(mysql_global_status_handlers_total{instance=~\"$instance\",server_env=~\"$server_env\",project=~\"$project\",handler=\"write\"}[5m]))",
       "legendFormat": "{{ instance }} - write"
      },
      {
       "expr": "topk($limit, rate(mysql_global_status_handlers_total{instance=~\"$instance\",server_env=~\"$server_env\",project=~\"$project\",handler=\"update\"}[5m]))",
       "legendFormat": "{{ instance }} - update"
      },
      {
       "expr": "topk($limit, rate(mysql_global_status_handlers_total{instance=~\"$instance\",server_env=~\"$server_env\",project=~\"$project\",handler=\"delete\"}[5m]))",
       "legendFormat": "{{ instance }} - delete"
      },
      {
       "expr": "topk($limit, rate(mysql_global_status_handlers_total{instance=~\"$instance\",server_env=~\"$server_env\",project=~\"$project\",handler=\"read_first\"}[5m]))",
       "legendFormat": "{{ instance }} - read_first"
      },
      {
       "expr": "topk($limit, rate(mysql_global_status_handlers_total{instance=~\"$instance\",server_env=~\"$server_env\",project=~\"$project\",handler=\"read_prev\"}[5m]))",
       "legendFormat": "{{ instance }} - read_prev"
      },
      {
       "expr": "topk($limit, rate(mysql_global_status_handlers_total{instance=~\"$instance\",server_env=~\"$server_env\",project=~\"$project\",handler=\"read_rnd\"}[5m]))",
       "legendFormat": "{{ instance }} - read_rnd"
      }
     ]
    },
    {
     "title": "Sorting (top $limit)",
     "type": "graph",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 21 },
     "yaxes": [
      { "format": "short", "label": "# per second" }
     ],
     "targets": [
      {
       "expr": "topk($limit, rate(mysql_global_status_sort_merge_passes{instance=~\"$instance\",server_env=~\"$server_env\",project=~\"$project\"}[5m]))",
       "legendFormat": "{{ instance }} - sort_merge_passes"
      },
      {
       "expr": "topk($limit, rate(mysql_global_status_sort_priority_queue_sorts{instance=~\"$instance\",server_env=~\"$server_env\",project=~\"$project\"}[5m]))",
       "legendFormat": "{{ instance }} - sort_priority_queue_sorts"
      },
      {
       "expr": "topk($limit, rate(mysql_global_status_sort_range{instance=~\"$instance\",server_env=~\"$server_env\",project=~\"$project\"}[5m]))",
       "legendFormat": "{{ instance }} - sort_range"
      },
      {
       "expr": "topk($limit, rate(mysql_global_status_sort_rows{instance=~\"$instance\",server_env=~\"$server_env\",project=~\"$project\"}[5m]))",
       "legendFormat": "{{ instance }} - sort_rows"
      },
      {
       "expr": "topk($limit, rate(mysql_global_status_sort_scan{instance=~\"$instance\",server_env=~\"$server_env\",project=~\"$project\"}[5m]))",
       "legendFormat": "{{ instance }} - sort_scan"
      }
     ]
    }
   ]
  },
  {
   "title": "Innodb I/O",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 },
   "collapsed": true,
   "panels": [
    {
     "title": "Open Descriptors (top $limit)",
     "type": "graph",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 16 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "topk($limit, mysql_global_status_open_files{instance=~\"$instance\",server_env=~\"$server_env\",project=~\"$project\"})",
       "legendFormat": "{{ instance }} - Current Open Files"
      },
      {
       "expr": "topk($limit, mysql_global_status_open_table_definitions{instance=~\"$instance\",server_env=~\"$server_env\",project=~\"$project\"})",
       "legendFormat": "{{ instance }} - Current Open Table Definitions"
      },
      {
       "expr": "topk($limit, mysql_global_status_open_tables{instance=~\"$instance\",server_env=~\"$server_env\",project=~\"$project\"})",
       "legendFormat": "{{ instance }} - Current Open Tables"
      }
     ]
    },
    {
     "title": "InnoDB I/O (bytes) (top $limit)",
     "type": "graph",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 22 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "topk($limit, rate(mysql_global_status_innodb_data_read{instance=~\"$instance\",server_env=~\"$server_env\",project=~\"$project\"}[5m]))",
       "legendFormat": "{{ instance }} - InnoDB Data Read"
      },
      {
       "expr": "topk($limit, rate(mysql_global_status_innodb_data_written{instance=~\"$instance\",server_env=~\"$server_env\",project=~\"$project\"}[5m]))",
       "legendFormat": "{{ instance }} - InnoDB Data Written"
      }
     ]
    }
   ]
  },
  {
   "title": "TMP",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 },
   "collapsed": true,
   "panels": [
    {
     "title": "MyISAM Key Buffer",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 17 },
     "yaxes": [
      { "format": "bytes", "label": "Bytes" }
     ],
     "targets": [
      {
       "expr": "mysql_global_variables_key_buffer_size{instance=\"$server:$port\"}",
       "legendFormat": "key_buffer_size"
      },
      {
       "expr": "mysql_global_status_key_blocks_used{instance=\"$server:$port\"}*mysql_global_variables_key_cache_block_size{instance=\"$server:$port\"}",
       "legendFormat": "key_cache_used"
      }
     ]
    },
    {
     "title": "Adaptive Hash and other memory usage",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 17 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "mysql_global_status_innodb_mem_adaptive_hash{instance=\"$server:$port\"}",
       "legendFormat": "Memory Adaptive Hash"
      },
      {
       "expr": "mysql_global_status_innodb_mem_dictionary{instance=\"$server:$port\"}",
       "legendFormat": "Memory Dictionary"
      },
      {
       "expr": "mysql_global_variables_innodb_additional_mem_pool_size{instance=\"$server:$port\"}",
       "legendFormat": "Additional Memory Pool"
      }
     ]
    },
    {
     "title": "Disk Latency",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 24 },
     "yaxes": [
      { "format": "ms", "label": "seconds" }
     ],
     "targets": [
      {
       "expr": "(max(irate(node_disk_read_time_seconds_total{instance=\"$server:9100\", device=~\"sda.*\"}[5m]))*1000) or max(irate(node_disk_read_time_ms{instance=\"$server:9100\", device=~\"sda.*\"}[5m]))",
       "legendFormat": "Disk IO read time"
      },
      {
       "expr": "(max(irate(node_disk_write_time_seconds_total{instance=\"$server:9100\", device=~\"sda.*\"}[5m]))*1000) or max(irate(node_disk_write_time_ms{instance=\"$server:9100\", device=~\"sda.*\"}[5m]))",
       "legendFormat": "Disk IO write time"
      }
     ]
    },
    {
     "title": "InnoDB Semaphores",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 24 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "  rate(mysql_global_status_innodb_mutex_os_waits{instance=\"$server:$port\"}[5m])",
       "legendFormat": "InnoDB Mutex OS Waits"
      },
      {
       "expr": "rate(mysql_global_status_innodb_mutex_spin_rounds{instance=\"$server:$port\"}[5m])",
       "legendFormat": "InnoDB Mutex Spin Rounds"
      },
      {
       "expr": "rate(mysql_global_status_innodb_mutex_spin_waits{instance=\"$server:$port\"}[5m])",
       "legendFormat": "InnoDB Mutex Spin Waits"
      }
     ]
    },
    {
     "title": "Disk IO Thoughput",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 31 },
     "yaxes": [
      { "format": "Bps", "label": "bytes/s" }
     ],
     "targets": [
      {
       "expr": "sum(irate(node_disk_read_bytes_total{instance=\"$server:9100\", device=~\"sda.*\"}[5m])) or sum(irate(node_disk_bytes_read{instance=\"$server:9100\", device=~\"sda.*\"}[5m]))",
       "legendFormat": "bytes_read"
      },
      {
       "expr": "sum(irate(node_disk_written_bytes_total{instance=\"$server:9100\", device=~\"sda.*\"}[5m])) or sum(irate(node_disk_bytes_written{instance=\"$server:9100\", device=~\"sda.*\"}[5m]))",
       "legendFormat": "bytes_written"
      }
     ]
    },
    {
     "title": "IOPS",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 31 },
     "yaxes": [
      { "format": "short", "label": "IOPS" }
     ],
     "targets": [
      {
       "expr": "sum(irate(node_disk_writes_completed_total{instance=\"$server:9100\", device=~\"sd.*\"}[5m])) or sum(irate(node_disk_writes_completed{instance=\"$server:9100\", device=~\"sd.*\"}[5m]))",
       "legendFormat": "Disk writes completed/s"
      },
      {
       "expr": "sum(irate(node_disk_reads_completed_total{instance=\"$server:9100\", device=~\"sd.*\"}[5m])) or sum(irate(node_disk_reads_completed{instance=\"$server:9100\", device=~\"sd.*\"}[5m]))",
       "legendFormat": "Disk reads completed/s"
      }
     ]
    }
   ]
  }
 ]
}