{
 "title": "Nginx exporter",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "server_env",
    "label": "Environment",
    "query": "label_values(prometheus_config_last_reload_successful, server_env)"
   },
   { "name": "data_source", "label": "Data source", "query": "prometheus" },
   {
    "name": "project",
    "label": "Project",
    "query": "label_values(nginx_up{server_env=~\"$server_env\"},project)"
   },
   {
    "name": "hostname",
    "label": "Host",
    "query": "label_values(nginx_up{server_env=~\"$server_env\",project=~\"$project\"}, hostname)"
   },
   {
    "name": "limit",
    "query": "1,2,3,4,5,6,7,8,9,10,15,20,25,30,40,50,70,100,9999"
   }
  ]
 },
 "panels": [
  {
   "title": "Exporter status",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Nginx exporter status",
     "type": "graph",
     "description": "1 = OK",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 1 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "up{instance=~\".*:9113\",hostname=~\"$hostname\",server_env=~\"$server_env\",project=~\"$project\"}",
       "legendFormat": "{{hostname}} - {{instance}}"
      }
     ]
    },
    {
     "title": "Nginx exporter scrape status",
     "type": "graph",
     "description": "1 = OK",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 7 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "nginx_up{hostname=~\"$hostname\",server_env=~\"$server_env\",project=~\"$project\"}",
       "legendFormat": "{{hostname}} - {{instance}}"
      }
     ]
    }
   ]
  },
  { "title": "Connections", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  {
   "title": "Active",
   "type": "graph",
   "description": "Active client connections",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 2 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "nginx_connections_active{hostname=~\"$hostname\",server_env=~\"$server_env\",project=~\"$project\"}",
     "legendFormat": "{{hostname}} - {{instance}}"
    }
   ]
  },
  {
   "title": "Reading",
   "type": "graph",
   "description": "Connections where NGINX is reading the request header",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "nginx_connections_reading{hostname=~\"$hostname\",server_env=~\"$server_env\",project=~\"$project\"}",
     "legendFormat": "{{hostname}} - {{instance}}"
    }
   ]
  },
  {
   "title": "Idle",
   "type": "graph",
   "description": "Idle client connections",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "nginx_connections_waiting{hostname=~\"$hostname\",server_env=~\"$server_env\",project=~\"$project\"}",
     "legendFormat": "{{hostname}} - {{instance}}"
    }
   ]
  },
  {
   "title": "Writing",
   "type": "graph",
   "description": "Connections where NGINX is writing the response back to the client",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "nginx_connections_writing{hostname=~\"$hostname\",server_env=~\"$server_env\",project=~\"$project\"}",
     "legendFormat": "{{hostname}} - {{instance}}"
    }
   ]
  },
  {
   "title": "Accepted",
   "type": "graph",
   "description": "Accepted client connections",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(nginx_connections_accepted{hostname=~\"$hostname\",server_env=~\"$server_env\",project=~\"$project\"}[5m])",
     "legendFormat": "{{hostname}} - {{instance}}"
    }
   ]
  },
  {
   "title": "Handled",
   "type": "graph",
   "description": "Handled client connections",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(nginx_connections_handled{hostname=~\"$hostname\",server_env=~\"$server_env\",project=~\"$project\"}[5m])",
     "legendFormat": "{{hostname}} - {{instance}}"
    }
   ]
  },
  {
   "title": "Total",
   "type": "graph",
   "description": "Total http requests",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 38 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(nginx_http_requests_total{hostname=~\"$hostname\",server_env=~\"$server_env\",project=~\"$project\"}[5m])",
     "legendFormat": "{{hostname}} - {{instance}}"
    }
   ]
  },
  {
   "title": "Build info",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 44 },
   "collapsed": true,
   "panels": [
    {
     "title": "Nginx exporter scrape status",
     "type": "graph",
     "description": "1 = OK",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 3 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "nginxexporter_build_info{hostname=~\"$hostname\",server_env=~\"$server_env\",project=~\"$project\"}",
       "legendFormat": "{{hostname}} - {{instance}} - version {{version}} - commit {{gitCommit}}"
      }
     ]
    }
   ]
  }
 ]
}