{
 "title": "Nginx exporter custom",
 "description": "Show haproxy stats per host",
 "tags": [ "nginx" ],
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "job",
    "label": "Job",
    "query": "label_values(node_monit{key=\"status\",type=\"system\"}, job)"
   },
   {
    "name": "node",
    "label": "Host:",
    "query": "label_values(nginx_up{job=~\"$job\",instance=~\".*:9113\"}, instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "Requests counter",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(nginx_http_requests_total{instance=\"$node\"}[5m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Connections live",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "nginx_connections_writing{instance=\"$node\"}",
     "legendFormat": "Writing"
    },
    {
     "expr": "nginx_connections_waiting{instance=\"$node\"}",
     "legendFormat": "Waiting"
    },
    {
     "expr": "nginx_connections_reading{instance=\"$node\"}",
     "legendFormat": "Reading"
    },
    {
     "expr": "nginx_connections_active{instance=\"$node\"}",
     "legendFormat": "Active"
    }
   ]
  },
  {
   "title": "Connections counters",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(nginx_connections_handled{instance=\"$node\"}[5m])",
     "legendFormat": "Handled"
    },
    {
     "expr": "rate(nginx_connections_accepted{instance=\"$node\"}[5m])",
     "legendFormat": "Accepted"
    }
   ]
  },
  {
   "title": "Nginx status (up/down)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "nginx_up{instance=\"$node\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}