{
 "title": "Node_exporter",
 "tags": [
  "prometheus",
  "eks"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "server_env",
    "label": "Environment",
    "query": "label_values(prometheus_config_last_reload_successful, server_env)"
   },
   { "name": "data_source", "label": "Data source", "query": "prometheus" },
   {
    "name": "project",
    "label": "Project",
    "query": "label_values(node_load1{server_env=~\"$server_env\"},project)"
   },
   {
    "name": "hostname",
    "label": "Host name",
    "query": "label_values(node_load1{server_env=~\"$server_env\",project=~\"$project\"},hostname)"
   },
   {
    "name": "mountpoint",
    "label": "Mount point",
    "query": "label_values(node_filesystem_avail_bytes{hostname=~\"$hostname\",project=~\"$project\",server_env=~\"$server_env\"},mountpoint)"
   },
   {
    "name": "limit",
    "query": "1,2,3,4,5,6,7,8,9,10,15,20,25,30,40,50,70,100,9999"
   }
  ]
 },
 "panels": [
  {
   "title": "Exporter",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Node exporter scrape status (bottom $limit)",
     "type": "graph",
     "description": "1 - OK\n0 - Error",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 1 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "bottomk($limit, up{job!~\"inventory only.*\",instance=~\".*:9100\",server_env=~\"$server_env\",hostname=~\"$hostname\",project=~\"$project\"})",
       "legendFormat": "{{ hostname }}"
      }
     ]
    },
    {
     "title": "Node collectors status (bottom $limit)",
     "type": "graph",
     "description": "1 - OK\n0 - Error",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 7 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "bottomk($limit, node_scrape_collector_success{server_env=~\"$server_env\",hostname=~\"$hostname\",project=~\"$project\"})",
       "legendFormat": "{{ hostname }} {{collector}}"
      }
     ]
    },
    {
     "title": "Node exporter text file scrape status (topk $limit)",
     "type": "graph",
     "description": "1 - Error\n0 - Ok",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 13 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "topk($limit, node_textfile_scrape_error{server_env=~\"$server_env\",hostname=~\"$hostname\",project=~\"$project\"})",
       "legendFormat": "{{hostname}}"
      }
     ]
    }
   ]
  },
  { "title": "System", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  {
   "title": "LA1 (top $limit)",
   "type": "graph",
   "description": "Load Averages",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 2 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk($limit, node_load1{server_env=~\"$server_env\",hostname=~\"$hostname\",project=~\"$project\"})",
     "legendFormat": "{{hostname}}"
    },
    {
     "expr": "max(instance:node_cpus:count{server_env=~\"$server_env\",hostname=~\"$hostname\"})",
     "legendFormat": "Max number of cores"
    }
   ]
  },
  {
   "title": "Uptime (bottom $limit)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "bottomk($limit, node_time_seconds{server_env=~\"$server_env\",hostname=~\"$hostname\",project=~\"$project\"} - node_boot_time_seconds)",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU in use (top $limit)",
     "type": "graph",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 15 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "topk($limit, 1 - avg by (hostname) (irate(node_cpu_seconds_total{mode=\"idle\",server_env=~\"$server_env\",hostname=~\"$hostname\",project=~\"$project\"}[5m])))",
       "legendFormat": "{{hostname}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Memory",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 },
   "collapsed": true,
   "panels": [
    {
     "title": "Memory in use % (top $limit)",
     "type": "graph",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 22 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "topk($limit, (node_memory_MemTotal_bytes{server_env=~\"$server_env\",hostname=~\"$hostname\",project=~\"$project\"} - node_memory_MemAvailable_bytes) / node_memory_MemTotal_bytes)",
       "legendFormat": "{{hostname}}"
      }
     ]
    },
    {
     "title": "Memory in use (top $limit)",
     "type": "graph",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 28 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "topk($limit, node_memory_MemTotal_bytes{server_env=~\"$server_env\",hostname=~\"$hostname\",project=~\"$project\"} - node_memory_MemAvailable_bytes)",
       "legendFormat": "{{hostname}}"
      },
      {
       "expr": "max(node_memory_MemTotal_bytes{server_env=~\"$server_env\",hostname=~\"$hostname\"})",
       "legendFormat": "Max memory"
      }
     ]
    }
   ]
  },
  {
   "title": "Network",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 },
   "collapsed": true,
   "panels": [
    {
     "title": "Network traffic (top $limit)",
     "type": "graph",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 35 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "topk($limit, irate(node_network_receive_bytes_total{server_env=~\"$server_env\",hostname=~\"$hostname\",project=~\"$project\"}[5m]))",
       "legendFormat": "{{hostname}} {{device}} Receive"
      },
      {
       "expr": "topk($limit, irate(node_network_transmit_bytes_total{server_env=~\"$server_env\",hostname=~\"$hostname\",project=~\"$project\"}[5m]))",
       "legendFormat": "{{hostname}} {{device}} Transmit"
      }
     ]
    },
    {
     "title": "Network packets (top $limit)",
     "type": "graph",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 41 },
     "yaxes": [
      { "format": "pps" }
     ],
     "targets": [
      {
       "expr": "topk($limit, irate(node_network_receive_packets_total{server_env=~\"$server_env\",hostname=~\"$hostname\",project=~\"$project\"}[5m]))",
       "legendFormat": "{{hostname}} {{device}} Receive"
      },
      {
       "expr": "topk($limit, irate(node_network_transmit_packets_total{server_env=~\"$server_env\",hostname=~\"$hostname\",project=~\"$project\"}[5m]))",
       "legendFormat": "{{hostname}} {{device}} Transmit"
      }
     ]
    }
   ]
  },
  {
   "title": "Disk",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "collapsed": true,
   "panels": [
    {
     "title": "Disk mounted as read only (top $limit)",
     "type": "graph",
     "description": "Disk mounted as read only:\n1 - True\n0 - False",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 48 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "topk($limit, node_filesystem_readonly{server_env=~\"$server_env\",hostname=~\"$hostname\",project=~\"$project\",mountpoint=~\"$mountpoint\"})",
       "legendFormat": "{{hostname}} - {{mountpoint}}"
      }
     ]
    },
    {
     "title": "Disk free % (bottom $limit)",
     "type": "graph",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 54 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "bottomk($limit, 100 * ( node_filesystem_avail_bytes{server_env=~\"$server_env\",hostname=~\"$hostname\",project=~\"$project\",mountpoint=~\"$mountpoint\"} / (node_filesystem_size_bytes - ( node_filesystem_free_bytes - node_filesystem_avail_bytes))))",
       "legendFormat": "{{hostname}} - {{mountpoint}}"
      }
     ]
    },
    {
     "title": "Disk free (bottom $limit)",
     "type": "graph",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 60 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "bottomk($limit, node_filesystem_free_bytes{server_env=~\"$server_env\",hostname=~\"$hostname\",project=~\"$project\",mountpoint=~\"$mountpoint\"})",
       "legendFormat": "{{hostname}} - {{mountpoint}}"
      }
     ]
    },
    {
     "title": "Disk inodes free (bottom $limit)",
     "type": "graph",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 66 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "bottomk($limit, node_filesystem_files_free{server_env=~\"$server_env\",hostname=~\"$hostname\",project=~\"$project\",mountpoint=~\"$mountpoint\"} / node_filesystem_files)",
       "legendFormat": "{{hostname}} - {{mountpoint}}"
      }
     ]
    },
    {
     "title": "Disk operations (top $limit)",
     "type": "graph",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 72 },
     "yaxes": [
      { "format": "iops", "label": "Bytes read (-) / write (+)" }
     ],
     "targets": [
      {
       "expr": "topk($limit, irate(node_disk_reads_completed_total{server_env=~\"$server_env\",hostname=~\"$hostname\",project=~\"$project\"}[5m]))",
       "legendFormat": "{{hostname}} - {{device}} - Read"
      },
      {
       "expr": "topk($limit, irate(node_disk_writes_completed_total{server_env=~\"$server_env\",hostname=~\"$hostname\",project=~\"$project\"}[5m]))",
       "legendFormat": "{{hostname}} - {{device}} - Write "
      }
     ]
    },
    {
     "title": "Disk bytes (top $limit)",
     "type": "graph",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 78 },
     "yaxes": [
      { "format": "Bps", "label": "Bytes read (-) / write (+)" }
     ],
     "targets": [
      {
       "expr": "topk($limit, irate(node_disk_read_bytes_total{server_env=~\"$server_env\",hostname=~\"$hostname\",project=~\"$project\"}[5m]))",
       "legendFormat": "{{hostname}} - {{device}} - Read bytes"
      },
      {
       "expr": "topk($limit, irate(node_disk_written_bytes_total{server_env=~\"$server_env\",hostname=~\"$hostname\",project=~\"$project\"}[5m]))",
       "legendFormat": "{{hostname}} - {{device}} - Write bytes"
      }
     ]
    }
   ]
  }
 ]
}