{
 "title": "Postgresql (postgres_exporter)",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "server_env",
    "label": "Environment",
    "query": "label_values(prometheus_config_last_reload_successful, server_env)"
   },
   { "name": "data_source", "label": "Data source", "query": "prometheus" },
   {
    "name": "project",
    "label": "Project",
    "query": "label_values(pg_up{server_env=~\"$server_env\"},project)"
   },
   {
    "name": "hostname",
    "label": "Host name",
    "query": "label_values(pg_up{server_env=~\"$server_env\",project=~\"$project\"},hostname)"
   },
   {
    "name": "database",
    "label": "Database",
    "query": "label_values(pg_stat_activity_count{server_env=~\"$server_env\",project=~\"$project\"},datname)"
   },
   {
    "name": "lock_mode",
    "label": "Lock mode",
    "query": "label_values(pg_locks_count{server_env=~\"$server_env\",project=~\"$project\"},mode)"
   },
   {
    "name": "connection_state",
    "label": "Connection state",
    "query": "label_values(pg_stat_activity_count{server_env=~\"$server_env\",project=~\"$project\"},state)"
   },
   {
    "name": "limit",
    "query": "1,2,3,4,5,6,7,8,9,10,15,20,25,30,40,50,70,100,9999"
   },
   { "name": "interval", "label": "Interval", "query": "20s,30s,40s,50s,1m,2m,3m,4m,5m" }
  ]
 },
 "panels": [
  {
   "title": "Exporter status",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Postgres exporter status (bottom $limit)",
     "type": "graph",
     "description": "OK = 1",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 1 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "bottomk($limit, up{instance=~\".*:9187\",server_env=~\"$server_env\",project=~\"$project\",hostname=~\"$hostname\"})",
       "legendFormat": "{{hostname}}"
      }
     ]
    },
    {
     "title": "Postgres exporter DB connection status (bottom $limit)",
     "type": "graph",
     "description": "OK = 1",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 7 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "bottomk($limit, pg_up{server_env=~\"$server_env\",project=~\"$project\",hostname=~\"$hostname\"})",
       "legendFormat": "{{hostname}}"
      }
     ]
    },
    {
     "title": "Postgres exporter scrape errors (top $limit)",
     "type": "graph",
     "description": "OK = 0",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 13 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "topk($limit, pg_exporter_last_scrape_error{server_env=~\"$server_env\",project=~\"$project\",hostname=~\"$hostname\"})",
       "legendFormat": "{{hostname}}"
      }
     ]
    }
   ]
  },
  { "title": "Connections", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  {
   "title": "Connections in use (top $limit)",
   "type": "graph",
   "description": "% of connections in  use",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 2 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "topk($limit, sum(pg_stat_activity_count{server_env=~\"$server_env\",project=~\"$project\",hostname=~\"$hostname\",datname=~\"$database\",state=~\"$connection_state\"}) by (hostname) / max(pg_settings_max_connections{server_env=~\"$server_env\",project=~\"$project\",hostname=~\"$hostname\"}) by (hostname))",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "Connections count (top $limit)",
   "type": "graph",
   "description": "Number of connections with state",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk($limit, pg_stat_activity_count{server_env=~\"$server_env\",project=~\"$project\",hostname=~\"$hostname\",datname=~\"$database\",state=~\"$connection_state\"})",
     "legendFormat": "{{hostname}} {{datname}} {{state}}"
    }
   ]
  },
  {
   "title": "Locks",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 },
   "collapsed": true,
   "panels": [
    {
     "title": "Locks count (top $limit)",
     "type": "graph",
     "description": "Number of locks",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 15 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "topk($limit, pg_locks_count{server_env=~\"$server_env\",project=~\"$project\",hostname=~\"$hostname\",datname=~\"$database\",mode=~\"$lock_mode\"})",
       "legendFormat": "{{hostname}} {{datname}} {{mode}}"
      }
     ]
    },
    {
     "title": "Deadlocks count (top $limit)",
     "type": "graph",
     "description": "Number of deadlocks detected per database",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 21 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "topk($limit, pg_stat_database_deadlocks{server_env=~\"$server_env\",project=~\"$project\",hostname=~\"$hostname\",datname=~\"$database\"})",
       "legendFormat": "{{hostname}} {{datname}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Rows counters",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 },
   "collapsed": true,
   "panels": [
    {
     "title": "Rows inserted  (top $limit)",
     "type": "graph",
     "description": "Number of rows inserted by queries per database",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 16 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "topk($limit, rate(pg_stat_database_tup_inserted{server_env=~\"$server_env\",project=~\"$project\",hostname=~\"$hostname\",datname=~\"$database\"}[$interval]))",
       "legendFormat": "{{hostname}} {{datname}}"
      }
     ]
    },
    {
     "title": "Rows readed  (top $limit)",
     "type": "graph",
     "description": "Number of rows readed by queries per database",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 22 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "topk($limit, rate(pg_stat_database_tup_fetched{server_env=~\"$server_env\",project=~\"$project\",hostname=~\"$hostname\",datname=~\"$database\"}[$interval]))",
       "legendFormat": "{{hostname}} {{datname}}"
      }
     ]
    },
    {
     "title": "Rows returned  (top $limit)",
     "type": "graph",
     "description": "Number of rows returned by queries per database",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 28 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "topk($limit, rate(pg_stat_database_tup_returned{server_env=~\"$server_env\",project=~\"$project\",hostname=~\"$hostname\",datname=~\"$database\"}[$interval]))",
       "legendFormat": "{{hostname}} {{datname}}"
      }
     ]
    },
    {
     "title": "Rows deleted  (top $limit)",
     "type": "graph",
     "description": "Number of rows deleted by queries per database",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 34 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "topk($limit, rate(pg_stat_database_tup_deleted{server_env=~\"$server_env\",project=~\"$project\",hostname=~\"$hostname\",datname=~\"$database\"}[$interval]))",
       "legendFormat": "{{hostname}} {{datname}}"
      }
     ]
    },
    {
     "title": "Rows updated  (top $limit)",
     "type": "graph",
     "description": "Number of rows updated by queries per database",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 40 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "topk($limit, rate(pg_stat_database_tup_updated{server_env=~\"$server_env\",project=~\"$project\",hostname=~\"$hostname\",datname=~\"$database\"}[$interval]))",
       "legendFormat": "{{hostname}} {{datname}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Cache",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 },
   "collapsed": true,
   "panels": [
    {
     "title": "Disk blocks from buffer cache (top $limit)",
     "type": "graph",
     "description": "Number of times disk blocks were found already in the buffer cache, so that a read was not necessary (this only inclu des hits in the PostgreSQL buffer cache, not the operating system's file system cache)",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 17 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "topk($limit, rate(pg_stat_database_blks_hit{server_env=~\"$server_env\",project=~\"$project\",hostname=~\"$hostname\",datname=~\"$database\"}[$interval]))",
       "legendFormat": "{{hostname}} {{datname}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Transactions",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "collapsed": true,
   "panels": [
    {
     "title": "Transactions committed  (top $limit)",
     "type": "graph",
     "description": "Number of transactions per database that have been committed",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 18 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "topk($limit, rate(pg_stat_database_xact_commit{server_env=~\"$server_env\",project=~\"$project\",hostname=~\"$hostname\",datname=~\"$database\"}[$interval]))",
       "legendFormat": "{{hostname}} {{datname}}"
      }
     ]
    },
    {
     "title": "Transactions rolled back  (top $limit)",
     "type": "graph",
     "description": "Number of transactions per database that have been rolled back",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 24 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "topk($limit, rate(pg_stat_database_xact_rollback{server_env=~\"$server_env\",project=~\"$project\",hostname=~\"$hostname\",datname=~\"$database\"}[$interval]))",
       "legendFormat": "{{hostname}} {{datname}}"
      }
     ]
    },
    {
     "title": "Max active transaction duration  (top $limit)",
     "type": "graph",
     "description": "Max duration in seconds any active transaction has been running",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 30 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "topk($limit, pg_stat_activity_max_tx_duration{server_env=~\"$server_env\",project=~\"$project\",hostname=~\"$hostname\",datname=~\"$database\",state=~\"$connection_state\"})",
       "legendFormat": "{{hostname}} {{datname}} {{state}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Temporary files",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "collapsed": true,
   "panels": [
    {
     "title": "Temporary files created (top $limit)",
     "type": "graph",
     "description": "Number of temporary files created by queries per database. All temporary files are counted, regardless of why t he temporary file was created (e.g., sorting or hashing), and regardless of the log_temp_files setting.",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 19 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "topk($limit, rate(pg_stat_database_temp_files{server_env=~\"$server_env\",project=~\"$project\",hostname=~\"$hostname\",datname=~\"$database\"}[$interval]))",
       "legendFormat": "{{hostname}} {{datname}}"
      }
     ]
    },
    {
     "title": "Data written to temporary files  (top $limit)",
     "type": "graph",
     "description": "Total amount of data written to temporary files by queries per database. All temporary files are counted, regar dless of why the temporary file was created, and regardless of the log_temp_files setting.",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 25 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "topk($limit, rate(pg_stat_database_temp_bytes{server_env=~\"$server_env\",project=~\"$project\",hostname=~\"$hostname\",datname=~\"$database\"}[$interval]))",
       "legendFormat": "{{hostname}} {{datname}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Conflicts",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 },
   "collapsed": true,
   "panels": [
    {
     "title": "Number of queries canceled due to conflicts  (top $limit)",
     "type": "graph",
     "description": "Number of queries canceled due to conflicts with recovery per database. (Conflicts occur only on standby servers ; see pg_stat_database_conflicts for details.)",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 20 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "topk($limit, rate(pg_stat_database_conflicts{server_env=~\"$server_env\",project=~\"$project\",hostname=~\"$hostname\",datname=~\"$database\"}[$interval]))",
       "legendFormat": "{{hostname}} {{datname}}"
      }
     ]
    }
   ]
  }
 ]
}