{
 "title": "Prometheus metrics",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "server_env",
    "label": "Environment",
    "query": "label_values(prometheus_config_last_reload_successful, server_env)"
   },
   { "name": "data_source", "label": "Data source", "query": "prometheus" },
   {
    "name": "project",
    "label": "Project",
    "query": "label_values(prometheus_config_last_reload_successful{server_env=~\"$server_env\"},project)"
   },
   {
    "name": "hostname",
    "label": "Host name",
    "query": "label_values(prometheus_config_last_reload_successful{server_env=~\"$server_env\",project=~\"$project\"},hostname)"
   },
   {
    "name": "reason",
    "label": "Reason",
    "query": "label_values(net_conntrack_dialer_conn_failed_total{server_env=~\"$server_env\",project=~\"$project\"},reason)"
   },
   {
    "name": "dialer_name",
    "label": "Dialer name",
    "query": "label_values(net_conntrack_dialer_conn_failed_total{server_env=~\"$server_env\",project=~\"$project\"},dialer_name)"
   },
   {
    "name": "limit",
    "query": "1,2,3,4,5,6,7,8,9,10,15,20,25,30,40,50,70,100,9999"
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": "label_values(prometheus_config_last_reload_successful{server_env=~\"$server_env\",project=~\"$project\"},instance)"
   }
  ]
 },
 "panels": [
  { "title": "Exporter", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Prometheus scrape status (bottom $limit)",
   "type": "graph",
   "description": "OK = 1",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "bottomk($limit, up{instance=~\"$instance\",server_env=~\"$server_env\",project=~\"$project\",hostname=~\"$hostname\"})",
     "legendFormat": "{{hostname}} {{instance}}"
    }
   ]
  },
  {
   "title": "Reload success (bottom $limit)",
   "type": "graph",
   "description": "OK = 1",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "bottomk($limit, prometheus_config_last_reload_successful{instance=~\"$instance\",server_env=~\"$server_env\",project=~\"$project\",hostname=~\"$hostname\"})",
     "legendFormat": "{{hostname}} {{instance}}"
    }
   ]
  },
  { "title": "Errors", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "Connections failed (top$limit)",
   "type": "graph",
   "description": "OK = 0",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk($limit, delta(net_conntrack_dialer_conn_failed_total{instance=~\"$instance\",server_env=~\"$server_env\",project=~\"$project\",hostname=~\"$hostname\",dialer_name=~\"$dialer_name\",reason=~\"$reason\"}[5m]))",
     "legendFormat": "{{hostname}} {{reason}} {{dialer_name}}"
    }
   ]
  }
 ]
}