{
 "title": "Proxysql (proxysql_exporter)",
 "tags": [ "prometheus" ],
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "server_env",
    "label": "Environment",
    "query": "label_values(prometheus_config_last_reload_successful, server_env)"
   },
   { "name": "data_source", "label": "Data source", "query": "prometheus" },
   {
    "name": "project",
    "label": "Project",
    "query": "label_values(node_load1{server_env=~\"$server_env\"},project)"
   },
   {
    "name": "hostname",
    "label": "Host name",
    "query": "label_values(node_load1{server_env=~\"$server_env\",project=~\"$project\"},hostname)"
   },
   {
    "name": "limit",
    "query": "1,2,3,4,5,6,7,8,9,10,15,20,25,30,40,50,70,100,9999"
   }
  ]
 },
 "panels": [
  {
   "title": "Exporter",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Proxysql exporter scrape status (bottom $limit)",
     "type": "graph",
     "description": "1 = OK",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 1 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "bottomk($limit, up{instance=~\".*:42004\",server_env=~\"$server_env\",hostname=~\"$hostname\",project=~\"$project\"})",
       "legendFormat": "{{ hostname }}"
      }
     ]
    },
    {
     "title": "Proxysql collector status (bottom $limit)",
     "type": "graph",
     "description": "1 = OK",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 7 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "bottomk($limit, proxysql_up{server_env=~\"$server_env\",hostname=~\"$hostname\",project=~\"$project\"})",
       "legendFormat": "{{ hostname }} {{collector}}"
      }
     ]
    }
   ]
  },
  { "title": "Endpoints", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  {
   "title": "Endpoints status (bottom $limit)",
   "type": "graph",
   "description": "1 = OK",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 2 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "bottomk($limit, proxysql_connection_pool_status{server_env=~\"$server_env\",hostname=~\"$hostname\",project=~\"$project\"})",
     "legendFormat": "{{ hostname }} - {{endpoint}} - {{hostgroup}}"
    }
   ]
  }
 ]
}