{
 "title": "RabbitMQ",
 "description": "Rabbitmq stats and alerting using RabbitMQ Exporter (https://github.com/kbudde/rabbitmq_exporter)",
 "tags": [
  "rabbitmq",
  "prometheus"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "node",
    "query": "label_values(rabbitmq_running, node)"
   },
   {
    "name": "job",
    "query": "label_values(rabbitmq_running, job)"
   }
  ]
 },
 "panels": [
  {
   "title": "Messages per Queue",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rabbitmq_queue_messages{job=~\"$job\"}",
     "legendFormat": "{{queue}}"
    }
   ]
  },
  {
   "title": "Messages status",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (queue)(rabbitmq_queue_messages_ready{job=~\"$job\"})",
     "legendFormat": "{{queue}}:ready"
    },
    {
     "expr": "sum by (queue)(rabbitmq_queue_messages_published_total{job=~\"$job\"})",
     "legendFormat": "{{queue}}:published"
    },
    {
     "expr": "sum by (queue)(rabbitmq_queue_messages_delivered_total{job=~\"$job\"})",
     "legendFormat": "{{queue}}:delivered"
    },
    {
     "expr": "sum by (queue)(rabbitmq_queue_messages_unacknowledged{job=~\"$job\"})",
     "legendFormat": "{{queue}}:unack"
    }
   ]
  },
  {
   "title": "Used memory",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "rabbitmq_node_mem_used{job=~\"$job\"}",
     "legendFormat": "{{node}}:used"
    },
    {
     "expr": "rabbitmq_node_mem_limit{job=~\"$job\"}",
     "legendFormat": "{{node}}:limit"
    }
   ]
  },
  {
   "title": "Free disk space",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "rabbitmq_node_disk_free{job=~\"$job\"}",
     "legendFormat": "{{node}}:free"
    },
    {
     "expr": "rabbitmq_node_disk_free_limit{job=~\"$job\"}",
     "legendFormat": "{{node}}:limit"
    }
   ]
  },
  {
   "title": "Alarm status",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rabbitmq_node_disk_free_alarm{job=~\"$job\"}",
     "legendFormat": "Disk alarm {{ job }}"
    },
    {
     "expr": "rabbitmq_node_mem_alarm{job=~\"$job\"}",
     "legendFormat": "Memory alarm {{ job }}"
    }
   ]
  }
 ]
}