{
 "title": "Shalb SNMP",
 "description": "Show switch stats",
 "tags": [
  "snmp",
  "prometheus"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "host",
    "label": "Host:",
    "query": "label_values(snmp_interface_out_bytes_total{net_dev_index=\"1\"}, host)"
   }
  ]
 },
 "panels": [
  {
   "title": "Network Out bytes per interface",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "irate(snmp_interface_out_bytes_total{host=\"$host\"}[1m])",
     "legendFormat": "Interface {{net_dev_index}} Out"
    }
   ]
  },
  {
   "title": "Network Out packets per interface",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "expr": "irate(snmp_interface_out_packets_total{host=\"$host\"}[1m])",
     "legendFormat": "Interface {{net_dev_index}}  Out"
    }
   ]
  },
  {
   "title": "Network In bytes per interface",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "irate(snmp_interface_in_bytes_total{host=\"$host\"}[1m])",
     "legendFormat": "Interface {{net_dev_index}}  In"
    }
   ]
  },
  {
   "title": "Network In packets per interface",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "expr": "irate(snmp_interface_in_packets_total{host=\"$host\"}[1m])",
     "legendFormat": "Interface {{net_dev_index}}  In"
    }
   ]
  },
  {
   "title": "Network Out Errors per interface",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "expr": "irate(snmp_interface_out_errors_total{host=\"$host\"}[1m])",
     "legendFormat": "Interface {{net_dev_index}}  Out"
    }
   ]
  },
  {
   "title": "Network In Errors per interface",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "expr": "irate(snmp_interface_in_errors_total{host=\"$host\"}[1m])",
     "legendFormat": "Interface {{net_dev_index}}  In"
    }
   ]
  }
 ]
}