---
- name: restart_init_service
  command: "/etc/init.d/monit_collector restart"

- name: restart_systemd_service
  shell: "systemctl daemon-reload && systemctl restart monit_collector.service"

- name: restart_amazon_service
  shell: "/etc/init.d/monit_collector restart && chkconfig --level 2345 monit_collector on"

- name: restart_debian_service
  command: "/etc/init.d/monit_collector restart"

- name: monit_reload
  shell: "monit -t && monit reload"

