---
- name: install rsnapshot [Debian] 
  apt:
    name: "{{ item }}"
    state: latest
    update_cache: true
    cache_valid_time: "{{ apt_update_cache_valid_time | default(3600) }}"
  with_items: 
    - "rsnapshot"

