apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-main-config
  namespace: monitoring
  labels:
    app: prometheus
data:
  prometheus.yml: |+
    global:
      scrape_interval:     10s
      evaluation_interval: 10s

    scrape_configs:
      - job_name: 'prometheus_exporter kubernetes'
        kubernetes_sd_configs:
        - role: pod
        relabel_configs:
        - source_labels: [__meta_kubernetes_pod_annotation_monitoring]
          regex: "true"
          action: keep
        - source_labels: [__address__]
          regex: ".*:9090"
          action: keep
        - source_labels: [__meta_kubernetes_namespace]
          target_label: namespace
        - source_labels: [__meta_kubernetes_pod_node_name]
          target_label: node_name
        - source_labels: [__meta_kubernetes_pod_name]
          target_label: pod_name
        - source_labels: [__meta_kubernetes_pod_container_name]
          target_label: container_name


      - job_name: 'node_exporter kubernetes'
        params:
          collect[]:
          - stat
          - diskstats
          - cpu
          - filesystem
          - loadavg
          - meminfo
          - netdev
          - textfile
          - time
          - timex
          - vmstat
        kubernetes_sd_configs:
        - role: pod
        relabel_configs:
        - source_labels: [__meta_kubernetes_pod_annotation_monitoring]
          regex: "true"
          action: keep
        - source_labels: [__address__]
          regex: ".*:9100"
          action: keep
        - source_labels: [__meta_kubernetes_pod_node_name]
          target_label: hostname
        - source_labels: [__meta_kubernetes_namespace]
          target_label: namespace
        - source_labels: [__meta_kubernetes_pod_node_name]
          target_label: node_name
        - source_labels: [__meta_kubernetes_pod_name]
          target_label: pod_name
        - source_labels: [__meta_kubernetes_pod_container_name]
          target_label: container_name
        metric_relabel_configs:
          - source_labels: [ mountpoint ]
            regex: '/run'
            action: drop
          - source_labels: [ __name__ ]
            regex: 'up|node_boot_time_seconds|node_memory_MemAvailable_bytes|node_time_seconds|node_memory_MemTotal_bytes|node_network_receive_bytes_total|node_network_transmit_bytes_total|node_disk_read_bytes_total|node_disk_written_bytes_total|node_network_receive_packets_total|node_network_transmit_packets_total|node_disk_writes_completed_total|node_disk_reads_completed_total|node_filesystem_size_bytes|node_filesystem_free_bytes|node_condition|node_cpu|node_cpu_seconds_total|node_cpus|node_filesystem_avail_bytes|node_filesystem_files|node_filesystem_files_free|node_filesystem_readonly|node_load1|node_mail_queue|node_monit|node_name|node_scrape_collector_success|node_stats_up|node_textfile_scrape_error|node_timex_sync_status'
            action: keep


      - job_name: "kubernetes_exporter kubernetes"
        kubernetes_sd_configs:
        - role: pod
        relabel_configs:
        - source_labels: [__meta_kubernetes_pod_annotation_monitoring]
          regex: "true"
          action: keep
        - source_labels: [__address__]
          regex: ".*:9610"
          action: keep
       #- source_labels: [__meta_kubernetes_namespace]
       #  target_label: namespace
       #- source_labels: [__meta_kubernetes_pod_node_name]
       #  target_label: node_name
       #- source_labels: [__meta_kubernetes_pod_name]
       #  target_label: pod_name
       #- source_labels: [__meta_kubernetes_pod_container_name]
       #  target_label: container_name
        - source_labels: [pod_name]
          regex: '(.*)-[0-9a-z]+'
          target_label: service
          replacement: '$1'


      - job_name: 'cadvisor kubernetes'
        scheme: https
        tls_config:
          ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
        bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
        kubernetes_sd_configs:
        - role: node
        relabel_configs:
        - action: labelmap
          regex: __meta_kubernetes_node_label_(.+)
        - target_label: __address__
          replacement: kubernetes.default.svc:443
        - source_labels: [__meta_kubernetes_node_name]
          regex: (.+)
          target_label: __metrics_path__
          replacement: /api/v1/nodes/${1}/proxy/metrics/cadvisor


      - job_name: 'kubernetes-apiservers'
        kubernetes_sd_configs:
        - role: endpoints
        scheme: https
        tls_config:
          ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
        bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
        relabel_configs:
        - source_labels: [__meta_kubernetes_namespace, __meta_kubernetes_service_name, __meta_kubernetes_endpoint_port_name]
          action: keep
          regex: default;kubernetes;https
        metric_relabel_configs:
          - source_labels: [ __name__ ]
            regex: 'apiserver_request_count|APIServiceOpenAPIAggregationControllerQueue1_depth|APIServiceRegistrationController_depth|AvailableConditionController_depth|DiscoveryController_depth|admission_quota_controller_depth|autoregister_depth|crdEstablishing_depth|APIServiceOpenAPIAggregationControllerQueue1_adds|APIServiceRegistrationController_adds|AvailableConditionController_adds|DiscoveryController_adds|admission_quota_controller_adds|autoregister_adds|crdEstablishing_adds|get_token_fail_count|get_token_count|etcd_object_counts'
            action: keep

     #- job_name: 'kubernetes nodes'
     #  scheme: https
     #  tls_config:
     #    ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
     #  bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
     #  kubernetes_sd_configs:
     #  - role: node
     #  relabel_configs:
     #  - action: labelmap
     #    regex: __meta_kubernetes_node_label_(.+)
     #  - target_label: __address__
     #    replacement: kubernetes.default.svc:443
     #  - source_labels: [__meta_kubernetes_node_name]
     #    regex: (.+)
     #    target_label: __metrics_path__
     #    replacement: /api/v1/nodes/${1}/proxy/metrics

     #- job_name: 'kubernetes-service-endpoints'
     #  kubernetes_sd_configs:
     #  - role: endpoints
     #  relabel_configs:
     #  - source_labels: [__meta_kubernetes_service_annotation_prometheus_io_scrape]
     #    regex: "true"
     #    action: keep
     #  - source_labels: [__address__]
     #    regex: ".*:9153;.*:44135;.*:8085"
     #    action: keep
     #  - action: labelmap
     #    regex: __meta_kubernetes_service_label_(.+)
     #  - source_labels: [__meta_kubernetes_namespace]
     #    action: replace
     #    target_label: kubernetes_namespace
     #  - source_labels: [__meta_kubernetes_service_name]
     #    action: replace
     #    target_label: kubernetes_name

     #- job_name: 'blackbox-exporter kubernetes services'
     #  metrics_path: /probe
     #  params:
     #    module: [http_2xx]
     #  kubernetes_sd_configs:
     #  - role: service
     #  relabel_configs:
     # #- source_labels: [__meta_kubernetes_service_name]
     # #  regex: "certificates|learning-objective-maker|lti-service|pdf-converter|progress-storage"
     # #  action: keep
     #  - source_labels: [__address__]
     #    target_label: instance
     #  - source_labels: [__address__]
     #    target_label: __param_target
     #  - target_label: __address__
     #    replacement: blackbox-exporter:9115
     #  - target_label: request
     #    replacement: '/'
     #  - source_labels: [__meta_kubernetes_namespace]
     #    target_label: namespace
     #  - source_labels: [__meta_kubernetes_service_name]
     #    target_label: service_name

