#!/bin/sh

# /etc/init.d/node_exporter
#
# Written by gelo
#


### BEGIN INIT INFO
# Provides:          node_exporter
# Required-Start:    $remote_fs
# Required-Stop:     $remote_fs
# Should-Start:      $all
# Should-Stop:       $all
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: prometheus node exporter
# Description:       prometheus node exporter
### END INIT INFO

# {{ ansible_managed }}

start() {
    start-stop-daemon --user {{ node_exporter_monitoring_user }} --pidfile /run/node_exporter.pid --background --make-pidfile --start --exec /usr/local/bin/node_exporter -- --collector.textfile.directory={{ node_exporter_textfile_directory }}
}

stop() {
    start-stop-daemon --user {{ node_exporter_monitoring_user }} --pidfile /run/node_exporter.pid --stop
}

restart() {
    stop
    sleep 1
    start
}

case "$1" in
    start)
        start
        ;;
    stop)
        stop
        ;;
    restart)
        restart
        ;;
    *)
        echo $"Usage: $0 {start|stop|restart}"
        exit 2
esac
exit $?

