#!/bin/bash

start() {
    /etc/local.d/node_exporter.start
}

stop() {
    /etc/local.d/node_exporter.stop
}

restart() {
    stop
    sleep 1
    start
}

case "$1" in
    start)
        start
        ;;
    stop)
        stop
        ;;
    restart)
        restart
        ;;
    *)
        echo $"Usage: $0 {start|stop|restart}"
        exit 2
esac
exit $?

