groups:
  - name: blackbox_exporter http checks host up
    rules:
      - alert: "Http check fails P1"
        expr: probe_success{host_priority="P1"} != 1
        for: 1m
        annotations:
          summary: "Http check fails"
          description: 'Check host: "{{ $labels.instance }}" and find appropriate servers, which serving it to fix the problem.'
          grafana: "https://grafana.monitoring-test.shalb.com/d/eXqpy5DWk/http-checks-blackbox_exporter?panelId=2&fullscreen&orgId=1&var-server_env={{ $labels.server_env }}&var-project={{ $labels.project }}&var-instance={{ $labels.instance }}"
          access: "https://confluence.shalb.com/display/TEST/Access#Access-Grafana,Prometheus,Alertmanager"
          priority: "P1"

      - alert: "Http check fails P2"
        expr: probe_success{host_priority="P2"} != 1
        for: 2m
        annotations:
          summary: "Http check fails"
          description: 'Check host: "{{ $labels.instance }}" and find appropriate servers, which serving it to fix the problem.'
          grafana: "https://grafana.monitoring-test.shalb.com/d/eXqpy5DWk/http-checks-blackbox_exporter?panelId=2&fullscreen&orgId=1&var-server_env={{ $labels.server_env }}&var-project={{ $labels.project }}&var-instance={{ $labels.instance }}"
          access: "https://confluence.shalb.com/display/TEST/Access#Access-Grafana,Prometheus,Alertmanager"
          priority: "P2"

      - alert: "Http check fails P3"
        expr: probe_success{host_priority="P3"} != 1
        for: 5m
        annotations:
          summary: "Http check fails"
          description: 'Check host: "{{ $labels.instance }}" and find appropriate servers, which serving it to fix the problem.'
          grafana: "https://grafana.monitoring-test.shalb.com/d/eXqpy5DWk/http-checks-blackbox_exporter?panelId=2&fullscreen&orgId=1&var-server_env={{ $labels.server_env }}&var-project={{ $labels.project }}&var-instance={{ $labels.instance }}"
          access: "https://confluence.shalb.com/display/TEST/Access#Access-Grafana,Prometheus,Alertmanager"
          priority: "P3"

      - alert: "Http check fails P4"
        expr: probe_success{host_priority="P4"} != 1
        for: 10m
        annotations:
          summary: "Http check fails"
          description: 'Check host: "{{ $labels.instance }}" and find appropriate servers, which serving it to fix the problem.'
          grafana: "https://grafana.monitoring-test.shalb.com/d/eXqpy5DWk/http-checks-blackbox_exporter?panelId=2&fullscreen&orgId=1&var-server_env={{ $labels.server_env }}&var-project={{ $labels.project }}&var-instance={{ $labels.instance }}"
          access: "https://confluence.shalb.com/display/TEST/Access#Access-Grafana,Prometheus,Alertmanager"
          priority: "P4"

      - alert: "Http check fails P5"
        expr: probe_success{host_priority="P5"} != 1
        for: 20m
        annotations:
          summary: "Http check fails"
          description: 'Check host: "{{ $labels.instance }}" and find appropriate servers, which serving it to fix the problem.'
          grafana: "https://grafana.monitoring-test.shalb.com/d/eXqpy5DWk/http-checks-blackbox_exporter?panelId=2&fullscreen&orgId=1&var-server_env={{ $labels.server_env }}&var-project={{ $labels.project }}&var-instance={{ $labels.instance }}"
          access: "https://confluence.shalb.com/display/TEST/Access#Access-Grafana,Prometheus,Alertmanager"
          priority: "P5"


  - name: blackbox_exporter http checks ssl exiration
    rules:
      - alert: "Ssl will be expired in next 10 days"
        expr: (probe_ssl_earliest_cert_expiry - time())  / (3600 * 24) < 10
        annotations:
          summary: "Ssl will be expired in next 10 days"
          description: 'Renew certificate for host: "{{ $labels.instance }}" if it managed by us or ask customer to get new one and install it'
          grafana: "https://grafana.monitoring-test.shalb.com/d/eXqpy5DWk/http-checks-blackbox_exporter?panelId=7&fullscreen&orgId=1&var-server_env={{ $labels.server_env }}&var-project={{ $labels.project }}&var-instance={{ $labels.instance }}"
          access: "https://confluence.shalb.com/display/TEST/Access#Access-Grafana,Prometheus,Alertmanager"
          priority: "P5"


      - alert: "Ssl will be expired in next 2 days"
        expr: (probe_ssl_earliest_cert_expiry - time())  / (3600 * 24) < 2
        annotations:
          summary: "Ssl will be expired in next 2 days"
          description: 'Renew certificate for host: "{{ $labels.instance }}" if it managed by us or ask customer to get new one and install it'
          grafana: "https://grafana.monitoring-test.shalb.com/d/eXqpy5DWk/http-checks-blackbox_exporter?panelId=7&fullscreen&orgId=1&var-server_env={{ $labels.server_env }}&var-project={{ $labels.project }}&var-instance={{ $labels.instance }}"
          access: "https://confluence.shalb.com/display/TEST/Access#Access-Grafana,Prometheus,Alertmanager"
          priority: "P3"

