groups:
  - name: get number of cores
    rules:
    - record: instance:node_cpus:count
      expr: count(node_cpu_seconds_total{mode="idle"}) without (cpu,mode)


  - name: load alerts
    rules:
      - alert: "LA > 110% P5"
        expr: node_load1{host_priority="P5"} > (instance:node_cpus:count + 1)
        for: 60m
        annotations:
          summary: "LA > 110%: {{ $value }}"
          description: 'Check why LA is to high on host: "{{ $labels.hostname }}"'
          grafana: "https://grafana.monitoring-test.shalb.com/d/FymDFbpZk/node-exporter?panelId=21&fullscreen&orgId=1&var-server_env={{ $labels.server_env }}&var-project={{ $labels.project }}&var-hostname={{ $labels.hostname }}"
          access: "https://confluence.shalb.com/display/TEST/Access#Access-Grafana,Prometheus,Alertmanager"
          priority: "P3"

      - alert: "LA > 110% P4"
        expr: node_load1{host_priority="P4"} > (instance:node_cpus:count + 1)
        for: 30m
        annotations:
          summary: "LA > 110%: {{ $value }}"
          description: 'Check why LA is to high on host: "{{ $labels.hostname }}"'
          grafana: "https://grafana.monitoring-test.shalb.com/d/FymDFbpZk/node-exporter?panelId=21&fullscreen&orgId=1&var-server_env={{ $labels.server_env }}&var-project={{ $labels.project }}&var-hostname={{ $labels.hostname }}"
          access: "https://confluence.shalb.com/display/TEST/Access#Access-Grafana,Prometheus,Alertmanager"
          priority: "P3"

      - alert: "LA > 110% P3"
        expr: node_load1{host_priority="P3"} > (instance:node_cpus:count + 1)
        for: 15m
        annotations:
          summary: "LA > 110%: {{ $value }}"
          description: 'Check why LA is to high on host: "{{ $labels.hostname }}"'
          grafana: "https://grafana.monitoring-test.shalb.com/d/FymDFbpZk/node-exporter?panelId=21&fullscreen&orgId=1&var-server_env={{ $labels.server_env }}&var-project={{ $labels.project }}&var-hostname={{ $labels.hostname }}"
          access: "https://confluence.shalb.com/display/TEST/Access#Access-Grafana,Prometheus,Alertmanager"
          priority: "P3"

      - alert: "LA > 110% P2"
        expr: node_load1{host_priority="P2"} > (instance:node_cpus:count + 1)
        for: 7m
        annotations:
          summary: "LA > 110%: {{ $value }}"
          description: 'Check why LA is to high on host: "{{ $labels.hostname }}"'
          grafana: "https://grafana.monitoring-test.shalb.com/d/FymDFbpZk/node-exporter?panelId=21&fullscreen&orgId=1&var-server_env={{ $labels.server_env }}&var-project={{ $labels.project }}&var-hostname={{ $labels.hostname }}"
          access: "https://confluence.shalb.com/display/TEST/Access#Access-Grafana,Prometheus,Alertmanager"
          priority: "P3"

      - alert: "LA > 110% P1"
        expr: node_load1{host_priority="P1"} > (instance:node_cpus:count + 1)
        for: 3m
        annotations:
          summary: "LA > 110%: {{ $value }}"
          description: 'Check why LA is to high on host: "{{ $labels.hostname }}"'
          grafana: "https://grafana.monitoring-test.shalb.com/d/FymDFbpZk/node-exporter?panelId=21&fullscreen&orgId=1&var-server_env={{ $labels.server_env }}&var-project={{ $labels.project }}&var-hostname={{ $labels.hostname }}"
          access: "https://confluence.shalb.com/display/TEST/Access#Access-Grafana,Prometheus,Alertmanager"
          priority: "P3"

