groups:
  - name: "monit services check alerts"
    rules:
      - alert: "service check failed P5-1"
        expr: node_monit{host_priority=~"P[4-5]",type="process",key="status",name!~".*exporter|monit|monit_collector"} > 0
        for: 15m
        annotations:
          summary: 'check failed for service: "{{ $labels.name }}"'
          description: 'Go to host: "{{ $labels.hostname }}" and check why it is not running or service check failed; find more info in monit config (grep -r {{ $labels.name }} /etc/monit.d/); see monit log: /var/log/monit/monit.log'
          grafana: "https://grafana.monitoring-test.shalb.com/d/RGx4RH-ik/monit-exporter?panelId=4&fullscreen&orgId=1&var-server_env={{ $labels.server_env }}&var-project={{ $labels.project }}&var-hostname={{ $labels.hostname }}"
          access: "https://confluence.shalb.com/display/TEST/Access#Access-Grafana,Prometheus,Alertmanager"
          priority: "P5"

      - alert: "service check failed P5-2"
        expr: node_monit{host_priority=~"P[1-3]",priority="P5",type="process",key="status",name!~".*exporter|monit|monit_collector"} > 0
        for: 15m
        annotations:
          summary: 'check failed for service: "{{ $labels.name }}"'
          description: 'Go to host: "{{ $labels.hostname }}" and check why it is not running or service check failed; find more info in monit config (grep -r {{ $labels.name }} /etc/monit.d/); see monit log: /var/log/monit/monit.log'
          grafana: "https://grafana.monitoring-test.shalb.com/d/RGx4RH-ik/monit-exporter?panelId=4&fullscreen&orgId=1&var-server_env={{ $labels.server_env }}&var-project={{ $labels.project }}&var-hostname={{ $labels.hostname }}"
          access: "https://confluence.shalb.com/display/TEST/Access#Access-Grafana,Prometheus,Alertmanager"
          priority: "P5"

      - alert: "service check failed P4"
        expr: node_monit{host_priority=~"P[1-3]",priority="P4",type="process",key="status",name!~".*exporter|monit|monit_collector"} > 0
        for: 10m
        annotations:
          summary: 'check failed for service: "{{ $labels.name }}"'
          description: 'Go to host: "{{ $labels.hostname }}" and check why it is not running or service check failed; find more info in monit config (grep -r {{ $labels.name }} /etc/monit.d/); see monit log: /var/log/monit/monit.log'
          grafana: "https://grafana.monitoring-test.shalb.com/d/RGx4RH-ik/monit-exporter?panelId=4&fullscreen&orgId=1&var-server_env={{ $labels.server_env }}&var-project={{ $labels.project }}&var-hostname={{ $labels.hostname }}"
          access: "https://confluence.shalb.com/display/TEST/Access#Access-Grafana,Prometheus,Alertmanager"
          priority: "P4"

      - alert: "service check failed P3"
        expr: node_monit{host_priority=~"P[1-3]",priority="P3",type="process",key="status",name!~".*exporter|monit|monit_collector"} > 0
        for: 5m
        annotations:
          summary: 'check failed for service: "{{ $labels.name }}"'
          description: 'Go to host: "{{ $labels.hostname }}" and check why it is not running or service check failed; find more info in monit config (grep -r {{ $labels.name }} /etc/monit.d/); see monit log: /var/log/monit/monit.log'
          grafana: "https://grafana.monitoring-test.shalb.com/d/RGx4RH-ik/monit-exporter?panelId=4&fullscreen&orgId=1&var-server_env={{ $labels.server_env }}&var-project={{ $labels.project }}&var-hostname={{ $labels.hostname }}"
          access: "https://confluence.shalb.com/display/TEST/Access#Access-Grafana,Prometheus,Alertmanager"
          priority: "P3"

      - alert: "service check failed P2"
        expr: node_monit{host_priority=~"P[1-3]",priority="P2",type="process",key="status",name!~".*exporter|monit|monit_collector"} > 0
        for: 2m
        annotations:
          summary: 'check failed for service: "{{ $labels.name }}"'
          description: 'Go to host: "{{ $labels.hostname }}" and check why it is not running or service check failed; find more info in monit config (grep -r {{ $labels.name }} /etc/monit.d/); see monit log: /var/log/monit/monit.log'
          grafana: "https://grafana.monitoring-test.shalb.com/d/RGx4RH-ik/monit-exporter?panelId=4&fullscreen&orgId=1&var-server_env={{ $labels.server_env }}&var-project={{ $labels.project }}&var-hostname={{ $labels.hostname }}"
          access: "https://confluence.shalb.com/display/TEST/Access#Access-Grafana,Prometheus,Alertmanager"
          priority: "P2"

      - alert: "service check failed P1"
        expr: node_monit{host_priority=~"P[1-3]",priority="P1",type="process",key="status",name!~".*exporter|monit|monit_collector"} > 0
        for: 1m
        annotations:
          summary: 'check failed for service: "{{ $labels.name }}"'
          description: 'Go to host: "{{ $labels.hostname }}" and check why it is not running or service check failed; find more info in monit config (grep -r {{ $labels.name }} /etc/monit.d/); see monit log: /var/log/monit/monit.log'
          grafana: "https://grafana.monitoring-test.shalb.com/d/RGx4RH-ik/monit-exporter?panelId=4&fullscreen&orgId=1&var-server_env={{ $labels.server_env }}&var-project={{ $labels.project }}&var-hostname={{ $labels.hostname }}"
          access: "https://confluence.shalb.com/display/TEST/Access#Access-Grafana,Prometheus,Alertmanager"
          priority: "P1"

