groups:
  - name: http checks
    rules:
      - alert: "ssl will be expired in next 10 days"
        expr: node_monit{key="port_certificate_valid"} < 10
        for: 10m
        annotations:
          summary: '{{ $labels.name }}: ssl will be expired in next 10 days'
          description: 'Renew certificate for domain: "{{ $labels.name }}" if it managed by us or ask customer to get new one and install it'
          grafana: "https://grafana.monitoring-test.shalb.com/d/RGx4RH-ik/monit-exporter?panelId=4&fullscreen&orgId=1&var-server_env={{ $labels.server_env }}&var-project={{ $labels.project }}&var-hostname={{ $labels.hostname }}"
          access: "https://confluence.shalb.com/display/TEST/Access#Access-Grafana,Prometheus,Alertmanager"
          priority: "P5"

      - alert: "ssl will be expired in next 2 days"
        expr: node_monit{key="port_certificate_valid"} < 2
        for: 10m
        annotations:
          summary: '{{ $labels.name }}: ssl will be expired in next 2 days for domain: "{{ $labels.name }}"'
          description: 'Renew certificate for domain: "{{ $labels.name }}" if it managed by us or ask customer to get new one and install it'
          grafana: "https://grafana.monitoring-test.shalb.com/d/RGx4RH-ik/monit-exporter?panelId=4&fullscreen&orgId=1&var-server_env={{ $labels.server_env }}&var-project={{ $labels.project }}&var-hostname={{ $labels.hostname }}"
          access: "https://confluence.shalb.com/display/TEST/Access#Access-Grafana,Prometheus,Alertmanager"
          priority: "P3"

