alertmanager:
  alertmanagerSpec:
    storage:
      volumeClaimTemplate:
        spec:
         #storageClassName: gluster
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 5Gi
        selector: {}

