additionalPrometheusRules:
  - name: prometheus-federate-rule-file
    groups:
      - name: "prometheus federate alerts"
        rules:
          - alert: "prometheus federate fails"
            expr: up{instance=~".*:443", job=~"prometheus_federate_kuber"} != 1
            annotations:
              summary: "prometheus federate fails"
              description: 'prometheus federate scrape job fails for instance: "{{ $labels.instance }}"'
              grafana: "GRAFANA_NODE_EXPORTER_UP_DASHBOARD"
              access: "WIKI_MONITORING_ACCESS"
              priority: "P5"

 #- name: test-alert
 #  groups:
 #    - name: "test-alert"
 #      rules:
 #        - alert: KubePodNotReady-TEST
 #          expr: sum by(namespace, pod) (kube_pod_status_phase{pod="prometheus-operator-grafana-6bd9c9968c-jz7qm",job="kube-state-metrics",phase=~"Failed|Pending|Unknown"} * on(namespace, pod) group_left(owner_kind) kube_pod_owner{owner_kind!="Job"}) == 0
 #          for: 1m
 #          labels:
 #            severity: critical
 #          annotations:
 #            message: Pod {{ $labels.namespace }}/{{ $labels.pod }} has been in a non-ready state for longer than 15 minutes.
 #            runbook_url: https://github.com/kubernetes-monitoring/kubernetes-mixin/tree/master/runbook.md#alert-name-kubepodnotready

