prometheus:
  prometheusSpec:
    storageSpec:
       volumeClaimTemplate:
         spec:
          #storageClassName: gp2
           accessModes: ["ReadWriteOnce"]
           resources:
             requests:
               storage: 100Gi
         selector: {}

